### ISSUE TITLE
[PGO] assert "Mismatch in align instruction."

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#95755]
PGO Libraries pipelines fail with:

```
Mismatch in align instruction.
Containing IG: IG29
loopHeadPredIG: IG52
loopHeadIG: IG53
igInLoop: IG58
igInLoop->backEdge: IG57
igInLoop has align instruction for : IG61
Loop:
	IG53
	IG54
	IG55
	IG56
	IG57
	IG58
	IG59
	IG60
	IG61
	IG62
	IG63
	IG64
	IG65
	IG66
	IG67
	IG68
	IG69
	IG70
	IG71
	IG72
	IG73
	IG74
	IG75
	IG76
	IG77
	IG78
	IG79
	IG80
	IG81
	IG82
	IG83
	IG84
	IG85
	IG86
	IG87
	IG88
	IG89
	IG90
	IG91

Assert failure(PID 5048 [0x000013b8], Thread: 7396 [0x1ce4]): Assertion failed 'false' in 'Microsoft.CodeAnalysis.TopologicalSort:TryIterativeSort[System.__Canon](System.Collections.Generic.IEnumerable`1[System.__Canon],Microsoft.CodeAnalysis.TopologicalSortAddSuccessors`1[System.__Canon],byref):ubyte' during 'Generate code' (IL size 278; hash 0x33b57c85; Tier1-OSR)

    File: D:\a\_work\1\s\src\coreclr\jit\emit.cpp Line: 5900
    Image: C:\h\w\A83D0943\p\dotnet.exe

    Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.InternalsVisibleToAssembliesTest(languageVersion: CSharp10) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Exit code was -1073740286 but it should have been 42
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(242,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(55,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/Microsoft.Extensions.Options/tests/SourceGeneration.Unit.Tests/Main.cs(1217,0): at Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.InternalsVisibleToAssembliesTest(LanguageVersion languageVersion)
        --- End of stack trace from previous location ---
  Finished:    Microsoft.Extensions.Options.SourceGeneration.Unit.Tests
```
E.g.  https://dev.azure.com/dnceng-public/public/_build/results?buildId=491980&view=ms.vss-test-web.build-test-results-tab&runId=11398310&resultId=190916&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

cc @dotnet/jit-contrib

**Comment by kunalspathak** [comment]
I will look into this if it repro after #95836 is merged.

**Comment by kunalspathak** [comment]
> This pipeline is still red, but I haven't seen this assert pop up in the [last few runs](https://dev.azure.com/dnceng-public/public/_build?definitionId=145&_a=summary), and #95836 has been merged in. Should we close this issue?

Yep.
