### ISSUE TITLE
`Process.ExitCode` throws `InvalidOperationException`

### ISSUE THREAD

**Issue by lostmsu** [dotnet/runtime#95831]
### Description

Unable to read `ExitCode` after calling `WaitForExit`.

### Reproduction Steps

```csharp
var process = Process.GetProcessById(any_PID);
process.WaitForExit();
Console.WriteLine(process.ExitCode);
```

### Expected behavior

Exit code should be printed

### Actual behavior

Accessing `ExitCode` throws

> System.InvalidOperationException: Process was not started by this object, so requested information cannot be determined.
>    at System.Diagnostics.Process.EnsureState(State state)
>    at System.Diagnostics.Process.get_ExitCode()

### Known Workarounds

Obtain two different instances or get and hold on to `SafeHandle` from before wait call until after `ExitCode` access.

See also on [StackOverflow](https://stackoverflow.com/questions/47649119/what-means-an-invalidoperationexception-on-process-exittime-process-was-not-sta)

**Comment by alexrp** [comment]
This is basically by design and is very unlikely to change at this point, since it would completely change the implications of obtaining a `Process` object for an existing process.

Even if this was changed, what you're trying to do is fundamentally racy anyway. `GetProcessById()` could fail because the process is already gone, in which case you wouldn't get the exit code either. Anything you do here can only be 'best effort'.

**Comment by lostmsu** [comment]
I mean basically it is broken from the expectations standpoint of view. If change of the existing APIs is impossible for compatibility reasons, they should be deprecated with a warning and a more reliable API should be designed.

**Comment by fbrosseau** [comment]
> GetProcessById() could fail because the process is already gone

This is true, of course, however this is dwarfed by the fact that any cautious Windows project, ever, needs to do a dummy access on `SafeHandle` for the other properties to be reliable. I do not think "changing the implications of obtaining a Process" are a worry, because there is extremely little you can do on a Process object without needing to go acquire a proper handle to it.

**Comment by alexrp** [comment]
I agree that the `Process` API is...less than ideal (and for many more reasons than just this one), but there is a lot of existing code out there that uses `GetProcesses()`, `GetProcessById()`, and `GetProcessByName()` without expecting any resource acquisition to happen. IMO, whatever change is proposed here would need to ensure that such existing code doesn't suddenly open a bunch of process handles that stay open until the GC gets around to finalizing the `Process` object(s), as that would have an observable, negative effect on the reliability of that code.
