### ISSUE TITLE
Test failure Interop/COM/NETClients/Primitives/NETClientPrimitives/NETClientPrimitives.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#95842]
**Failed in:** [runtime-coreclr pgostress 20231208.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=494156&view=ms.vss-test-web.build-test-results-tab&runId=11465374&resultId=119331&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked syntheticpgo @ Windows.10.Amd64.Open
    - Interop/COM/NETClients/Primitives/NETClientPrimitives/NETClientPrimitives.cmd
    - Interop/COM/NETClients/Primitives/NETClientPrimitivesInALC/NETClientPrimitivesInALC.cmd
```

**Error message:**
```
Assert failure(PID 3664 [0x00000e50], Thread: 7728 [0x1e30]): m_crawl.pFunc->SanityCheck()

CORECLR! StackFrameIterator::CheckForSkippedFrames + 0x153 (0x720e8398)
CORECLR! StackFrameIterator::NextRaw + 0x74E (0x720ea135)
<no module>! <no symbol> + 0x0 (0xffffffff)
<no module>! <no symbol> + 0x0 (0x0a21d514)
<no module>! <no symbol> + 0x0 (0x0a21d4c0)
<no module>! <no symbol> + 0x0 (0x0a21d451)
<no module>! <no symbol> + 0x0 (0x0a21d3e3)
<no module>! <no symbol> + 0x0 (0x0a21c2b1)
<no module>! <no symbol> + 0x0 (0x0a210771)
<no module>! <no symbol> + 0x0 (0x058fe89e)
    File: D:_work1ssrccoreclrmstackwalk.cpp Line: 3153
    Image: C:hwB4A009D9pcorerun.exe


Return code:      1
Raw output file:      C:hwB4A009D9wA21B08F0uploadsCOMNETClientsPrimitivesNETClientPrimitivesoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwB4A009D9pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  NETClientPrimitives.dll 
Numeric RNG seed: 37
Byte test invariant: 101 + 70 = 171
Int16 test invariant: 22885 + -29882 = -6997
UInt16 test invariant: 22885 + 35654 = 58539
Int32 test invariant: 120215909 + 1447004998 = 1567220907
UInt32 test invariant: 120215909 + 1447004998 = 1567220907
Int64 test invariant: 120215909 + 1447004998 = 1567220907
UInt64 test invariant: 120215909 + 1447004998 = 1567220907
Single test invariant: 1202159.1 + 14470051 = 15672210
Double test invariant: 1202159.09 + 14470049.98 = 15672209.07
Int32 11 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 = 66
Int32 12 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 = 78
Byte[] marshalling
Int16[] marshalling
UInt16[] marshalling
Int32[] marshalling
UInt32[] marshalling
Int64[] marshalling
UInt64[] marshalling
Single[] marshalling
Double[] marshalling
Marshal strings as LPStr
Marshal strings as LPWStr
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 12/9/2023 7:38:42 AM
Processing C:corescorerun.exe.3664.dmp
Invoking: C:Program Files (x86)Windows Kits10Debuggerscdb.exe -c "$<C:hwB4A009D9		mp4ckteb.tmp" -z "C:corescorerun.exe.3664.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:corescorerun.exe.3664.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hwB4A009D9pPDB
Symbol search path is: C:hwB4A009D9pPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Sat Dec  9 07:38:48.000 2023 (UTC + 0:00)
System Uptime: 0 days 0:57:10.136
Process Uptime: 0 days 0:00:06.000
.........................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(e50.1e30): Unknown exception - code c0000602 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
eax=0337ba50 ebx=00000000 ecx=00000000 edx=00000000 esi=0337ba00 edi=0337ba50
eip=724775f2 esp=0337bd30 ebp=0337cdc8 iopl=0         nv up ei pl nz ac pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000216
coreclr!
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor208|25_209(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```

**Comment by v-wenyuxu** [comment]
**Failed again in:** [runtime-coreclr pgostress 20231215.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=501847&view=ms.vss-test-web.build-test-results-tab&runId=11680318&resultId=119640&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked syntheticpgo @ Windows.10.Amd64.Open
    - Interop/COM/NETClients/Primitives/NETClientPrimitives/NETClientPrimitives.cmd
    - Interop/COM/NETClients/Primitives/NETClientPrimitivesInALC/NETClientPrimitivesInALC.cmd
```

**Error message:**
```
 Assert failure(PID 7192 [0x00001c18], Thread: 7196 [0x1c1c]): m_crawl.pFunc->SanityCheck()

CORECLR! StackFrameIterator::CheckForSkippedFrames + 0x153 (0x72708398)
CORECLR! StackFrameIterator::NextRaw + 0x74E (0x7270a135)
<no module>! <no symbol> + 0x0 (0xffffffff)
<no module>! <no symbol> + 0x0 (0x0985f1a4)
<no module>! <no symbol> + 0x0 (0x0985f150)
<no module>! <no symbol> + 0x0 (0x0985f0e1)
<no module>! <no symbol> + 0x0 (0x0985f043)
<no module>! <no symbol> + 0x0 (0x0985ddf9)
<no module>! <no symbol> + 0x0 (0x09851071)
<no module>! <no symbol> + 0x0 (0x04daeb3e)
    File: D:_work1ssrccoreclrmstackwalk.cpp Line: 3153
    Image: C:hwA179091Cpcorerun.exe


Return code:      1
Raw output file:      C:hwA179091CwB6B40A09uploadsCOMNETClientsPrimitivesNETClientPrimitivesoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwA179091Cpcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  NETClientPrimitives.dll 
Numeric RNG seed: 37
Byte test invariant: 101 + 70 = 171
Int16 test invariant: 22885 + -29882 = -6997
UInt16 test invariant: 22885 + 35654 = 58539
Int32 test invariant: 120215909 + 1447004998 = 1567220907
UInt32 test invariant: 120215909 + 1447004998 = 1567220907
Int64 test invariant: 120215909 + 1447004998 = 1567220907
UInt64 test invariant: 120215909 + 1447004998 = 1567220907
Single test invariant: 1202159.1 + 14470051 = 15672210
Double test invariant: 1202159.09 + 14470049.98 = 15672209.07
Int32 11 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 = 66
Int32 12 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 = 78
Byte[] marshalling
Int16[] marshalling
UInt16[] marshalling
Int32[] marshalling
UInt32[] marshalling
Int64[] marshalling
UInt64[] marshalling
Single[] marshalling
Double[] marshalling
Marshal strings as LPStr
Marshal strings as LPWStr
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 12/16/2023 7:51:04 AM
Processing C:corescorerun.exe.7192.dmp
Invoking: C:Program Files (x86)Windows Kits10Debuggerscdb.exe -c "$<C:hwA179091C		mpvlyqki.tmp" -z "C:corescorerun.exe.7192.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:corescorerun.exe.7192.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hwA179091CpPDB
Symbol search path is: C:hwA179091CpPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Sat Dec 16 07:51:13.000 2023 (UTC + 0:00)
System Uptime: 0 days 0:13:09.650
Process Uptime: 0 days 0:00:09.000
.........................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(1c18.1c1c): Unknown exception - code c0000602 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
eax=007fb940 ebx=00000000 ecx=00000000 edx=00000000 esi=007fb8f0 edi=007fb940
eip=72a97714 esp=007fbc20 ebp=007fccb8 iopl=0         nv up ei pl nz ac pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000216
corecl
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor210|25_211(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```

**Comment by AaronRobinsonMSFT** [comment]
I can't reproduce this any more. Please re-open if it reproduces.
