### ISSUE TITLE
Reachable assert in ECDiffieHellmanCng

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#95886]
The following test will produce an assertion in ECDiffieHellmanCng for debug builds of the runtime.

```C#
[Fact]
public static void ECDiffieHellman_Assert()
{
    X509Certificate2 loaded;

    using (ECDsa ca = ECDsa.Create(ECCurve.NamedCurves.nistP256))
    {
        CertificateRequest req = new("CN=potatos", ca, HashAlgorithmName.SHA256);

        using (X509Certificate2 cert = req.CreateSelfSigned(DateTimeOffset.Now, DateTimeOffset.Now.AddDays(3)))
        {
            loaded = new X509Certificate2(cert.Export(X509ContentType.Pkcs12, "carrots"), "carrots");
        }
    }

    using (ECDiffieHellman partyB = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256))
    using (ECDiffieHellman partyAPrivateKey = loaded.GetECDiffieHellmanPrivateKey())
    using (ECDiffieHellman partyAPublicKey = loaded.GetECDiffieHellmanPublicKey())
    {
        loaded.Dispose();
        byte[] derivedB = partyB.DeriveKeyFromHash(partyAPublicKey.PublicKey, HashAlgorithmName.SHA256, null, null);
        byte[] derivedA = partyAPrivateKey.DeriveKeyFromHash(partyB.PublicKey, HashAlgorithmName.SHA256, null, null);
        Assert.Equal(derivedB, derivedA);

    }
}
```

Which will produce an assertion:

```
Process terminated. Assertion failed.
   at System.Security.Cryptography.ECDiffieHellmanCng..ctor(CngKey key, Boolean transferOwnership) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/ECDiffieHellmanCng.cs:line 38
   at System.Security.Cryptography.X509Certificates.CertificatePal.<>c.<GetECDiffieHellmanPrivateKey>b__71_1(CngKey cngKey) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/CertificatePal.Windows.PrivateKey.cs:line 67
   at System.Security.Cryptography.X509Certificates.CertificatePal.GetPrivateKey[T](Func`2 createCsp, Func`2 createCng) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/CertificatePal.Windows.PrivateKey.cs:line 210
   at System.Security.Cryptography.X509Certificates.CertificatePal.GetECDiffieHellmanPrivateKey() in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/CertificatePal.Windows.PrivateKey.cs:line 65
   at System.Security.Cryptography.X509Certificates.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/CertificateExtensionsCommon.cs:line 70
   at System.Security.Cryptography.X509Certificates.X509Certificate2.GetECDiffieHellmanPrivateKey() in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X509Certificate2.cs:line 720
```

Which is

https://github.com/dotnet/runtime/blob/0fae364617f03d1003af0f0b49e57876e51875d4/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/ECDiffieHellmanCng.cs#L38

If the assertion is invalid, then it should be removed. Otherwise, we should address what the assertion is asserting.

**Comment by KevinCathcart** [comment]
The assert was introduced with #72120, but the relevant code path there previously triggered an exception (verified by running against an older runtime on my machine), which is also not good, because `.GetECDiffieHellmanPrivateKey()` is documented as returning null, not throwing.

I'm no CNG expert, but from what I can tell the Debug.Assert there is correct.

My understanding is CNG has the unfortunate limitation that keys originally created as ECDSA keys cannot be used for ECDH, but keys created as ECDH can be used for either ECDSA or ECDH.

So my understanding is that the only way for unit test in the top post to work on Windows while backed by CNG is if:
a) `ECDsa.Create` were changed to create the key as an ECDH private key such that CNG allows it to work with ECDH and ECDS, or
b) `.GetECDiffieHellmanPrivateKey()` were enhanced to detect if the private key is ECDSA but is readable, and if so, read the key, and re-create it as ECDH. 

I'm not actually sure if either are desirable or not.

If neither such change is made, then IMHO, the correct behavior would be:
1. `loaded.loaded.HasPrivateKey = true`
1. `loaded.GetECDiffieHellmanPublicKey()` works because the cert allows all key usages by not constraining them.
1. `loaded.GetECDiffieHellmanPrivateKey()` returns null, because no private key that is usable for ECDH is currently available.
1. both `GetECDsa(Public|Private)Key` extension methods work.

**Comment by vcsjones** [comment]
> ) ECDsa.Create were changed to create the key as an ECDH private key such that CNG allows it to work with ECDH and ECDS, or

This is not a full fix, because the actual problem from the example is that the PKCS12 has a bag attribute saying "I am ECDSA, so my private key material should be imported in to CNG as ECDSA". So if we ever get a PKCS12/PFX with one of those bag attributes, the problem remains.

> .GetECDiffieHellmanPrivateKey() were enhanced to detect if the private key is ECDSA but is readable, and if so, read the key, and re-create it as ECDH.

That is... possible, but CNG gets a little iffy about exporting private keys that were imported from a PFX. They would need to be "encrypted" exports, and we would need to tear apart the PKCS#8 manually because the PKCS#8 blob _also_ preserves the key algorithm, so we would just end up round-tripping back to the same problem. This also wouldn't work if the key were totally non-exportable (either by policy or by provider limitation).

The last option you outlined is probably "right" to me, in spirit with CNG. If someone really wanted to, I suppose they could call `GetECDsaPrivateKey`, export the parameters if they are exportable, and import them back in as ECDiffieHellman.
