### ISSUE TITLE
[wasm] `DebuggerTests.ExceptionTests.ExceptionTestAllWithReload` failing with `Expected to only pause because of an exception.`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#95943]
Failing on rolling [build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=497276&view=results), and [log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-70eb7873854843548f/chrome-DebuggerTests.ExceptionTests/1/console.670e93af.log?helixlogtype=result):

```
[xUnit.net 00:01:34.81]     DebuggerTests.ExceptionTests.ExceptionTestAllWithReload(entry_method_name: "[debugger-test] DebuggerTests.ExceptionTestsClassD"���, class_name: "System.Exception", line_number: 76, class_name_pause: "DebuggerTests.ExceptionTestsClassDefault") [FAIL]
  Failed DebuggerTests.ExceptionTests.ExceptionTestAllWithReload(entry_method_name: "[debugger-test] DebuggerTests.ExceptionTestsClassD"���, class_name: "System.Exception", line_number: 76, class_name_pause: "DebuggerTests.ExceptionTestsClassDefault") [12 s]
  Error Message:
   Assert.Equal() Failure: [Expected to only pause because of an exception. {
  "callFrames": [
    {
      "callFrameId": "7777036982711948032.2.0",
      "functionName": "",
      "functionLocation": {
        "scriptId": "231",
        "lineNumber": 0,
        "columnNumber": 0
      },
      "location": {
        "scriptId": "231",
        "lineNumber": 20,
        "columnNumber": 4
      },
      "url": "",
      "scopeChain": [
        {
          "type": "block",
          "object": {
            "type": "object",
            "className": "Object",
            "description": "Object",
            "objectId": "7777036982711948032.2.2513"
          },
          "startLocation": {
            "scriptId": "231",
            "lineNumber": 7,
            "columnNumber": 4
          },
          "endLocation": {
            "scriptId": "231",
            "lineNumber": 22,
            "columnNumber": 1
          }
        },
        {
          "type": "module",
          "object": {
            "type": "object",
            "className": "Object",
            "description": "Object",
            "objectId": "7777036982711948032.2.2514"
          },
          "startLocation": {
            "scriptId": "231",
            "lineNumber": 0,
            "columnNumber": 0
          },
          "endLocation": {
            "scriptId": "231",
            "lineNumber": 25,
            "columnNumber": 1
          }
        },
        {
          "type": "global",
          "object": {
            "type": "object",
            "className": "Window",
            "description": "Window",
            "objectId": "7777036982711948032.2.2515"
          }
        }
      ],
      "this": {
        "type": "undefined"
      },
      "canBeRestarted": false
    }
  ],
  "reason": "step",
  "hitBreakpoints": [],
  "sessionId": null
}]

Expected: exception
Actual:   step
  Stack Trace:
     at DebuggerTests.DebuggerTestBase.AssertEqual(Object expected, Object actual, String label) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1311
   at DebuggerTests.ExceptionTests.WaitForManagedException(JObject pause_location) in /_/src/mono/wasm/debugger/DebuggerTestSuite/ExceptionTests.cs:line 359
   at DebuggerTests.ExceptionTests.ExceptionTestAllWithReload(String entry_method_name, String class_name, Int32 line_number, String class_name_pause) in /_/src/mono/wasm/debugger/DebuggerTestSuite/ExceptionTests.cs:line 312
```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Expected to only pause because of an exception",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=497276
**Error message validated:** `Expected to only pause because of an exception`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 12/13/2023 3:05:48 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not been hit in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0
