### ISSUE TITLE
[wasm] Lot of HybridGlobalization test failures with NodeJS

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#95983]
## Build Information
Build:https://dev.azure.com/dnceng-public/public/_build/results?buildId=498273
Build error leg or test failing: WasmTestOnNodeJS-System.Globalization.Hybrid.WASM.Tests
Pull request: https://github.com/dotnet/runtime/pull/95959

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Failing tests can be seen in the generated [wasm-console.log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-95959-merge-62e883a1ffe143939f/WasmTestOnNodeJS-System.Globalization.Hybrid.WASM.Tests/1/xharness-output/wasm-console.log?helixlogtype=result), like:

```
[FAIL] System.Globalization.Tests.DateTimeFormatInfoAbbreviatedMonthNames.AbbreviatedMonthNames_Get_ReturnsExpected_HybridGlobalization(cultureName: "nl-NL", expected: ["jan.", "feb.", "mrt.", "apr.", "mei", ···])
Failed for culture: nl-NL on index: 0. Expected: jan., Actual: jan
   at System.Globalization.Tests.DateTimeFormatInfoAbbreviatedMonthNames.AbbreviatedMonthNames_Get_ReturnsExpected_HybridGlobalization(String cultureName, String[] expected)
   at System.Object.InvokeStub_DateTimeFormatInfoAbbreviatedMonthNames.AbbreviatedMonthNames_Get_ReturnsExpected_HybridGlobalization(Object , Span`1 )
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

[FAIL] System.Globalization.Tests.DateTimeFormatInfoShortDatePattern.ShortDatePattern_Get_ReturnsExpected_HybridGlobalization(cultureName: "en-CH", expected: "dd/MM/yyyy")
Failed for culture: en-CH. Expected: dd/MM/yyyy, Actual: dd.MM.yyyy
   at System.Globalization.Tests.DateTimeFormatInfoShortDatePattern.ShortDatePattern_Get_ReturnsExpected_HybridGlobalization(String cultureName, String expected)
   at System.Object.InvokeStub_DateTimeFormatInfoShortDatePattern.ShortDatePattern_Get_ReturnsExpected_HybridGlobalization(Object , Span`1 )
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

[FAIL] System.Globalization.Tests.DateTimeFormatInfoNativeCalendarName.NativeCalendarName_Get_ReturnsExpected_HybridGlobalization(format: DateTimeFormatInfo { AbbreviatedDayNames = ["እሑድ", "ሰኞ", "ማክሰ", "ረቡዕ", "ሐሙስ", ···], AbbreviatedMonthGenitiveNames = >
Assert.Equal() Failure: Strings differ
           ↓ (pos 0)
Expected: "GREGORIAN"
Actual:   "gregory"
           ↑ (pos 0)
   at System.Object.InvokeStub_DateTimeFormatInfoNativeCalendarName.NativeCalendarName_Get_ReturnsExpected_HybridGlobalization(Object , Span`1 )
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

222 failures.

And similar failures are seen for `System.Globalization.Tests`.

cc @ilonatommy

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by ilonatommy** [comment]
On the PR that was switching on the HG job, I did not manage to have the NodeJS version updated and I adjusted the tests on Windows to the old version. Now it seems the changes got propagated just fine. It's an easy fix
