### ISSUE TITLE
Exception when adding console logging

### ISSUE THREAD

**Issue by esbenbjerre** [dotnet/runtime#96010]
### Description

`ILoggingBuilder.AddConsole()` throws an exception.

### Reproduction Steps

```fsharp
#r "nuget: Microsoft.Extensions.Logging"
#r "nuget: Microsoft.Extensions.Logging.Console"

open Microsoft.Extensions.Logging
open Microsoft.Extensions.Logging.Console

let loggerFactory = LoggerFactory.Create(fun builder -> builder.AddConsole() |> ignore)
let logger = loggerFactory.CreateLogger("FSI")
```
will throw
```
error FS0193: Could not load file or assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

File name: 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Microsoft.Extensions.Logging.ConsoleLoggerExtensions.AddConsole(ILoggingBuilder builder)
   at FSI_0004.loggerFactory@7.Invoke(ILoggingBuilder builder) in /Users/ebj/Source/frc.value-at-risk/src/ValueAtRisk.Core/Playground2.fsx:line 7
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Microsoft.Extensions.Logging.LoggerFactory.Create(Action`1 configure)
   at <StartupCode$FSI_0004>.$FSI_0004.main@() in /Users/ebj/Source/frc.value-at-risk/src/ValueAtRisk.Core/Playground2.fsx:line 7
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Stopped due to error
```
while pinning the versions to 7.0.0 works
```fsharp
#r "nuget: Microsoft.Extensions.Logging, 7.0.0"
#r "nuget: Microsoft.Extensions.Logging.Console, 7.0.0"
```

Note that adding a reference to `System.Text.Json` does not help.

### Expected behavior

Should now throw an exception.

### Actual behavior

Throws exception.

### Regression?

It appears to be OK with `Microsoft.Extensions.Logging 7.0.0` or when using .NET 8.0.100.

### Known Workarounds

Use version 7.0.0.

### Configuration

.NET 7.0.306
macOS Ventura 13.5.2 (ARM)

**Comment by esbenbjerre** [comment]
Closing as it appears to be solved in .NET 8.
