### ISSUE TITLE
ValidateOnStart() does not work in Azure Function

### ISSUE THREAD

**Issue by iamprovidence** [dotnet/runtime#96034]
### Description

I'm using `OptionsBuilderExtensions.ValidateOnStart` to validate some settings to fail fast if there are any values missing etc in Azure function host.

The issue I'm experiencing the configuration does not get validated.

### Reproduction Steps

1. Create new Azure Function project weith HTTP trigger in .Net8.0
2. Install Microsoft.Extensions.Options nuget. You can edit .csproj and add next line:

```
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
```

3. Modify `Program.cs` setup, so its validate options:

```csharp
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureServices(services =>
    {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();

        services
            .AddOptions<MyOptions>()
            .Validate(x => false)
            .ValidateOnStart();
    })
    .Build();

host.Run();

public class MyOptions
{
}
```
I also tries to add `Startup.cs`, but it still does not work:

```csharp
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;

[assembly: FunctionsStartup(typeof(FunctionApp.Startup))]

namespace FunctionApp
{
    public class MyOptions
    {
    }

    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var services = builder.Services;

            services
                .AddOptions<MyOptions>()
                .Validate(x => false)
                .ValidateOnStart();
        }
    }
}
```

### Expected behavior

When I start application there is an exception with "A validation error has occurred" message

### Actual behavior

No exception is thrown. The application continue working

**Comment by AliYussef** [comment]
Having same issue with isolated .net8 durable function

**Comment by tarekgh** [comment]
This looks more Azure function host issue more than the runtime issue.

**Comment by ericstj** [comment]
@fabiocav does anything look off about how this Azure Function is set up for validation?  

If I remove all the Azure-specific references here I'll see the exception as expected:
```c#
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var host = new HostBuilder()    
    .ConfigureServices(services =>
    {
        services
            .AddOptions<MyOptions>()
            .Validate(x => false)
            .ValidateOnStart();
    })
    .Build();
host.Run();
public record class MyOptions;
```
```
Unhandled exception. Microsoft.Extensions.Options.OptionsValidationException: A validation error has occurred.
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c.<Get>b__10_0(String name, IOptionsFactory`1 factory)
   at Microsoft.Extensions.Options.OptionsCache`1.<>c__DisplayClass3_1`1.<GetOrAdd>b__2()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.Extensions.DependencyInjection.OptionsBuilderExtensions.<>c__DisplayClass0_1`1.<ValidateOnStart>b__1()
   at Microsoft.Extensions.Options.StartupValidator.Validate()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Options.StartupValidator.Validate()
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(<>c__DisplayClass15_0&)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in C:\scratch\validate\Program.cs:line 14
```

I could imagine that Azure Functions might somehow override how Host startup works, either by implementing their own Host, or somehow wrapping this...  ASP.NET works by using the M.E.Hosting Host - so it benefits when we move functionality into the host like [IStartupValidator](https://github.com/dotnet/runtime/commit/693eef6417353d45d126fa05365665bccf5b82d9) and [IHostedLifecycleServices](https://github.com/dotnet/runtime/commit/abcd91ce89a3d47cd140d4973afd8c2badfa4dd7).  cc @steveharter

**Comment by ericstj** [comment]
Actually - just to double check.  I assumed you were targeting `net8.0` here - @iamprovidence can you confirm.  Also - can you please share your full repro project?

**Comment by iamprovidence** [comment]
@ericstj . You are correct. I am targeting .net8.0, but is just a clear project scaffolded from VisualStudio's template:
github.com/iamprovidence/AzureFuncValidateConfig

I have also checked .net6.0 and it does not work there either. However, in .net6.0 the issues happen because `.ValidationOnStartup()` relies on a hosted service (`ValidationHostedService`) which is not supported in the azure function app.
However, in .net8.0 it is no longer the case, so I would expect it to work, but it doesn't...

**Comment by ericstj** [comment]
Thank you for that repro.  It always helps to have a repro to ensure we're looking at the same thing.  

Have a look at this in the debugger:
<img width="1269" alt="image" src="https://github.com/dotnet/runtime/assets/8918108/55b992db-76a2-4995-bac7-b473f2949f20">

Those are all 5.0 versions of the extensions libraries.  Those are coming in from the functions package references - and since you're running this as a console (and not web) project they don't get a newer version with the framework.  If I add a reference to the 8.0 version of hosting it works as expected:
```xml
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
```
With this added to the project I will see:
```
Microsoft.Extensions.Options.OptionsValidationException
  HResult=0x80131500
  Message=A validation error has occurred.
  Source=Microsoft.Extensions.Options
  StackTrace:
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name) in /_/src/libraries/Microsoft.Extensions.Options/src/OptionsFactory.cs:line 87
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c.<Get>b__10_0(String name, IOptionsFactory`1 factory) in /_/src/libraries/Microsoft.Extensions.Options/src/OptionsMonitor.cs:line 100
   at Microsoft.Extensions.Options.OptionsCache`1.<>c__DisplayClass3_1`1.<GetOrAdd>b__2() in /_/src/libraries/Microsoft.Extensions.Options/src/OptionsCache.cs:line 68
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode) in /_/src/libraries/System.Private.CoreLib/src/System/Lazy.cs:line 323
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor) in /_/src/libraries/System.Private.CoreLib/src/System/Lazy.cs:line 347
   at System.Lazy`1.CreateValue() in /_/src/libraries/System.Private.CoreLib/src/System/Lazy.cs:line 427
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument) in /_/src/libraries/Microsoft.Extensions.Options/src/OptionsCache.cs:line 66
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name) in /_/src/libraries/Microsoft.Extensions.Options/src/OptionsMonitor.cs:line 100
   at Microsoft.Extensions.DependencyInjection.OptionsBuilderExtensions.<>c__DisplayClass0_1`1.<ValidateOnStart>b__1() in /_/src/libraries/Microsoft.Extensions.Options/src/OptionsBuilderExtensions.cs:line 34
   at Microsoft.Extensions.Options.StartupValidator.Validate() in /_/src/libraries/Microsoft.Extensions.Options/src/ValidateOnStart.cs:line 29
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Options.StartupValidator.Validate() in /_/src/libraries/Microsoft.Extensions.Options/src/ValidateOnStart.cs:line 43
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__15.MoveNext() in /_/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs:line 111
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(<>c__DisplayClass15_0& ) in /_/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs:line 171
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__15.MoveNext() in /_/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs:line 118
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext() in /_/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/HostingAbstractionsHostExtensions.cs:line 67
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext() in /_/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/HostingAbstractionsHostExtensions.cs:line 79
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host) in /_/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/HostingAbstractionsHostExtensions.cs:line 53
   at Program.<Main>$(String[] args) in C:\scratch\AzureFuncValidateConfig\FunctionApp\FunctionAppNet8\Program.cs:line 23
```

**Comment by iamprovidence** [comment]
@ericstj Amazing work! Thanks for the help. It does solve my issue.

I think it kind of neglects the point of this story since one has to depend on both `Microsoft.Extensions.Options` and `Microsoft.Extensions.Hosting`
https://github.com/dotnet/runtime/issues/84347
However, it is fine with me.

I am not sure whether you plan to do any in the code, VisualStudio's template or do anything for .Net6, but feel free to close this bug. Once again, thanks for your time

**Comment by ericstj** [comment]
> I think it kind of neglects the point of this story since one has to depend on both Microsoft.Extensions.Options and Microsoft.Extensions.Hosting

The point was to allow a _library_ author to avoid the dependency, which it still does.  In this case the _application_ is already depending on `Microsoft.Extensions.Hosting` through the Azure Functions references it's just difficult to see that since it's transitive.  It's unusual for folks to mix different versions of extensions together.  It is true that the feature refactoring required changes up stack and requires folks to update in order to get that feature.  The same is true for any feature that interacts with hosting, and often DI.  At the limit this problem goes away as folks update their dependencies.  

We should find out why AzureFunctions is still depending on the out-of-support packages and how to suggest folks update those.  I opened https://github.com/Azure/azure-functions-dotnet-worker/issues/2176 to track that.

I'm not inclined to do much else here - perhaps we can document this as a breaking change so that others might find it more easily.

**Comment by rogerospinaglobant** [comment]
@ericstj Thank so much. It worked
