### ISSUE TITLE
System.ExecutionEngineException: Attempting to JIT compile method '(wrapper runtime-invoke) object <Module>:runtime_invoke_void_CGRect_CGRect_single (object,intptr,intptr,intptr)' while running in aot-only mode.

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#96063]
### Description

Calling a method with the following signature using reflection:

> public static void TheMethod (CGRect a, CGRect b, float c)

throws:

```
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
  ---> System.ExecutionEngineException: Attempting to JIT compile method '(wrapper runtime-invoke) object <Module>:runtime_invoke_void_CGRect_CGRect_single (object,intptr,intptr,intptr)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MySimpleApp.Program.FloatingPointStretTrampolineTest() in /Users/rolf/work/maccore/mono-master/xamarin-macios/tests/dotnet/MySimpleApp/AppDelegate.cs:line 31
```

### Reproduction Steps

1. Create a new maccatalyst project: `mkdir testapp && cd testapp && dotnet new maccatalyst`
2. Replace `Main.cs` with:

```cs
using System;
using System.Reflection;
using System.Runtime.InteropServices;

using CoreGraphics;
using Foundation;

namespace MySimpleApp {
	public class Program {
		static int Main (string [] args)
		{
			try {
				FloatingPointStretTrampolineTest ();
			} catch (Exception e) {
				Console.WriteLine (e);
				return 1;
			}

			return 0;
		}

		public static void FloatingPointStretTrampolineTest ()
		{
			CGRect rect = default (CGRect);
			TheMethod (rect, rect, 3); // calling the method first doesn't fix anything.
			typeof (Program).GetMethod ("TheMethod", BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public).Invoke (null, new object [] { rect, rect, (float) 3 });
		}

		// static or not doesn't matter
		// removing one of the CGRect arguments makes the problem go away
		// the float argument is significant:
		// * remove it and the problem goes away.
		// * change it to double and the problem is still there
		// * change it to int and the problem goes away
		public static void TheMethod (CGRect a, CGRect b, float c)
		{
		}
	}
}
```

3. Build (must be on arm64): `dotnet build`
4. Run:

```
$ ./bin/Debug/net9.0-maccatalyst/maccatalyst-arm64/testapp.app/Contents/MacOS/testapp
2023-12-15 15:12:35.242 testapp[53932:15039935] Microsoft.MacCatalyst: Invalid IDE Port: -1
2023-12-15 15:12:35.244 testapp[53932:15039929] Microsoft.MacCatalyst: Debugger not loaded (disabled).
2023-12-15 15:12:35.244 testapp[53932:15039929] Microsoft.MacCatalyst: Profiler not loaded (disabled)
2023-12-15 15:12:35.306 testapp[53932:15039929] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
2023-12-15 15:12:35.306 testapp[53932:15039929]  ---> System.ExecutionEngineException: Attempting to JIT compile method '(wrapper runtime-invoke) object <Module>:runtime_invoke_void_CGRect_CGRect_single (object,intptr,intptr,intptr)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
2023-12-15 15:12:35.307 testapp[53932:15039929]    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
2023-12-15 15:12:35.307 testapp[53932:15039929]    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2023-12-15 15:12:35.307 testapp[53932:15039929]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
2023-12-15 15:12:35.307 testapp[53932:15039929]    at MySimpleApp.Program.FloatingPointStretTrampolineTest() in /Users/rolf/work/maccore/mono-master/xamarin-macios/tests/dotnet/MySimpleApp/MacCatalyst/testapp/Main.cs:line 26
   at MySimpleApp.Program.Main(String[] args) in /Users/rolf/work/maccore/mono-master/xamarin-macios/tests/dotnet/MySimpleApp/MacCatalyst/testapp/Main.cs:line 13
```

### Expected behavior

No exception.

### Actual behavior

ExecutionEngineException

### Regression?

Yes, somewhere in this range:

https://github.com/dotnet/runtime/compare/a26802aa5793060c512359c2be83e9a4c51964c1...ab1a8224cdf115b65e0db5dc88d11f205068f444

This started happening in a maestro bump: https://github.com/xamarin/xamarin-macios/pull/19633

### Known Workarounds

None

### Configuration

Latest .NET 9.

**Comment by vargaz** [comment]
Probably a dup of:
https://github.com/dotnet/runtime/issues/96041

**Comment by jamesingreersc** [comment]
Has there been any update or answer on this? Our .Net iOS project is unusable at .Net 8. Was working fine at .Net 7. Been working on this problem for almost 2 days.

Attempting to JIT compile method 'string DSDRouteManager.Shared.Utils:RunAiME (string,System.Collections.Generic.Dictionary`2<string, object>)' while running in aot-only mode.

**Comment by vargaz** [comment]
Thats probably a different problem.

**Comment by rolfbjarne** [comment]
> Probably a dup of: #96041

I can't reproduce anymore, so probably.
