### ISSUE TITLE
`TraceUtils.CopyStringDictionary()` is broken

### ISSUE THREAD

**Issue by Zastai** [dotnet/runtime#96092]
### Description

`TraceUtils.CopyStringDictionary()` (from `System.Configuration.ConfigurationManager`) only works for empty dictionaries.

This is because it uses a `foreach` loop over a `StringDictionary` but uses a `string` loop variable while the enumeration provides dictionary entries.

### Reproduction Steps

1. `dotnet new console`
2. `dotnet add package System.Configuration.ConfigurationManager`
3. edit Program.cs:
   ```cs
   ```
4. create app.config:
   ```xml
    <configuration>
      <system.diagnostics>
        <sources>
          <source name="Foo" switch="Foo">
            <listeners>
              <add name="console" type="System.Diagnostics.ConsoleTraceListener" traceOutputOptions="DateTime,ProcessId" />
            </listeners>
          </source>
        </sources>
        <switches>
          <add name="Foo" value="All" />
        </switches>
      </system.diagnostics>
    </configuration>
   ```
   (note incorrect use of `switch` instead of `switchName`)
5. `dotnet run`

### Expected behavior

A trace message is shown, similar to

```
Foo Information: 0 : Hello World
    ProcessId=1234
    DateTime=2023-12-16T12:34:26.1102915Z
```

### Actual behavior

The application abends:

```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Collections.DictionaryEntry' to type 'System.String'.
   at System.Diagnostics.TraceUtils.CopyStringDictionary(StringDictionary source, StringDictionary dest)
   at System.Diagnostics.TraceConfiguration.InitializingTraceSource(Object sender, InitializingTraceSourceEventArgs e)
   at System.Diagnostics.TraceSource.OnInitializing(InitializingTraceSourceEventArgs e)
   at System.Diagnostics.TraceSource.Initialize()
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args)
   at System.Diagnostics.TraceSource.TraceInformation(String message)
   at Program.<Main>$(String[] args)
```

### Regression?

Regression from .NET Framework.
The implementation added in .NET 7 seems to have always had this issue; it's unfortunate that there were no unit tests for this (it also feels like this could/should be detectable by source analyzers).

### Known Workarounds

None.

### Configuration

Tested with .NET SDK 8.0.100

**Comment by buyaa-n** [comment]
@steveharter PTAL

**Comment by Zastai** [comment]
Minor update on the expected behaviour: it should probably error out with an `ArgumentException`, saying `switch` is not a supported attribute for a `TraceSource`, rather than silently ignoring it.
