### ISSUE TITLE
.NET 8 ReadyToRun regression bug: TypeLoadException 

### ISSUE THREAD

**Issue by bitbonk** [dotnet/runtime#96225]
### Description

When publishing an application with ReadyToRun in .NET 8, that includes the below C# type hierarchy, the following exception is thrown during the start of the published application:
```
System.TypeLoadException: Return type in method 'ReadyToRunRepro.DataElementBase`1[TIdentifier].get_Id()' on type 'ReadyToRunRepro.DataElementBase`1[TIdentifier]' from assembly 'ReadyToRunRepro, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is not compatible with base type method 'ReadyToRunRepro.DataElementBase.get_Id()
```

The application with the same type hierarchy works without problems in .NET 7.

The type hierarchy:
```csharp
public abstract class DataElementBase
{
    private protected DataElementBase(IdentifierBase id)
    {
        this.Id = id;
    }

    public virtual IdentifierBase Id { get; }
}

public abstract class DataElementBase<TIdentifier> : DataElementBase
    where TIdentifier : DataElementIdentifierBase
{
    private protected DataElementBase(
        TIdentifier id)
        : base(id)
    {
    }
    
    public override TIdentifier Id => (TIdentifier) base.Id;
}

public sealed class EventDefinition : DataElementBase<EventDefinitionIdentifier>
{
    internal EventDefinition(EventDefinitionIdentifier id)
        : base(id)
    {
    }
}

public abstract class EventDefinitionBase : DataElementBase<EventDefinitionIdentifier>
{
    private protected EventDefinitionBase(
        NodeIdentifier nodeId,
        EventSettingsBase settings,
        Type? argumentType = null)
        : base(
            new EventDefinitionIdentifier(nodeId))
    {
    }

    protected internal abstract EventSettingsBase Settings { get; }
}

public abstract class EventDefinitionBase<TSettings> : EventDefinitionBase
    where TSettings : EventSettingsBase
{
    private protected EventDefinitionBase(
        NodeIdentifier nodeId,
        TSettings settings,
        Type? argumentType = null)
        : base(nodeId, settings, argumentType)
    {
        this.Settings = settings;
    }

    protected internal override TSettings Settings { get; }
}

public abstract class IdentifierBase
{
}

public sealed class NodeIdentifier : IdentifierBase, IEquatable<NodeIdentifier>
{
    public bool Equals(NodeIdentifier? other)
    {
        return true;
    }
}

public abstract class OwnedIdentifierBase<TOwner> : IdentifierBase, IEquatable<OwnedIdentifierBase<TOwner>>
    where TOwner : IdentifierBase
{
    public OwnedIdentifierBase(TOwner owner)
    {
        this.Owner = owner;
    }

    public TOwner Owner { get; }

    public bool Equals(OwnedIdentifierBase<TOwner>? other)
    {
        return true;
    }
}

public abstract class DataElementIdentifierBase : OwnedIdentifierBase<NodeIdentifier>
{
    protected DataElementIdentifierBase(NodeIdentifier owner)
        : base(owner)
    {
    }
}

public abstract record DataElementSettingsBase
{
    private protected DataElementSettingsBase()
    {
    }
}

public sealed class EventDefinitionIdentifier : DataElementIdentifierBase
{
    public EventDefinitionIdentifier(NodeIdentifier owner)
        : base(owner)
    {
    }
}

public abstract record EventSettingsBase : DataElementSettingsBase;

public record EventSettings : EventSettingsBase;
```

### Reproduction Steps

1. Clone the repo https://github.com/bitbonk/ReadyToRunRepro and run 

   `dotnet publish .\ReadyToRunRepro\ReadyToRunRepro.csproj  --configuration=Release -p:PublishReadyToRun=true --runtime win-x64 --self-contained`
   
   followed by 

   `.\ReadyToRunRepro\bin\Release\net7.0\win-x64\publish\ReadyToRunRepro.exe`

2. See that the worker service starts correctly and runs without errors
3. Change the target framework in `ReadyToRunRepro.csproj` to .NET 8: `<TargetFramework>net8.0</TargetFramework>`
4. Publish again with the same command as in 1.: 

   `dotnet publish .\ReadyToRunRepro\ReadyToRunRepro.csproj  --configuration=Release -p:PublishReadyToRun=true --runtime win-x64 --self-contained`
   
   and then start the published .NET 8 exe:

   `.\ReadyToRunRepro\bin\Release\net8.0\win-x64\publish\ReadyToRunRepro.exe`

### Expected behavior

The worker service application published with a .NET 8 TFM starts and runs without problems.

### Actual behavior

the following exception occurs:

```
Unhandled exception. System.TypeLoadException: Return type in method 'ReadyToRunRepro.DataElementBase`1[TIdentifier].get_Id()' on type 'ReadyToRunRepro.DataElementBase`1[TIdentifier]' from assembly 'ReadyToRunRepro, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is not compatible with base type method 'ReadyToRunRepro.DataElementBase.get_Id()'.
   at ReadyToRunRepro.Service..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in C:\source\ReadyToRunRepro\ReadyToRunRepro\Program.cs:line 8
```

### Regression?

Yes this is a regression, since it works with a .NET 7 TFM.

### Known Workarounds

none is known

### Other information

Deleting either one of these three lines (commented with in code `deleting this line will make the error go away`) will make the problem go away:

- in `Service.cs`:

  ```csharp
  private readonly NestedDictionary<NodeIdentifier, EventDefinitionIdentifier, EventDefinitionBase> dict = new();
  ```
- in `Worker.cs`

  ```csharp
  this.logger.LogInformation("Service {service} acquired", this.service);
  ```
- in `Types.cs`:

  ```chsarp
  public record EventSettings : EventSettingsBase;
  ``` 

See also https://github.com/bitbonk/ReadyToRunRepro/pull/2/files which contains step 3 and 4 of the reproduction steps.
You can just switch to branch `net8` and run `buildandrun.ps1` to see the error.

**Comment by TahirAhmadov** [comment]
I have a slightly different but I'm pretty sure related problem. In my case I'm getting `System.Security.VerificationException: Method ...: type argument '...' violates the constraint of type parameter '...'.`
I've been trying to create a re-pro (not to post the real project) but I'm unable to get a (non)working reproduction yet. Will post again if I succeed.

**Comment by TahirAhmadov** [comment]
Weird. I created a repro (still trimming it down to post here) and now I get the `violates` exception regardless of ReadyToRun, but not in debug mode.

**Comment by TahirAhmadov** [comment]
OK repro is below. Running in debug, or in release without r2r, or making either one of the changes per the comments below gets rid of the exception. Same behavior on Win Server 2019 and Windows 10; doesn't seem to be OS related. 

![image](https://github.com/dotnet/runtime/assets/16783987/de84dd3c-b3f4-4fd6-b723-d990960b7e78)

Please let me know if there is anything else I can provide.

```cs
using System.Collections.Generic;
using System.Threading.Tasks;

interface IListControl { }

interface IEntityChildControl
{
	Control Child { get; }
}
interface IEntityChildControl<out TChildControl> : IEntityChildControl
{
	new TChildControl Child { get; }
}
abstract class EntityControlBase<T, TChildControl> : ValueControlBase<T>, IEntityChildControl<TChildControl>
		where TChildControl : Control, new()
{
	public virtual Task BindAsync() => this.BindDataAsync();
	protected abstract Task BindDataAsync();
	public virtual TChildControl Child { get; set; } = new();
	Control IEntityChildControl.Child => this.Child;
}
interface IEntityListControl<out TControl> : IEntityChildControl<TControl> where TControl : IListControl { }
abstract class EntityListControlBase<TValue, TControl> : EntityControlBase<TValue, TControl>, IEntityListControl<TControl>
		where TControl : ValueControlBase<string>, IListControl, new()
{
}
abstract class EntityMultiValueListControlBase<T, C> : EntityListControlBase<IEnumerable<T>, C>
		where C : ValueControlBase<string>, IListControl, new()
{
}
// removing the presumably irrelevant TId generic parameter fixes the problem
class EntityClassMultiValueListControl<TId, TEntity, TControl> : EntityMultiValueListControlBase<TEntity, TControl>
	where TEntity : class, new()
	where TControl : ValueControlBase<string>, IListControl, new()
{
	protected override async Task BindDataAsync()
	{
		this.EntityClassListControlCommon.BindToChild([]); // commenting this line fixes the problem
	}
	public EntityClassListControlCommon<TEntity, EntityClassMultiValueListControl<TId, TEntity, TControl>> EntityClassListControlCommon;
}
class ContractParty { }
class Control { }
abstract class ValueControlBase<T> : Control { }
abstract partial class ComplexListControlBase : ValueControlBase<string>, IListControl { }
class DropDownCheckBoxList : ComplexListControlBase, IListControl { }
class ContractPartyDDCBL : EntityClassMultiValueListControl<int, ContractParty, DropDownCheckBoxList>
{
}

struct EntityClassListControlCommon<TEntity, TThis>
	where TEntity : notnull
	where TThis : IEntityChildControl<IListControl>
{
	public void BindToChild(IEnumerable<TEntity> list) { }
}

internal class Program
{
	static async Task Main(string[] args)
	{
		await new ContractPartyDDCBL().BindAsync();
	}
}
```

**Comment by TahirAhmadov** [comment]
Another potentially relevant problem has shown up:

```
System.BadImageFormatException: Bad IL format. The format of the file 'C:\......\Microsoft.Data.SqlClient.SNI.dll' is invalid.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFile(String path)
```

This only happens when publishing in .NET 8 with R2R.

**Comment by TahirAhmadov** [comment]
Will this ever be addressed or at least acknowledged by anybody? This issue was first reported more than 5 months ago and it seriously inhibits one of the main use cases - publishing R2R web and win services.

**Comment by janvorli** [comment]
@davidwrighton can you please take a look?

**Comment by steveisok** [comment]
@ivdiazsa please triage and see if you can reproduce.

**Comment by ivdiazsa** [comment]
Apparently, this was fixed at some point between .NET 8 and now. When I run it on .NET 7 it all goes fine, on .NET 8 it fails with the exception error described at the beginning of this issue post, and on .NET 9 preview-5 it runs well again.

**Comment by ivdiazsa** [comment]
Apparently, this was fixed at some point between .NET 8 and now. I ran the repro provided in the first post of this issue on multiple frameworks, and I got the following results:

- .NET 6: Runs well
- .NET 7: Runs well
- .NET 8: The System.TypeLoadException happens
- .NET 9 Preview 5: Runs well

For additional context, I got the same results on Windows and on Linux.

**Comment by TahirAhmadov** [comment]
@ivdiazsa can you confirm that the `VerificationException` in my repro is fixed in .NET 9 preview, too?

**Comment by ivdiazsa** [comment]
@TahirAhmadov The issue you sent doesn't repro on .NET 9 Preview 5 either.

**Comment by ivdiazsa** [comment]
@TahirAhmadov @bitbonk Hi all, would you need the fix to this issue backported to .NET 8?

**Comment by bitbonk** [comment]
> @TahirAhmadov @bitbonk Hi all, would you need the fix to this issue backported to .NET 8?

We only use LTS releases, so we are "stuck" with .NET 8 for a while.
We would greatly appreciate a backport to .NET 8.

**Comment by ivdiazsa** [comment]
@bitbonk @TahirAhmadov The backport of the fix for this issue will be released in .NET 8.0.9.

**Comment by TahirAhmadov** [comment]
@ivdiazsa I'll be sure to try it when that version is out. 
Thank you very much!
