### ISSUE TITLE
Test failure System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#96303]
**Failed in:** [runtime-coreclr crossgen2 20231223.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508163&view=ms.vss-test-web.build-test-results-tab&runId=11863174&resultId=180082&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-TestReadyToRun_Release-Windows.11.Amd64.Client.Open
    - System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest
net9.0-windows-Release-x64-TestReadyToRun_Release-Windows.Amd64.Server2022.Open
    - System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest
```

**Error message:**
```
Assert.Throws() Failure: No exception was thrown
Expected: typeof(System.TimeZoneNotFoundException)
```

**Stack trace:**
```
   at System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest() in /_/src/libraries/System.Runtime/tests/System.Runtime.Tests/System/TimeZoneInfoTests.cs:line 2939
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by jkotas** [comment]
Fixed by #96279
