### ISSUE TITLE
Test failure System.Globalization.Tests.IcuTests.IcuShouldBeLoaded

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#96301]
**Failed in:** [runtime-coreclr crossgen2 20231223.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508163&view=ms.vss-test-web.build-test-results-tab&runId=11863172&resultId=126023&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-TestReadyToRun_Release-Windows.Amd64.Server2022.Open
    - System.Globalization.Tests.IcuTests.IcuShouldBeLoaded
net9.0-windows-Release-x64-TestReadyToRun_Release-Windows.11.Amd64.Client.Open
    - System.Globalization.Tests.IcuTests.IcuShouldBeLoaded
```

**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False
```

**Stack trace:**
```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by jkotas** [comment]
This should be fixed by #96288
