### ISSUE TITLE
JsonSourceGenerator InvalidOperationException Unreachable with C# 12 using  alias

### ISSUE THREAD

**Issue by universorum** [dotnet/runtime#96313]
### Description

JsonSourceGenerator will make warning when compile if I using the C# 12 Using Alias.
Not all Using Alias will make warning. Only specify class with any alias will make warning.

### Reproduction Steps

I notice that if I add the using alias, the` JsonSourceGenerator` will throw and make the warning `CS8785 ` in compile and it say the generator throw `InvalidOperationException` with message `Unreachable`

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

</Project>
```
```
namespace GenLab;

public class MyAttribute : Attribute
{
}
```

```
using Point = (int x, int y);

namespace GenLab;

public class Class1
{
    [My]
    private readonly object? _obj;
}
```

The attribute is required to reproduce the problem.

### Expected behavior

Compile without warning

### Actual behavior

```
System.InvalidOperationException: Unreachable
at Microsoft.CodeAnalysis.DotnetRuntime.Extensions.RoslynExtensions.GetUnqualifiedName(NameSyntax name)
at Microsoft.CodeAnalysis.DotnetRuntime.Extensions.CSharpSyntaxHelper.AddAliases(SyntaxList`1 usings, ValueListBuilder`1& aliases, Boolean global)
at Microsoft.CodeAnalysis.DotnetRuntime.Extensions.CSharpSyntaxHelper.AddAliases(SyntaxNode node, ValueListBuilder`1& aliases, Boolean global)
at Microsoft.CodeAnalysis.DotnetRuntime.Extensions.SyntaxValueProviderExtensions.GetMatchingNodes(ISyntaxHelper syntaxHelper, GlobalAliases globalAliases, SyntaxTree syntaxTree, String name, Func`3 predicate, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.DotnetRuntime.Extensions.SyntaxValueProviderExtensions.<>c__DisplayClass5_0.<ForAttributeWithSimpleName>b__5(ValueTuple`2 tuple, CancellationToken c)
at Microsoft.CodeAnalysis.UserFunctionExtensions.<>c__DisplayClass0_0`2.<WrapUserFunction>b__0(TInput input, CancellationToken token)
```

Using alias work fine in other class in same project.

### Known Workarounds

Change TargetFramework to net8.0 will not throw the warning.

### Configuration

SDK: 8.0.100 on Windows 11
Target Framework: net6.0
C# Language version: default

**Comment by eiriktsarpalis** [comment]
Does it reproduce in .NET 8 as well?

**Comment by eiriktsarpalis** [comment]
Targeting `net6.0` will result in the source generator from .NET 6 being used, even if you have the newer .NET 8 sdk installed. My recommendation is to either update or remove the offending alias that is causing the issue.

Closing as fixed.

**Comment by MichalPetryka** [comment]
> to either update

Worth noting that using newer C# versions on older runtimes is not officially supported.
