### ISSUE TITLE
Can not create folder when path exists

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#96353]
### Description

When I try to create a folder in Linux get an exception like below:

```
System.IO.IOException: The file '/home/runner/.dotnet/tools/dotnet-exec' already exists.
2023-12-29T09:54:16.5271941Z     at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
2023-12-29T09:54:16.5273299Z     at System.IO.Directory.CreateDirectory(String path)
```

### Reproduction Steps

```c#
dotnet tool install -g dotnet-execute

dotnet-exec 'Directory.CreateDirectory(Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
        ".dotnet",
        "tools",
        "dotnet-exec"
    ))'
```

### Expected behavior

Directory should be created 

### Actual behavior

Exception

### Configuration

.NET 8
Linux crash only

**Comment by WeihanLi** [comment]
seemed Linux constraints, closing
