### ISSUE TITLE
Add implementations for SigntureHelper.AddSentinel() and/or other methods in mono runtime

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#96389]
A [test](https://github.com/dotnet/runtime/blob/0ba232e70e824474baa10e29350bd5c5552a3f85/src/libraries/System.Reflection.Emit/tests/PersistableAssemblyBuilder/AssemblySaveILGeneratorTests.cs#L1779) added for `ILGeneratorImpl.Emit(OpCode opcode, SignatureHelper signature)` failed with 
```log
System.NotImplementedException : The method or operation is not implemented.
      Stack Trace:
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/Emit/SignatureHelper.cs(277,0): at System.Reflection.Emit.SignatureHelper.AddSentinel()
        /_/src/libraries/System.Reflection.Emit/tests/PersistableAssemblyBuilder/AssemblySaveILGeneratorTests.cs(1847,0): at System.Reflection.Emit.Tests.AssemblySaveILGeneratorTests.Emit_CallBySignature()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```
The same would happen for VarArg methods. Looks there is several other public APIs not implemented, it would be great to add implementations for all

We might be able to move the runtime implementation into share libraries instead of trying to add implementation for mono implementation.

**Comment by buyaa-n** [comment]
Mono runtime also doesn't support standalone signature: 
```log
 System.NotImplementedException : The method or operation is not implemented.

  Stack Trace: 
SignatureHelper.GetSignature() line 381
ModuleBuilderImpl.GetSignatureMetadataToken(SignatureHelper signature) line 1040
AssemblySaveModuleBuilderTests.GetABCMetadataToken_Validations() line 283
```

**Comment by steveharter** [comment]
cc @BrzVlad
