### ISSUE TITLE
System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async_HttpMessageInvoker Test failure

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#96407]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=511843
Build error leg or test failing: System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async_HttpMessageInvoker.RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded
Pull request: https://github.com/dotnet/runtime/pull/96362

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Not found:  \"System.Net.Http.HttpRequestException\"",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```
From [Log](https://helix.dot.net/api/2019-06-17/jobs/cb09e6e6-3e2a-4b6a-aa7a-0b7418de5a43/workitems/System.Net.Http.Functional.Tests/console):
```log
System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async_HttpMessageInvoker.RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded [FAIL]
      Assert.Contains() Failure: Item not found in collection
      Collection: ["System.Threading.Tasks.TaskCanceledException", "response_ended"]
      Not found:  "System.Net.Http.HttpRequestException"
      Stack Trace:
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs(103,0): at System.Net.Http.Functional.Tests.HttpMetricsTestBase.VerifyRequestDuration(String instrumentName, Double measurement, KeyValuePair`2[] tags, Uri uri, Version protocolVersion, Nullable`1 statusCode, String method, String[] acceptedErrorTypes)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs(79,0): at System.Net.Http.Functional.Tests.HttpMetricsTestBase.VerifyRequestDuration(Measurement`1 measurement, Uri uri, Version protocolVersion, Nullable`1 statusCode, String method, String[] acceptedErrorTypes)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs(862,0): at System.Net.Http.Functional.Tests.HttpMetricsTest_Http11.<>c__DisplayClass5_0.<<RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs(44,0): at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass6_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(107,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs(846,0): at System.Net.Http.Functional.Tests.HttpMetricsTest_Http11.RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded()
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=511843
**Error message validated:** `Not found:  "System.Net.Http.HttpRequestException"`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 1/2/2024 7:25:41 PM UTC

**Comment by ManickaP** [comment]
This looks like #93627.

**Comment by ManickaP** [comment]
@antonfirsov should we close this as a dupe, or do you want to keep both open?

**Comment by antonfirsov** [comment]
I closed the old one, this one has more info in the issue description.

**Comment by AraHaan** [comment]
Does this have enough information to well, fix it?

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr crossgen2 20240528.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=690683&view=ms.vss-test-web.build-test-results-tab&runId=17153894&resultId=214702&paneView=debug)

**Failed tests:**
```
net9.0-osx-Release-x64-TestReadyToRun_Release-OSX.1200.Amd64.Open
    - System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async_HttpMessageInvoker.RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded
```

**Error message:**
```
 Assert.Contains() Failure: Item not found in collection
Collection: ["System.Threading.Tasks.TaskCanceledException", "response_ended"]
Not found:  "System.Net.Http.HttpRequestException"
```

**Stack trace:**
```
   at System.Net.Http.Functional.Tests.HttpMetricsTestBase.VerifyRequestDuration(String instrumentName, Double measurement, KeyValuePair`2[] tags, Uri uri, Version protocolVersion, Nullable`1 statusCode, String method, String[] acceptedErrorTypes) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs:line 102
   at System.Net.Http.Functional.Tests.HttpMetricsTestBase.VerifyRequestDuration(Measurement`1 measurement, Uri uri, Version protocolVersion, Nullable`1 statusCode, String method, String[] acceptedErrorTypes) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs:line 79
   at System.Net.Http.Functional.Tests.HttpMetricsTest_Http11.<>c__DisplayClass5_0.<<RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded>b__0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs:line 861
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 120
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 90
   at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass6_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs:line 44
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 107
   at System.Net.Http.Functional.Tests.HttpMetricsTest_Http11.RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs:line 846
--- End of stack trace from previous location ---
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-02-02T23:01:22.324Z | runtime-nativeaot-outerloop | Release | osx.1200.arm64.open | arm64 | System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async_HttpMessageInvoker.RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded | PassedOnRerun | {"configuration":"Release","architecture":"arm64","BuildId":"551534","DefinitionId":"265","Project":"public","System.JobAttempt":"1","System.PhaseName":"build_osx_arm64_Release_NativeAOT_Libs","AzurePipelinesTestRunId":"13119248","runtimeFlavor":"coreclr","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"OSX.1200.ARM64.Open","BuildNumber":"20240202.3","System.StageAttempt":"1","System.StageName":"Build","DefinitionName":"runtime-nativeaot-outerloop","System.PhaseAttempt":"1","Reason":"Schedule","System.JobName":"__default","System.JobId":"81f19b99-bbe6-5a12-eb99-6b7b5bb4d46c"} | Schedule
2024-02-02T21:33:28.326Z | runtime-extra-platforms | Release | ubuntu.2204.amd64.open.rt | x64 | System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async_HttpMessageInvoker.RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded | PassedOnRerun | {"configuration":"Release","architecture":"x64","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.JobAttempt":"1","DefinitionName":"runtime-extra-platforms","runtimeFlavor":"coreclr","System.StageName":"Build","AzurePipelinesTestRunId":"13116602","System.PhaseName":"libraries_test_run_release_coreclr_linux_x64_Release","BuildNumber":"20240202.3","DefinitionId":"154","operatingSystem":"(openSUSE.15.2.Amd64.Open)Ubuntu.2204.Amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:opensuse-15.2-helix-amd64","BuildId":"551535","Reason":"Schedule","Project":"public","System.JobName":"__default","System.JobId":"52ad279b-b059-569b-870a-4d7b21a81589"} | Schedule

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr crossgen2 20240602.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695417&view=ms.vss-test-web.build-test-results-tab&runId=17282464&resultId=204164&paneView=debug)

**Failed tests:**
```
net9.0-osx-Release-x64-TestReadyToRun_Release-OSX.1200.Amd64.Open
    - System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async_HttpMessageInvoker.RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded
```

**Error message:**
```
 Assert.Contains() Failure: Item not found in collection
Collection: ["System.Threading.Tasks.TaskCanceledException", "response_ended"]
Not found:  "System.Net.Http.HttpRequestException"
```

**Stack trace:**
```
   at System.Net.Http.Functional.Tests.HttpMetricsTestBase.VerifyRequestDuration(String instrumentName, Double measurement, KeyValuePair`2[] tags, Uri uri, Version protocolVersion, Nullable`1 statusCode, String method, String[] acceptedErrorTypes) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs:line 102
   at System.Net.Http.Functional.Tests.HttpMetricsTestBase.VerifyRequestDuration(Measurement`1 measurement, Uri uri, Version protocolVersion, Nullable`1 statusCode, String method, String[] acceptedErrorTypes) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs:line 79
   at System.Net.Http.Functional.Tests.HttpMetricsTest_Http11.<>c__DisplayClass5_0.<<RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded>b__0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs:line 861
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 120
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 90
   at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass6_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs:line 44
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 107
   at System.Net.Http.Functional.Tests.HttpMetricsTest_Http11.RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs:line 846
--- End of stack trace from previous location ---
```

**Comment by AraHaan** [comment]
What is needed is a sort of xfail system for this so if it does fail it does not fail the entire test legs of the CI (sort of a try the test and if it fails it is as if it was skipped).

**Comment by ManickaP** [comment]
@rokonec why did you close this? If it's fixed by any PR, please link it here, same for duplicates.

**Comment by rokonec** [comment]
@ManickaP Sorry,  my bad. It was closed by mistake, I have added it to my personal project, and moved it to Done by mistake, I missed the fact that moving it from Done to InProgress do not reopen issues.

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0
