### ISSUE TITLE
JsonSerializer constructor serialization does not ignore readonly properties

### ISSUE THREAD

**Issue by Helco** [dotnet/runtime#96408]
### Description

When the following code is run an exception is thrown as the readonly property is not ignored despite the corresponding property in JsonSerializerOptions being set.

### Reproduction Steps

```csharp
using System;
using System.Text.Json;
public record A(string name)
{
  public string Name => name;
}		
public class Program
{
	public static void Main()
	{
		var obj = new A("Hello");
		Console.WriteLine(JsonSerializer.Serialize(obj, new JsonSerializerOptions()
	        {
		        IgnoreReadOnlyProperties = true
	        }));
	}
}
```

### Expected behavior

The program should output the correct json, e.g. `{"name":"Hello"}`

### Actual behavior

An exception is thrown:
```
Unhandled exception. System.InvalidOperationException: Members 'name' and 'Name' on type 'A' cannot both bind with parameter 'name' in the deserialization constructor.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_MultiplePropertiesBindToConstructorParameters(Type parentType, String parameterName, String firstMatchName, String secondMatchName)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureConstructorParameters()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type type, Boolean fallBackToNearestAncestorType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Program.Main()
```

### Configuration

.NET 8, Windows 10 x64
Most likely not specific to this configuration.

**Comment by eiriktsarpalis** [comment]
The issue is unrelated to `IgnoreReadOnlyProperties`, since the same error happens even with that setting turned off. The real underlying issue is that `A` is a positional record type, meaning that `name` is both a constructor parameter _and_ a public field. This creates a conflict when trying to associate a property with the `name` constructor parameter (binding is case insensitive, so the logic detects a conflict in having two public properties called `name` and `Name`). 

There are a few workarounds you could follow, either fix the naming violation in the constructor parameter like so:
```C#
public record A(string Name)
{
}	
```
or change your type to be a regular class
```C#
public class A(string name)
{
    public string Name => name;
}
```

Hope this helps.
