### ISSUE TITLE
Using System.IO from Linux to write to an existing file on a Windows fileshare fails with 'Operation not supported'

### ISSUE THREAD

**Issue by ihasson** [dotnet/runtime#96503]
### Description

The easiest setup, I know of, to reproduce this is from a virtual machine running Ubuntu Desktop 22.04 LTS. Connect to a windows file share using the file manager, browse to a folder and use right-click 'Open in Terminal' to get the path. Also make sure powershell is installed. Then run from powershell:
```
$mySharePath = '/run/user/1000/gvfs/smb-share:server=servername,share=sharename/redacted/redacted/redacted/'
Add-Content -Path ($mySharePath + "fileName.txt") "one"
Add-Content -Path ($mySharePath + "fileName.txt") "two"
```
The first call to Add-Content will succeed so long as no file with that name exists. The second call to Add-Content will fail with the following message:

`Add-Content: Operation not supported : '/run/user/1000/gvfs/smb-share:server=redacted,share=netshare/redacted/redacted/redacted/fileName.txt'
`
and checking the stack trace from that error will show:
```
System.Management.Automation.MethodInvocationException: Exception calling "OpenWrite" with "1" argument(s): "Operation not supported : '/run/user/1000/gvfs/smb-share:server=servername,share=sharename/redacted/redacted/redacted/fileName.txt'"
 ---> System.IO.IOException: Operation not supported : '/run/user/1000/gvfs/smb-share:server=redacted,share=netshare/redacted/redacted/PS_Service/new.txt'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at CallSite.Target(Closure, CallSite, Type, Object)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
   at CallSite.Target(Closure, CallSite, Type, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

Doing something similar with `[System.IO.File]::WriteAllText(($mySharePath + "fileName.txt") ,"message text")` in PowerShell or `File.WriteAllText(filename, "C# line 2");` using dotnet core 8 and C# gives the same results with similar stack traces.

What makes this strange is that I can still create files and read them. Just not open existing files with a mode that allows writing. I'm also able to modify those files using Bash.

### Configuration

```
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Ubuntu 22.04.3 LTS
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by wfurt** [comment]
Did you really mean to open the file with all the special characters @ihasson ?  I'm wondering if `gvfs` supports locking? As if the file is locked e.g. cannot be opened for concurrent write?

**Comment by ihasson** [comment]
@wfurt I'm not sure what you mean by "open the file with all the special characters." I'm not familiar enough with `gvfs` to rule out anything but I can still append to files on that share with bash. As an example the following from the same powershell session as before works just fine.
```
$filename = ($mySharePath + "fileName.txt")
bash -c "echo three >> $filename" 
```

**Comment by wfurt** [comment]
part of the name seems to be `:server=servername,share=`. and that does not look like typical name to me. It still may be find, just curious. For long time Windows had special handling of `:` but that may be hidden by the docker magic.

**Comment by adamsitnik** [comment]
@ihasson could you please try setting `DOTNET_SYSTEM_IO_DISABLEFILELOCKING` env var to `true`, try again and let us know if you still get the same error?

**Comment by ihasson** [comment]
I tried setting `DOTNET_SYSTEM_IO_DISABLEFILELOCKING` to `true` and I get the same error.
Just to make sure I tested correctly, the following implies that I applied the environment value correctly, right?
```
> Get-Item -Path Env:/DOTNET*

Name                           Value
----                           -----
DOTNET_SYSTEM_IO_DISABLEFILEL… True
```

**Comment by GHJebus** [comment]
I'm experiencing the same behavior with mono applications writing to files via a gvfs smb share.  After working with the application developer (https://sourceforge.net/p/keepass/bugs/2321/) we've realized the issue is with mono.  My setup is as follows:
1) SMB share on a server backed by ZFS
2) Mount SMB share from step 1 via gio on a Linux machine 
3) Attempt to perform file writes to the share mounted via gio in step 2
4) Mono throws System.IO exceptions

This does not happen when mounting the same share directly using mount -t cifs.  Even when the cifs mount is performed with the same uid/guid as the user performing the gio mount, who is also the owning user of the share.  The issue does not appear to be with permissions on the smb share, rather with how mono is interacting with a gvfs mount.

I'm attaching a small sample that reproduces the problem.  Download and unzip, modify the run.sh to fill in the share/user info, modify the gtp_creds file for the password to the share, and execute run.sh.  A direct copy with 'cp' succeeds, however calling File.Copy from the mono app fails:

`Unhandled Exception:
System.IO.IOException: Operation not supported
  at Interop.ThrowExceptionForIoErrno (Interop+ErrorInfo errorInfo, System.String path, System.Boolean isDirectory, System.Func`2[T,TResult] errorRewriter) [0x00017] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at Interop.CheckIo (System.Int64 result, System.String path, System.Boolean isDirectory, System.Func`2[T,TResult] errorRewriter) [0x0000d] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at Interop.CheckIo (System.Int32 result, System.String path, System.Boolean isDirectory, System.Func`2[T,TResult] errorRewriter) [0x00000] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at System.IO.FileSystem.CopyFile (System.String sourceFullPath, System.String destFullPath, System.Boolean overwrite) [0x00068] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x0006e] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at CopyFile.Program.Main (System.String[] args) [0x00010] in <4b076641c9294ecb80a7b04aced090da>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.IOException: Operation not supported
  at Interop.ThrowExceptionForIoErrno (Interop+ErrorInfo errorInfo, System.String path, System.Boolean isDirectory, System.Func`2[T,TResult] errorRewriter) [0x00017] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at Interop.CheckIo (System.Int64 result, System.String path, System.Boolean isDirectory, System.Func`2[T,TResult] errorRewriter) [0x0000d] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at Interop.CheckIo (System.Int32 result, System.String path, System.Boolean isDirectory, System.Func`2[T,TResult] errorRewriter) [0x00000] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at System.IO.FileSystem.CopyFile (System.String sourceFullPath, System.String destFullPath, System.Boolean overwrite) [0x00068] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x0006e] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at CopyFile.Program.Main (System.String[] args) [0x00010] in <4b076641c9294ecb80a7b04aced090da>:0 
... returned exit code 1.
`
[monotest.zip](https://github.com/dotnet/runtime/files/15257327/monotest.zip)
