### ISSUE TITLE
System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.ManagedDelay test failure

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#96585]
```
[19:06:42] info: [2024-01-06T19:06:42.030Z] [FAIL] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.ManagedDelay_ConfigureAwait_True(executor: NewThread)
[19:06:42] info: System.AggregateException : One or more errors occurred. (Assert.NotEqual() Failure: Values are equal
[19:06:42] info: Expected: Not 302
[19:06:42] info: Actual:       302)
[19:06:42] info: ---- Assert.NotEqual() Failure: Values are equal
[19:06:42] info: Expected: Not 302
[19:06:42] info: Actual:       302
[19:06:42] info:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
[19:06:42] info:    at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
[19:06:42] info:    at System.Threading.Tasks.Task.Wait()
[19:06:42] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTestHelper.<>c__DisplayClass11_0.<RunOnNewThread>b__0()
[19:06:42] info: --- End of stack trace from previous location ---
[19:06:42] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.ManagedDelay_ConfigureAwait_True(Executor executor)
[19:06:42] info: --- End of stack trace from previous location ---
[19:06:42] info: ----- Inner Stack Trace -----
[19:06:42] info:    at System.Runtime.InteropServices.JavaScript.Tests.Executor.AssertAwaitCapturedContext()
[19:06:42] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.<>c__DisplayClass10_0.<<ManagedDelay_ConfigureAwait_True>b__0>d.MoveNext()
[19:06:42] info: [0x5110310-worker] MONO_WASM [0x5110310-worker]: forceDisposeProxies done: 0 imports, 0 exports, 0 GCHandles, 0 JSHandles.
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=517017
Build error leg or test failing: System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.ManagedDelay_ConfigureAwait_True
Pull request: https://github.com/dotnet/runtime/pull/96583

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Expected: Not 302",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=517017
**Error message validated:** `Expected: Not 302`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/6/2024 11:30:05 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jeffschwMSFT** [comment]
was not seen recently... dropping blocking-clean-ci

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0
