### ISSUE TITLE
[6.0] Test failure in System.Text.Json.Tests.Utf8JsonWriterTests.Writing3MBBase64Bytes(formatted: True, skipValidation: False)

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#96879]
### Error Blob

```json
{
  "ErrorMessage": "KioqKioqKioq",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

- PR: https://github.com/dotnet/runtime/pull/96783
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=522551
- Queue: `Libraries Test Run release mono OSX x64 Debug`
- Run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=522551&view=logs&j=c6f8dc49-92a1-5760-c098-ba97b8142bfb&t=22b0078b-0469-5ba6-8725-2121fdbae049
- Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-96783-merge-bb9e2883e11a45e8ad/System.Text.Json.Tests/1/console.13232992.log?helixlogtype=result
- Output:
```
===========================================================================================================
/private/tmp/helix/working/B6440A0C/w/B37609D6/e /private/tmp/helix/working/B6440A0C/w/B37609D6/e
  Discovering: System.Text.Json.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Json.Tests (found 2807 of 2855 test cases)
  Starting:    System.Text.Json.Tests (parallel test collections = on, max threads = 12)
    System.Text.Json.Tests.Utf8JsonWriterTests.Writing3MBBase64Bytes(formatted: True, skipValidation: False) [FAIL]
      Assert.Equal() Failure
                                       ↓ (pos 1371297)
      Expected: ···KioqKioqKioqKioqKioqkioqKioqKioqKioqKioqKioqKioqKioqKioqKioqK···
      Actual:   ···KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqK···
                                       ↑ (pos 1371297)
      Stack Trace:
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/JsonTestHelper.cs(738,0): at System.Text.Json.JsonTestHelper.AssertContentsAgainstJsonNet(String expectedValue, String value, Boolean skipSpecialRules)
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/JsonTestHelper.cs(714,0): at System.Text.Json.JsonTestHelper.AssertContents(String expectedValue, ArrayBufferWriter`1 buffer, Boolean skipSpecialRules)
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Utf8JsonWriterTests.cs(3175,0): at System.Text.Json.Tests.Utf8JsonWriterTests.Writing3MBBase64Bytes(Boolean formatted, Boolean skipValidation)
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(370,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  Finished:    System.Text.Json.Tests
=== TEST EXECUTION SUMMARY ===
   System.Text.Json.Tests  Total: 19695, Errors: 0, Failed: 1, Skipped: 0, Time: 83.984s
/private/tmp/helix/working/B6440A0C/w/B37609D6/e
----- end Wed Jan 10 19:26:02 EST 2024 ----- exit code 1 ----------------------------------------------------------
```

**Comment by eiriktsarpalis** [comment]
Here's the test in question:

**Comment by jeffschwMSFT** [comment]
was not seen recently... dropping blocking-clean-ci

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0
