### ISSUE TITLE
System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime failing

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#97020]
```
    System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime [FAIL]
      Expected: 1/15/2024 9:28:17 AM to be greater than 1/15/2024 9:28:17 AM
      Stack Trace:
        /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs(335,0): at System.AssertExtensions.GreaterThan[T](T actual, T greaterThan, String userMessage)
        /_/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/GetSetTimes_SafeFileHandle.cs(115,0): at System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime()
        --- End of stack trace from previous location ---
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=527171
Build error leg or test failing: System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime
Pull request: https://github.com/dotnet/runtime/pull/96894

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "to be greater than",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by Jozkee** [comment]
Looks similar to https://github.com/dotnet/runtime/issues/95378 and https://github.com/dotnet/runtime/issues/95298.
Will mark as future since it has very few failing runs. It may still be related to FAT resolution.

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci label as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr crossgen2 20240703.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=730403&view=ms.vss-test-web.build-test-results-tab&runId=18372238&resultId=141532&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-TestReadyToRun_Release-Windows.81.Amd64.Open
    - System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime
    - System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime
```

**Error message:**
```
 Expected: 7/4/2024 8:25:25 AM to be greater than 7/4/2024 8:25:25 AM
```

**Stack trace:**
```
   at System.AssertExtensions.GreaterThan[T](T actual, T greaterThan, String userMessage) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 335
   at System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime() in /_/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/GetSetTimes_SafeFileHandle.cs:line 115
--- End of stack trace from previous location ---
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr crossgen2 20240904.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=798329&view=ms.vss-test-web.build-test-results-tab&runId=20574546&resultId=142305&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-TestReadyToRun_Release-Windows.81.Amd64.Open
    - System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime
```

**Error message:**
```
 Expected: 9/5/2024 8:17:47 AM to be greater than 9/5/2024 8:17:47 AM
```

**Stack trace:**
```
   at System.AssertExtensions.GreaterThan[T](T actual, T greaterThan, String userMessage) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 335
   at System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime() in /_/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/GetSetTimes_SafeFileHandle.cs:line 115
--- End of stack trace from previous location ---
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr crossgen2 20241006.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=828933&view=ms.vss-test-web.build-test-results-tab&runId=21562404&resultId=139438&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x64-TestReadyToRun_Release-Windows.81.Amd64.Open
    - System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime
```

**Error message:**
```
 Expected: 10/7/2024 8:04:06 AM to be greater than 10/7/2024 8:04:06 AM
```

**Stack trace:**
```
   at System.AssertExtensions.GreaterThan[T](T actual, T greaterThan, String userMessage) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 335
   at System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime() in /_/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/GetSetTimes_SafeFileHandle.cs:line 115
--- End of stack trace from previous location ---
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20241031.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=857256&view=ms.vss-test-web.build-test-results-tab&runId=22287528&resultId=171112&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x64-no_tiered_compilation-Windows.10.Amd64.Open
    - System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime
```

**Error message:**
```
 Expected: 10/31/2024 8:03:12 AM to be greater than 10/31/2024 8:03:12 AM
```

**Stack trace:**
```
   at System.AssertExtensions.GreaterThan[T](T actual, T greaterThan, String userMessage) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 335
   at System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime() in /_/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/GetSetTimes_SafeFileHandle.cs:line 115
--- End of stack trace from previous location ---
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20251105.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1195472)

**Failed tests:**
```
net10.0-windows-Release-x86-jitstress1_tiered-Windows.10.Amd64.Open
    - System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime
```

**Error message:**
```
Expected: 11/6/2025 8:12:19 AM to be greater than 11/6/2025 8:12:19 AM
```

**Stack trace:**
```
   at System.AssertExtensions.GreaterThan[T](T actual, T greaterThan, String userMessage) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 335
   at System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime() in /_/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/GetSetTimes_SafeFileHandle.cs:line 115
--- End of stack trace from previous location ---
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20251107.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1197780)

**Failed tests:**
```
net10.0-windows-Release-x86-tailcallstress-Windows.10.Amd64.Open
    - System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime
```

**Error message:**
```
Expected: 11/8/2025 8:11:14 AM to be greater than 11/8/2025 8:11:14 AM
```

**Stack trace:**
```
   at System.AssertExtensions.GreaterThan[T](T actual, T greaterThan, String userMessage) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 335
   at System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime() in /_/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/GetSetTimes_SafeFileHandle.cs:line 115
--- End of stack trace from previous location ---
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20251110.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1199593)

**Failed tests:**
```
net10.0-windows-Release-x86-jitstress1_tiered-Windows.10.Amd64.Open
    - System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime
```

**Error message:**
```
Expected: 11/11/2025 8:02:04 AM to be greater than 11/11/2025 8:02:04 AM
```

**Stack trace:**
```
   at System.AssertExtensions.GreaterThan[T](T actual, T greaterThan, String userMessage) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 335
   at System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime() in /_/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/GetSetTimes_SafeFileHandle.cs:line 115
--- End of stack trace from previous location ---
```

**Comment by VincentBu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20260519.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1426096)

**Failed tests:**
```
net11.0-windows-Release-x86-tailcallstress-Windows.10.Amd64.Open
- System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime

```

**Error message:**
```
Expected: 5/19/2026 8:56:50 AM to be greater than 5/19/2026 8:56:50 AM
```

**Stack trace:**
```
   at System.AssertExtensions.GreaterThan[T](T actual, T greaterThan, String userMessage) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 335
   at System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime() in /_/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/GetSetTimes_SafeFileHandle.cs:line 115
--- End of stack trace from previous location ---
```

**Comment by VincentBu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstressregs 20260531.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1442451)

**Failed tests:**
```
net11.0-windows-Release-x86-jitstressregs2-Windows.10.Amd64.Open
- System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime

```

**Error message:**
```
Expected: 5/31/2026 10:43:32 AM to be greater than 5/31/2026 10:43:32 AM
```

**Stack trace:**
```
   at System.AssertExtensions.GreaterThan[T](T actual, T greaterThan, String userMessage) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 335
   at System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime() in /_/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/GetSetTimes_SafeFileHandle.cs:line 115
--- End of stack trace from previous location ---
```
