### ISSUE TITLE
[browser][MT] System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_CancellationRequestedInflightConnect_ThrowsOperationCanceledException

### ISSUE THREAD

**Issue by maraf** [dotnet/runtime#97092]
### Error Blob

```json
{
  "ErrorMessage": "[FAIL] System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_CancellationRequestedInflightConnect_ThrowsOperationCanceledException",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

**Comment by maraf** [comment]
```
[11:02:01] info: [2024-01-17T11:02:01.371Z] [FAIL] System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_CancellationRequestedInflightConnect_ThrowsOperationCanceledException
[11:02:01] info: Assert.ThrowsAny() Failure: Exception type was not compatible
[11:02:01] info: Expected: typeof(System.OperationCanceledException)
[11:02:01] info: Actual:   typeof(System.Net.WebSockets.WebSocketException)
[11:02:01] info: ---- System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
[11:02:01] info: -------- System.Runtime.InteropServices.JavaScript.JSException : Error: WebSocket error
[11:02:01] info:    at System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_CancellationRequestedInflightConnect_ThrowsOperationCanceledException()
[11:02:01] info: --- End of stack trace from previous location ---
[11:02:01] info: ----- Inner Stack Trace -----
[11:02:01] info:    at System.Net.WebSockets.BrowserWebSocket.CancellationHelper(Task promise, CancellationToken cancellationToken, WebSocketState previousState, IDisposable disposable)
[11:02:01] info:    at System.Net.WebSockets.BrowserWebSocket.ConnectAsyncCore(CancellationToken cancellationToken)
[11:02:01] info:    at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken)
[11:02:01] info: ----- Inner Stack Trace -----
[11:02:01] info:    at System.Net.WebSockets.BrowserWebSocket.CancellationHelper(Task promise, CancellationToken cancellationToken, WebSocketState previousState, IDisposable disposable)
[11:02:01] info: ... omitted JavaScript stack trace from another thread.
```
