### ISSUE TITLE
Unexpected deletion of persisted private key on disposing X509Certificate2 object

### ISSUE THREAD

**Issue by decoyjoe** [dotnet/runtime#97121]
### Description

Install a certificate and its private key from a PFX file to the `LocalMachine` store with the `MachineKeySet | PersistKeySet` key storage flags. Close the process. The private key is persistently stored on disk under `C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\`.

Start a process as the local `NT AUTHORITY\SYSTEM` user and read the certificate PFX file again, creating an `X509Certificate2` object.

The bug manifests when the `.Dispose()` method is called on the `X509Certificate2` object. The private key container is unexpectedly deleted from disk, from the `C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\` directory, even though it was installed with the `PersistKeySet` flag.

Any subsequent attempts to access or read the private key, even in new processes, result in errors stating "Keyset does not exist." To resolve this issue, the certificate and its private key must be re-installed.

### Reproduction Steps

Run the following program as the local `NT AUTHORITY\SYSTEM` user. A base64 encoded certificate has been included for convenience.

```csharp
using System.IO;
using System.Runtime.InteropServices;
using System.Security.Principal;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;

namespace DotnetX509CertificateBug
{
    class Program
    {
        static void Main()
        {
            Console.WriteLine();
            Console.WriteLine("Reproducing dotnet/runtime #97121");
            Console.WriteLine();

            var currentUser = WindowsIdentity.GetCurrent().Name;

            if (!currentUser.Equals(@"NT AUTHORITY\SYSTEM", StringComparison.OrdinalIgnoreCase))
            {
                throw new Exception($"Only reproducible when running as the SYSTEM user but current user is {currentUser}. Please re-run as SYSTEM.");
            }

            Console.WriteLine($"Running as: {currentUser}");
            Console.WriteLine($"{RuntimeInformation.OSDescription}");
            Console.WriteLine($"{RuntimeInformation.FrameworkDescription}");
            Console.WriteLine();

            string pfxBase64 = """MIIGqgIBAzCCBmYGCSqGSIb3DQEHAaCCBlcEggZTMIIGTzCCA7gGCSqGSIb3DQEHAaCCA6kEggOlMIIDoTCCA50GCyqGSIb3DQEMCgECoIICtjCCArIwHAYKKoZIhvcNAQwBAzAOBAgotekLrVxDhAICB9AEggKQi2ieJS12oTrDVrRQ4fADCFLtPki6zWsmNdZLoaYqb6sH8qBGbRF1DC4aUkOEezKY0xYjR48q6bVDRtoXbK4Kb1fhCv9zmh4qwQSKliOQWwaF1G1UvyhT6WF22k8nD9My+DUjahyDihCrVjRd0jOEKeftAk0Sawt7roeJmUx2UhRO9lCOItXBwRvXe8kMPHVtI5mcECW6PlEJmu1OxaXjSUSCLCZLM9JVXy6JfZcMp1TwDYy2in/gIrOCjwPR/68gP4DepUSsIbLD+lNMzAj2+5iPWdC/Lu5Ho97p1fUxvMsDL3fY8Gjat9HXaGTD0CnPYTvcASdaAv/FAvpYyfg7JC/PYci91uDLglJt08TNpTg4xdVU1AK8S3I8sedomuHToSC6kibToN4u2p6YlMVQ/i6Sa3smUDuKurIGLNH08DoQnEQ+bsGx7gBMU19kDYnxpAGaD+hNJdukmyI4MdPd7nBbRjvcMaxk2wPL2GxlV6fu49uJKg3PWcJqCgjVp/UT+w+Sd1T1/1Q7y4KHTXtaB4ObBvGkc5RZ3K34Yy7bMz0It9AXGvpH2dR7XAaLxrhEDtc43y5FcKXz/PaejArH1kqcRhRMwiNSGqdAEfAH/FglA5dJFIt2+2qd7lw3IZYmRBKi0YQJELJUh8vF5Sq1x+z/eTnHC1pele33uLTTUeI5wWmn044MF2D9kSCJ8zFkd87NBrOwPNsM20bb+/UwF0Naaw2iZRb/P12pKYTxqhUs/VoIIwVIpvoJwnAS4fl2BmiUa+NHq3qmu8AgdizJsUH7ti1eUOUlDk8HJy3LjXart3BA0vzDHi23/FbhkO2BW5jfaH4ej8AuNKUB5Nce6UJBgSVAnL733Qgjb2Z5uTcxgdMwEwYJKoZIhvcNAQkVMQYEBAEAAAAwXQYJKoZIhvcNAQkUMVAeTgB0AHEALQBlADcAYQBmADcAZABkAGUALQAzADcAOQAxAC0ANAAyAGEAYwAtAGIANgA2AGUALQAyAGQAMwA0AGQANQAyAGUAMgAwADIAZDBdBgkrBgEEAYI3EQExUB5OAE0AaQBjAHIAbwBzAG8AZgB0ACAAUwB0AHIAbwBuAGcAIABDAHIAeQBwAHQAbwBnAHIAYQBwAGgAaQBjACAAUAByAG8AdgBpAGQAZQByMIICjwYJKoZIhvcNAQcGoIICgDCCAnwCAQAwggJ1BgkqhkiG9w0BBwEwHAYKKoZIhvcNAQwBAzAOBAjpqoUuxvwRSQICB9CAggJIAeC+H5ibBNoZGuKoREElkKtkUEajSzYsNDKq2pxbkp93Yzq+1PZECRdPOvc85G16SnvOwiYVFnzcC7IgPs3fV8NwarDq6qO28jUzwWhWQKjj9hhjoMFHXGg47wuVoBEj45EpmARWOQ4EQFjSAEDuima0YUOFVlyat+izMoVMiaEewKV75LZRgy4WAgPAhbMrAVbNOGIbBCIx5jrVKbqjLSoiL8B6hDniI98GqDsIqBvVAdLFxtBkD7+JPVQKDX0vkk21CXfXcaKW3NRAtoZvBvS2ggseGTvmpeNtcNrhDlDEkUSJxKKiibBSBHad06thoZ5xwMcZrQvL09ouKzzHu2ehk92pBXN8eAAqI1QYStZH2MW1wr1UEy+uesLAmgRFe1HHypautdEtA/xoIGPXyuEWpsb7Ge+aKzJWr/ISAoI5icxv07LEV7ws1WI6Y8dy/cxYUFcYB1404oxNmgKrInwui+yx97IUKgi/glhCb95URWgEyPwBJjnv7od0UCjTuK5hxk1t17EXO5zg+85r9Ja2tToBNoJMTC8OZ6ce/3QOFsme9pB/6pcajtD8nuqu0p6f24LjWDTHIv6kLMNkCIFODPSW7IIp3OvmDrxjdqu1cwEcq25d8cco/hQVUzUQeG5hIxgSKGdvDCl3xlE66TFG2JKfs/GOb7DLJxxbg7JtceMGCtv7crV8XD2/h9yx89ZbL9FV+2crUHwaPgSrZ/quXT3Kzhn+BgT95ri69UR0VcBiFxOEwqDj5EPvfH0cpEVUeEFGhbEwOzAfMAcGBSsOAwIaBBTXj1M7ucmPJfbOzVjXnnYejFDTbQQUI3AjQvLeMTKWqU9c4g89tVY4H7ACAgfQ""";
            string password = "password";

            var pfxBytes = Convert.FromBase64String(pfxBase64);
            var keyFlags = X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.PersistKeySet;
            var certToInstall = new X509Certificate2(pfxBytes, password, keyFlags);

            var thumbprint = certToInstall.Thumbprint;
            var privateKey = RSACertificateExtensions.GetRSAPrivateKey(certToInstall);
            var keyContainer = ((RSACng)privateKey).Key.UniqueName;

            Console.WriteLine($"Install certificate to LocalMachine/My store with X509KeyStorageFlags: {keyFlags}");
            Console.WriteLine($"  Subject: {certToInstall.Subject}");
            Console.WriteLine($"  Subject: {certToInstall.Thumbprint}");
            Console.WriteLine();

            var store = new X509Store(StoreName.My, StoreLocation.LocalMachine);
            store.Open(OpenFlags.ReadWrite);
            store.Add(certToInstall);
            store.Close();
            store.Dispose();
            certToInstall.Dispose();

            var privateKeyFilePath = $"C:\\ProgramData\\Microsoft\\Crypto\\RSA\\MachineKeys\\{keyContainer}";

            Console.WriteLine("Check certificate private key:");
            Console.WriteLine($"  Path: {privateKeyFilePath}");
            Console.WriteLine($"  Exists: {Path.Exists(privateKeyFilePath)}");
            Console.WriteLine();

            Console.WriteLine("Now read certificate again from PFX and then dispose it:");
            var certFromPfx = new X509Certificate2(pfxBytes, password);
            certFromPfx.Dispose();
            Console.WriteLine("  Done.");
            Console.WriteLine();

            Console.WriteLine("Check certificate private key again:");
            Console.WriteLine($"  Path: {privateKeyFilePath}");
            Console.WriteLine($"  Exists: {Path.Exists(privateKeyFilePath)}");
            Console.WriteLine();

            store = new X509Store(StoreName.My, StoreLocation.LocalMachine);
            store.Open(OpenFlags.ReadOnly);
            var installedCert = store.Certificates.Where(cert => cert.Thumbprint == thumbprint).First();
            Console.WriteLine("Try to get the private key with GetRSAPrivateKey():");
            Console.WriteLine(RSACertificateExtensions.GetRSAPrivateKey(installedCert));
        }
    }
}
```

For a fully automated reproduction in a fresh virtual machine, [see this repository here](https://github.com/decoyjoe/dotnet-x509-certificate-bug).

### Expected behavior

The private key container under `C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\` remains after disposing the certificate object.

### Actual behavior

The private key container no longer exists under `C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\`.

Here's the output from the reproduction program:

```
Reproducing dotnet/runtime #97121

Running as: NT AUTHORITY\SYSTEM
Microsoft Windows 10.0.22631
.NET 8.0.1

Install certificate to LocalMachine/My store with X509KeyStorageFlags: MachineKeySet, PersistKeySet
  Subject: CN="dotnet-runtime-#97121"
  Subject: C6CDE0BCFC3F49C319CDA872AC1602D9D5FE621B

Check certificate private key:
  Path: C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\3783dffe86057ae296d14ef8601e9142_eead0bb6-08ac-432d-82ec-f0b5657e3223
  Exists: True

Now read certificate again from PFX and then dispose it:
  Done.

Check certificate private key again:
  Path: C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\3783dffe86057ae296d14ef8601e9142_eead0bb6-08ac-432d-82ec-f0b5657e3223
  Exists: False

Try to get the private key with GetRSAPrivateKey():
Unhandled exception. System.Security.Cryptography.CryptographicException: Keyset does not exist
   at System.Security.Cryptography.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeProvHandle()
   at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeKeyHandle()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 keySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.CertificatePal.<>c.<GetRSAPrivateKey>b__68_0(CspParameters csp)
   at System.Security.Cryptography.X509Certificates.CertificatePal.GetPrivateKey[T](Func`2 createCsp, Func`2 createCng)
   at System.Security.Cryptography.X509Certificates.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
   at DotnetX509CertificateBug.Program.Main() in C:\build\dotnet-x509-certificate-bug\Program.cs:line 74
dotnet.exe exited on DESKTOP-KGNKFC0 with error code -532462766.
```

### Known Workarounds

Do not read installed certificates with private keys as the local `NT AUTHORITY\SYSTEM` user.

### Configuration

.NET 8.0.1
Microsoft Windows 10.0.22631

**Comment by bartonjs** [comment]
> Start a process as the local NT AUTHORITY\SYSTEM user and read the certificate PFX file again, creating an X509Certificate2 object.

> The bug manifests when the .Dispose() method is called on the X509Certificate2 object. The private key container is unexpectedly deleted from disk, from the C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\ directory, even though it was installed with the PersistKeySet flag.

This is a combination of misunderstanding how PFX works, and (seemingly) a bug in the Windows OS.

> even though it was installed with the PersistKeySet flag

PFXes don't get "installed".  They get "loaded", and when they get loaded a private key is in one of four states:

1. Doesn't exist.
2. Exists, but only in memory (true if loaded with EphemeralKeySet)
3. Exists, on disk, and .NET is tracking disk cleanup (true if neither EphemeralKeySet or PersistKeySet are specified)
4. Exists, on disk, and .NET Is not tracking disk cleanup (PersistKeySet).

When you load the PFX the second time, it _should_ be the case that a second copy of the key manifests on disk (since you didn't specify EphemeralKeySet).  Then, when you later dispose the certificate, that file (which should be a different file) gets erased (because you didn't specify PersistKeySet).

So here's where the thing that I think is a Windows bug is creeping in.  PFXes (can) contain an identifier saying what name the key had when it was exported.  When the PFX is imported, if that name is not already in use then Windows will use it.  We tell Windows that it's not allowed to overwrite a key, so it should have the behavior of "this key name is taken, I'll generate a new key name" (and since the file name is derived from the key name, that means it gets a different file name).  However, for LOCAL AUTHORITY\SYSTEM, the user keystore and the machine keystore are the same directory.  So Windows seems to be seeing "this key name isn't in use as a user key, so I can use that same name", then giving it the same file on disk; but when you then dispose the key it ends up deleting the user file which is also the machine file.  Basically, there's nothing we can do about this, because we don't own the keystore, Windows does.

I believe it will also be the case that once you've opened that PFX as LOCAL AUTHORITY\SYSTEM that any custom ACLs on the private key will be lost.  It might not actually be true, because it depends on whether Windows overwrites the file in an ACL-resetting way, but it's definitely a possibility.

For your later openings, I recommend any of
* Stripping the friendly name property off of the key in the PFX before loading it, so it always gets a GUID-based name on import (astronomically low chances of conflicting with an existing file).
* Do your initial import in a weird way:  Import it without PersistKeySet, then import it a second time WITH PersistKeySet, so the PersistKeySet-copy isn't using the preferred file name.  Later imports won't generate this name.
* Do your later imports with EphemeralKeySet and get rid of the whole key-erasing thing.
* Do your later imports with the MachineKeySet flag, and Windows might correctly realize the key is in use.
* Don't import PFXes as SYSTEM.

**Comment by decoyjoe** [comment]
Thanks for the insight and all the provided workarounds @bartonjs. Seems like the best workaround is:

> Do your initial import in a weird way: Import it without PersistKeySet, then import it a second time WITH PersistKeySet, so the PersistKeySet-copy isn't using the preferred file name. Later imports won't generate this name.

That workaround will import it in a way that avoids the issue entirely, no matter the manner in which later processes might load the PFX (e.g. as SYSTEM with UserKeySet).

Also, I have a question regarding this statement:

> However, for LOCAL AUTHORITY\SYSTEM, the user keystore and the machine keystore are the same directory.

Why is the machine keystore directory (`C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys`) used for the SYSTEM account's user keystore? I would have expected the SYSTEM account's user keystore to be under its profile directory (like other user's keystores), e.g. `C:\Windows\System32\config\systemprofile\AppData\Roaming\Microsoft\Crypto`. Or perhaps even `C:\ProgramData\Microsoft\Crypto\RSA\S-1-5-18` which I see already exists (but am unsure what it's used for).

Is the SYSTEM user keystore being the same location as the machine keystore related to the (presumable) Windows bug? Or by design based on how Windows works with keys and its keystores?

**Comment by bartonjs** [comment]
Huh, that's a good point, SYSTEM should be using `%ALLUSERSPROFILE%\Application Data\Microsoft\Crypto\SystemKeys` per https://learn.microsoft.com/en-us/windows/win32/seccng/key-storage-and-retrieval#key-directories-and-files.  I was just describing what seems to be going wrong by the symptoms.

That may be then that the PFX itself is marking the key as a machine store key; but it still would be a Windows bug that it's not correctly identifying the key as already in use.  .NET isn't involved in how Windows writes the files to disk (including when it fails to notice that the key name is in use).

**Comment by vladimir-bukreev** [comment]
@decoyjoe , have you reported this bug to Windows? Can you share the issue, please?

**Comment by decoyjoe** [comment]
I have not reported this bug to Windows. This issue was labeled with "tracking-external-issue" which I assumed to mean that @bartonjs reported it as an issue to Windows, but that may not be the case.

@bartonjs Was there a Windows bug report submitted for this? If not, what is the best avenue for me to do that?
