### ISSUE TITLE
SignedXml does not work by default in trimmed applications

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#97274]
If you use `SignedXml` within a trimmed application, the out-of-the-box experience is going to be a `CryptographicException`.

This is because `SignedXml` uses `CryptoConfig` to resolve hash algorithm identifiers (URIs) to an appropriate hash implementation. The trimmer cannot see through this, and even if it could, it could not handle scenarios where the algorithm is part of the document input. The trimmer ends up removing various pieces from `System.Security.Cryptography` that `SignedXml` actually needs. This includes types like `RSAPKCS1SignatureFormatter` and `RSAPKCS1SignatureDeformatter`, `SHA1Managed`, etc.

The error you get in this situation is very difficult to resolve.

> System.Security.Cryptography.CryptographicException: Could not create hash algorithm object. If the application has been trimmed, ensure the required algorithm implementations are preserved.

What hash algorithm? It actually needs to be the `*Managed` ones because that's what CryptoConfig resolves for legacy purposes. If you just add `S.S.C.SHA1` to your root list, it's not going to work. Without a detailed knowledge of how CryptoConfig and the runtime works, it's difficult to solve this problem on your own. How is someone supposed to know they need to add an obsolete class to their roots?

I am sure we can fix CryptoConfig to resolve things to better algorithms in some situations, or we can improve the error message. You fix one, then you move on to the next error about signature formatters. That presents as a null-ref.

One option is we add `DynamicDependencyAttribute` to `SignedXml` for common things that get end up getting resolved by `CryptoConfig`.

Something like:

```C#
partial class SignedXml {
    [DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.SHA1Managed", "System.Security.Cryptography.Algorithms")]
    [DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.SHA256Managed", "System.Security.Cryptography.Algorithms")]
    [DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography. RSAPKCS1SignatureFormatter", "System.Security.Cryptography.Algorithms")]
    [DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography. RSAPKCS1SignatureDeformatter", "System.Security.Cryptography.Algorithms")]
    // SHA-384 and SHA-512 too, I suppose.
    public SignedXml(XmlDocument doc);

    // Repeat for other constructors or methods
}
```

The knee-jerk reaction here might be to say "But this ends up rooting types that might not be used" which is correct. If you never use SHA-1, SHA-1 is rooted for no good reason. It's on the "small" side, we aren't rooting an actual implementation of SHA-1, just a public shim around an internal algorithm that dispatches by name.

This is a common issue with other cryptographic stacks. OIDs in various things like CMS have the same problem. We don't know the hash algorithm in a document until we try to process the document at runtime.

You could also say, "But if someone changes their CryptoConfig to use something else, we've rooted these things for nothing" which, yes, is also correct. But I believe this to be an uncommon scenario.

I also believe that if we were building S.S.C.Xml from scratch without CryptoConfig, it would look something like this:

```C#
HashAlgorithm alg = hasher switch {
    "http://www.w3.org/2000/09/xmldsig#sha1" => SHA1.Create(),
    "http://www.w3.org/2001/04/xmlenc#sha256" => SHA256.Create(),
    // etc
    _ => throw new CryptographicException(SR.IDontKnowWhatHashYouAreTalkingAbout),
};
```

Which leads us back to rooting hash algorithms.

-----

An alternative thing to do is to handle `null` better when we get back from CryptoConfig, like `GetSha1FromCryptoConfig() ?? SHA1.Create()` but this is going to end up rooting common algorithms anyway through the factory method. Likewise for the signature formatters.

A final alternative option is to not fix this - but instead (significantly) improve the error along with a link to documentation explaining which things they need to manually add to their roots.

**Comment by ceztko** [comment]
I use something similar to this [class](https://stackoverflow.com/a/50134529/213871) inheriting `SignedXML` and I put this in my Native AOT compiled code:

```csharp
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.SHA1Managed", "System.Security.Cryptography.Algorithms")]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.SHA256Managed", "System.Security.Cryptography.Algorithms")]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.SHA384Managed", "System.Security.Cryptography.Algorithms")]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.SHA512Managed", "System.Security.Cryptography.Algorithms")]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.RSAPKCS1SignatureFormatter", "System.Security.Cryptography.Algorithms")]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.RSAPKCS1SignatureDeformatter", "System.Security.Cryptography.Algorithms")]
    private XadesSignedXml(XmlDocument document)
#pragma warning disable IL2026 // Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code
#pragma warning disable IL3050 // Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.
        : base(document)
#pragma warning restore IL3050 // Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.
#pragma warning restore IL2026 // Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code
    {
        // ...
    }
```

This helped me solve `System.Security.Cryptography.CryptographicException` and reduces the warnings during compilation. If something like `DynamicDependencyAttribute` could be set as an assembly level attribute, instead of setting it per class member, it would be more meaningful to me. If you have suggestions how this issue could be solved differently in a Native AOT application/library please tell me.

**Comment by DanSmith** [comment]
On net core 8, the classes were in a different assembly than in great suggestions from @ceztko and @vcsjones 

DynamicDependency using this style with typeof should work wherever:
```csharp
[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.SHA1))]
...
...
```

**Comment by rokmeglic71** [comment]
According to [issue #102033](https://github.com/dotnet/runtime/issues/102033) I have tested with various versions of Cryptography. We are using RSA and AES. We are getting error:

```
System.Security.Cryptography.CryptographicException: Cryptography_Xml_MissingAlgorithm
   at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
```
We are using MAUI c# NET 9.0.

**Linker XML:**
```
<linker>
	<assembly fullname="System.Security.Cryptography.Xml">
		<type fullname="System.Security.Cryptography.Xml.EncryptedXml" preserve="all" />
		<type fullname="System.Security.Cryptography.Xml.EncryptedData" preserve="all" />
		<type fullname="System.Security.Cryptography.Xml.EncryptionMethod" preserve="all" />
		<type fullname="System.Security.Cryptography.Xml.KeyInfoName" preserve="all" />
		<type fullname="System.Security.Cryptography.Xml.CipherData" preserve="all" />
		<type fullname="System.Security.Cryptography.Xml.EncryptedKey" preserve="all" />
	</assembly>
	<assembly fullname="System.Security.Cryptography.Algorithms" preserve="all" />
</linker>
```
with <TrimmerRootDescriptor Include="trim.xml" />  does not work.
Trim.xml file is set to Build action: none

[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.Aes))]
```
        // Reference: https://github.com/dotnet/runtime/issues/97274#issuecomment-2197683458
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.Xml.EncryptedKey))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.Xml.CipherData))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.Xml.EncryptedXml))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.Xml.EncryptedData))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.Xml.EncryptionMethod))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.Xml.KeyInfoName))]

        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.Aes))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.AesCcm))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.AesCng))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.AesGcm))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.RSA))]
```

does not work.

**[DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.Xml", "System.Security.Cryptography.Xml.EncryptedKey")]**

        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.Xml", "System.Security.Cryptography.Xml.EncryptedKey")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.Xml", "System.Security.Cryptography.Xml.CipherData")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.Xml", "System.Security.Cryptography.Xml.EncryptedXml")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.Xml", "System.Security.Cryptography.Xml.EncryptedData")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.Xml", "System.Security.Cryptography.Xml.EncryptionMethod")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.Xml", "System.Security.Cryptography.Xml.KeyInfoName")]

        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.Xml", "System.Security.Cryptography.Aes")]

**MtouchExtraArgs**
<MtouchExtraArgs>--linkskip=System.Security.Cryptography.Xml</MtouchExtraArgs>

does not work.

**PublishTrimmed**
`<PublishTrimmed>false</PublishTrimmed>`

does not work. iOS requires PublishTrimmed=true for MAUI.

**Is this release or debug mode also?**
Release mode = does not work
Debug mode = it works

`Related to specific iPhone?`
Tested on iOS 14 or iOS 16, it does not matter.

**Code from [https://github.com/dotnet/runtime](https://github.com/dotnet/runtime) (MIT licence)**
SourceServer\2d221f7ca446c7172a7ead39d390abf5f76ee61f74c281d07c029fb3c69d140a\EncryptedXml.cs
throw new CryptographicException(SR.Cryptography_Xml_MissingAlgorithm);
namespace System.Security.Cryptography.Xml

**Comment by rokmeglic71** [comment]
I tested a few more things.

**#1 Editing MAUI project file**
`		
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios|AnyCPU'">
<MtouchExtraArgs>--linkskip=System.Security.Cryptography.Xml --linkskip=System.Security.Cryptography.Xml.EncryptedKey --linkskip=System.Security.Cryptography.Xml.CipherData --linkskip=System.Security.Cryptography.Xml.KeyInfoName --linkskip=System.Security.Cryptography.Xml.EncryptionMethod --linkskip=System.Security.Cryptography.Xml.EncryptedData --linkskip=System.Security.Cryptography.Xml.EncryptedXml --linkskip=System.Security.Cryptography.Algorithms --linkskip=System.Security.Cryptography.Aes --linkskip=System.Security.Cryptography.RSA --linkskip=System.Security.Cryptography.AesCcm --linkskip=System.Security.Cryptography.AesCng --linkskip=System.Security.Cryptography.AesGcm</MtouchExtraArgs>	`

it did not work.

**#2 Extended DynamicDependency calls**
```
[DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.Xml", "System.Security.Cryptography.Xml.EncryptedKey")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.Xml", "System.Security.Cryptography.Xml.CipherData")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.Xml", "System.Security.Cryptography.Xml.EncryptedXml")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.Xml", "System.Security.Cryptography.Xml.EncryptedData")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.Xml", "System.Security.Cryptography.Xml.EncryptionMethod")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.Xml", "System.Security.Cryptography.Xml.KeyInfoName")]

        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography", "System.Security.Cryptography.Aes")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography", "System.Security.Cryptography.AesCcm")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography", "System.Security.Cryptography.AesCng")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography", "System.Security.Cryptography.AesGcm")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography", "System.Security.Cryptography.RSA")]

        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.Aes", "System.Security.Cryptography.Algorithms")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.AesCcm", "System.Security.Cryptography.Algorithms")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.AesCng", "System.Security.Cryptography.Algorithms")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.AesGcm", "System.Security.Cryptography.Algorithms")]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, "System.Security.Cryptography.RSA", "System.Security.Cryptography.Algorithms")]

        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.Xml.EncryptedKey))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.Xml.CipherData))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.Xml.EncryptedXml))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.Xml.EncryptedData))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.Xml.EncryptionMethod))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.Xml.KeyInfoName))]

        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.Aes))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.AesCcm))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.AesCng))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.AesGcm))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.RSA))]
        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Security.Cryptography.ECKeyXmlFormat))]

        [System.Diagnostics.CodeAnalysis.RequiresDynamicCode("Necessary for decryption")]
        [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("Ensures linker doesn't trim needed code")]
```
it did not work.

In the end, the solution is the same as here [#102033
](https://github.com/dotnet/runtime/issues/102033#issuecomment-2101685600), just with different XML content:


```
<linker>
	<assembly fullname="System.Security.Cryptography" preserve="all" />
</linker>
```

**Project file content:** 
```
<ItemGroup>
	<TrimmerRootDescriptor Include="trim.xml" />
</ItemGroup>
```

**Solution detail:**
trim.xml file is set to Build action: none
