### ISSUE TITLE
[browser][mt] AsyncTransactionScopeTests.VerifyBYOTSyncTSNestedAsync - Value is not null

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#97513]
### Error Blob

```json
{
  "ErrorMessage": "[FAIL] System.Transactions.Tests.AsyncTransactionScopeTests.VerifyBYOTSyncTSNestedAsync",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-97391-merge-e87055956b43439792/WasmTestOnBrowser-System.Transactions.Local.Tests/1/console.575bfd9c.log?helixlogtype=result)
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=540294&view=logs&jobId=63c2d0c8-fec2-5788-81c8-f3ac95e8841f
```
[13:18:51] info: [2024-01-25T13:18:51.175Z] [FAIL] System.Transactions.Tests.AsyncTransactionScopeTests.VerifyBYOTSyncTSNestedAsync
[13:18:51] info: Assert.Null() Failure: Value is not null
[13:18:51] info: Expected: null
[13:18:51] info: Actual:   CommittableTransaction { IsolationLevel = Serializable, PromoterType = 00000000-0000-0000-0000-000000000000, TransactionInformation = TransactionInformation { CreationTime = 2024-01-25T13:18:50.4690000, DistributedIdentifier = 00000000-0000-0000-0000-000000000000, LocalIdentifier = "daab704c-0ff1-40af-aa0a-a1710e8d470b:293", Status = Committed } }
[13:18:51] info:    at System.Transactions.Tests.AsyncTransactionScopeTests.AssertTransactionNull()
[13:18:51] info:    at System.Transactions.Tests.AsyncTransactionScopeTests.<>c__DisplayClass18_0.<VerifyBYOTSyncTSNestedAsync>b__0()
[13:18:51] info:    at System.Threading.Tasks.Task.InnerInvoke()
[13:18:51] info:    at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
[13:18:51] info:    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[13:18:51] info: --- End of stack trace from previous location ---
[13:18:51] info:    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[13:18:51] info:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[13:18:51] info: --- End of stack trace from previous location ---
[13:18:51] info:    at System.Transactions.Tests.AsyncTransactionScopeTests.VerifyBYOTSyncTSNestedAsync()
[13:18:51] info: --- End of stack trace from previous location ---

```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=540294
**Error message validated:** `[FAIL] System.Transactions.Tests.AsyncTransactionScopeTests.VerifyBYOTSyncTSNestedAsync`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/25/2024 3:03:12 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[540294](https://dev.azure.com/dnceng-public/public/_build/results?buildId=540294)|dotnet/runtime|[WasmTestOnBrowser-System.Transactions.Local.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=540294&view=ms.vss-test-web.build-test-results-tab&runId=12794238&resultId=186622)|dotnet/runtime#97391|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by maraf** [comment]
Occured on my PR https://github.com/dotnet/runtime/pull/97213

[Build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=559831&view=logs&j=63c2d0c8-fec2-5788-81c8-f3ac95e8841f&t=744baa8c-2e26-50b3-27ca-51a0d84eca60) 
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-97213-merge-0886f4a9b7d94bda8e/WasmTestOnBrowser-System.Transactions.Local.Tests/1/console.7960d9e3.log?helixlogtype=result)

**Comment by pavelsavara** [comment]
let's put back the active issue and investigate root cause.

**Comment by maraf** [comment]
https://github.com/dotnet/runtime/pull/98221

**Comment by pavelsavara** [comment]
Possibly this is improved by https://github.com/dotnet/runtime/pull/99836, let's re-test

**Comment by ilonatommy** [comment]
This test on main run on repeat passes in 100% cases. Unblocking.
