### ISSUE TITLE
Permit loading Explicit layouts with generics constrained to unmanaged

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#97526]
Currently the runtime errors out when trying to load such type:
```cs
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit)]
public struct S<T> where T : unmanaged
{
    [FieldOffset(0)]
    public T t;
    [FieldOffset(0)]
    public int i;
}
```
with `System.TypeLoadException: Could not load type 'S`1' from assembly '_, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because generic types cannot have explicit layout.`

While determining proper offsets for generics is problematic due to unknown sizes, union types with all fields at 0 offset don't face such issues and since the generic is constrained to `unmanaged`, the runtime doesn't need to worry about managed types appearing in the layout.

**Comment by MichalStrehovsky** [comment]
Sidenote: the `unmanaged` constraint is a concept the C# compiler made up and runtime hasn't so far made decisions around that. `typeof(S<>).MakeGenericType(typeof(KeyValuePair<string, string>))` will load fine.

**Comment by hamarb123** [comment]
> Sidenote: the `unmanaged` constraint is a concept the C# compiler made up and runtime hasn't so far made decisions around that. `typeof(S<>).MakeGenericType(typeof(KeyValuePair<string, string>))` will load fine.

That's inaccurate, and has been so since .NET 5.0 at least iirc, but probably even a bit earlier - [link](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwBYBuYsyvAOgCV0EowBTZgYQD2YAA5QANt2QBlSQDcoAY24BneiQpU2HLrwCSMBJIHCZyeUtXEGAZko5yfYgG9i5N3Zyv3Lou7/kEAE9hbgEAMwAKKQAeAD4ASmYAWQgAa24AcW4YSUUAFWDuCKCQ8IiAaW5AgDUIMVRuAAVoZGiqUjgmUgT4tT8AX2JBomIAbSkENAUEABkIQIFUBAi5haXy2AATZgBRAA9hMUUoBHiAXRtyZUnUafIYvNjyAHcAC0lucjzyEHJ0SBgEAA5txNs4vG5RgAxKDcMSbADyYTCym4y1I5whlFs3wQfXc0Nh8KRKLREQxF187iwtlgCHIUDU/SAA=).

**Comment by MichalStrehovsky** [comment]
> > Sidenote: the `unmanaged` constraint is a concept the C# compiler made up and runtime hasn't so far made decisions around that. `typeof(S<>).MakeGenericType(typeof(KeyValuePair<string, string>))` will load fine.
> 
> That's inaccurate, and has been so since .NET 5.0 at least iirc, but probably even a bit earlier - [link](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwBYBuYsyvAOgCV0EowBTZgYQD2YAA5QANt2QBlSQDcoAY24BneiQpU2HLrwCSMBJIHCZyeUtXEGAZko5yfYgG9i5N3Zyv3Lou7/kEAE9hbgEAMwAKKQAeAD4ASmYAWQgAa24AcW4YSUUAFWDuCKCQ8IiAaW5AgDUIMVRuAAVoZGiqUjgmUgT4tT8AX2JBomIAbSkENAUEABkIQIFUBAi5haXy2AATZgBRAA9hMUUoBHiAXRtyZUnUafIYvNjyAHcAC0lucjzyEHJ0SBgEAA5txNs4vG5RgAxKDcMSbADyYTCym4y1I5whlFs3wQfXc0Nh8KRKLREQxF187iwtlgCHIUDU/SAA=).

My comment is about `unmanaged` constraint being meaningless to the runtime (it's the same as `struct`). Your example doesn't load because of the StructLayout, not because of unmet constraints.

**Comment by hamarb123** [comment]
I swear I tested this in the past with generic methods, but I presumably must have tested it incorrectly.

I think it would make more sense to allow it based on what the type parameters are in practice, as opposed to what they're constrained to anyway.

So, what I would suggest, is that *if* the type parameters are `unmanaged`, then we allow it to work as expected. And, if you constrain it, then you can ensure yourself that it will successfully load.

**Comment by MichalPetryka** [comment]
> > > Sidenote: the `unmanaged` constraint is a concept the C# compiler made up and runtime hasn't so far made decisions around that. `typeof(S<>).MakeGenericType(typeof(KeyValuePair<string, string>))` will load fine.
> > 
> > 
> > That's inaccurate, and has been so since .NET 5.0 at least iirc, but probably even a bit earlier - [link](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwBYBuYsyvAOgCV0EowBTZgYQD2YAA5QANt2QBlSQDcoAY24BneiQpU2HLrwCSMBJIHCZyeUtXEGAZko5yfYgG9i5N3Zyv3Lou7/kEAE9hbgEAMwAKKQAeAD4ASmYAWQgAa24AcW4YSUUAFWDuCKCQ8IiAaW5AgDUIMVRuAAVoZGiqUjgmUgT4tT8AX2JBomIAbSkENAUEABkIQIFUBAi5haXy2AATZgBRAA9hMUUoBHiAXRtyZUnUafIYvNjyAHcAC0lucjzyEHJ0SBgEAA5txNs4vG5RgAxKDcMSbADyYTCym4y1I5whlFs3wQfXc0Nh8KRKLREQxF187iwtlgCHIUDU/SAA=).
> 
> My comment is about `unmanaged` constraint being meaningless to the runtime (it's the same as `struct`). Your example doesn't load because of the StructLayout, not because of unmet constraints.

That doesn't seem to be fully the case:
```cs
Console.WriteLine(typeof(S<>).MakeGenericType(typeof(string)).FullName);
public struct S<T> where T : unmanaged
{
    public T t;
}
```
gives:
```
System.ArgumentException: GenericArguments[0], 'System.String', on 'S`1[T]' violates the constraint of type 'T'.
 ---> System.TypeLoadException: GenericArguments[0], 'System.String', on 'S`1[T]' violates the constraint of type parameter 'T'.
   at System.RuntimeTypeHandle.Instantiate(RuntimeType inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Program.<Main>$(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

**Comment by MichalStrehovsky** [comment]
> That doesn't seem to be fully the case:

Not sure I follow - I wrote unmanaged is same as struct constraint and yes, string is not a struct.

**Comment by MichalPetryka** [comment]
> > That doesn't seem to be fully the case:
> 
> Not sure I follow - I wrote unmanaged is same as struct constraint and yes, string is not a struct.

Oh I thought you meant it as `struct` being meaningless to the runtime too.

**Comment by lambdageek** [comment]
I wonder how this will interact with the ref/non-ref check in the runtime for something like this:

```csharp
[StructLayout(LayoutKind.Explicit)]
public struct S<T> where T : unmanaged
{
    [FieldOffset(0)]
    public T t;
    [FieldOffset(8)]
    public object i;
}

public struct TwoLongs {
   public long a;
   public long b;
}
```

So `S<long>` is ok, but `S<TwoLongs>` overlaps. I'm not sure if we currently do the overlap check on instantiations.

**Comment by MichalPetryka** [comment]
> I wonder how this will interact with the ref/non-ref check in the runtime for something like this

I'd say that blocking such layouts with managed fields would be okay. I don't have any use cases for generic managed unions.

**Comment by lambdageek** [comment]
> > I wonder how this will interact with the ref/non-ref check in the runtime for something like this
> 
> I'd say that blocking such layouts with managed fields would be okay. I don't have any use cases for generic managed unions.

My point isn't just that we need to block such structs. My point is that we don't have a check on generic instances right now, but if we allow an explicit layout on generics, we would need such a check.  That might be fine - but right now the check isn't there.

**Comment by kg** [comment]
I'm curious about the use scenario for this. It makes me nervous since it would allow you to author a struct that *looks* memory and type safe but will be broken depending on the size of `T`. Is there a problem this solves that can't be solved by a property that wraps `Unsafe.As`?

**Comment by adams85** [comment]
> It makes me nervous since it would allow you to author a struct that looks memory and type safe but will be broken depending on the size of T

There are safe use cases. For example, when the field with the generic type is the last one in the memory layout, it won't be broken.

> Is there a problem this solves that can't be solved by a property that wraps Unsafe.As?

Although I'm not 100% familiar with the topic, e.g. [this looks like a problem](https://fractalfir.github.io/generated_html/rustc_codegen_clr_v0_1_0.html#why_does_layoutkind.explicit_not_work_with_generics?) that could benefit from this.

**Comment by lambdageek** [comment]
> Sidenote: the `unmanaged` constraint is a concept the C# compiler made up and runtime hasn't so far made decisions around that. 

I dont' think this issue is about `unmanaged` actually.

What we need is some logic in the runtime like this:
1. if a generic type definition has an explicit layout, set some bit on the type definition
2. when instantiating a generic type definition, if the bit is set, run the field overlap check on the generic instance.

**Comment by timcassell** [comment]
#43486
