### ISSUE TITLE
[browser] GC - Assertion: should not be reached - simple_nursery_serial_scan_object

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#97543]
### Error Blob

```json
{
  "ErrorMessage": "Assertion: should not be reached at D:/a/_work/1/s/src/mono/mono/sgen/sgen-scan-object.h",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-97441-merge-aaf7269ed7104e83a1/WasmTestOnBrowser-System.Runtime.Tests/1/console.5f83fb81.log?helixlogtype=result)
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=540864&view=logs&jobId=92abeb82-4b48-52bb-630e-73b3c35173bb
```
[19:52:21] info: Starting:    System.Runtime.Tests.dll
[19:53:51] fail: Error: [MONO] * Assertion: should not be reached at D:/a/_work/1/s/src/mono/mono/sgen/sgen-scan-object.h:93

    at st (http://127.0.0.1:49198/_framework/dotnet.runtime.js:3:12809)
    at Yc (http://127.0.0.1:49198/_framework/dotnet.runtime.js:3:164114)
    at wasm_trace_logger (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[161]:0xaaa9)
    at eglib_log_adapter (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[630]:0x3dba7)
    at monoeg_g_logv_nofree (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[552]:0x3c0c3)
    at monoeg_assertion_message (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[556]:0x3c1e4)
    at mono_assertion_message_unreachable (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[559]:0x3c24d)
    at simple_nursery_serial_scan_object (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[1024]:0x54ca7)
    at simple_nursery_serial_drain_gray_stack (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[1021]:0x53c83)
    at finish_gray_stack (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[869]:0x48402)
[19:53:51] fail: Error: [MONO] D:/a/_work/1/s/src/mono/mono/sgen/sgen-gc.c:3970 <disabled>
    at st (http://127.0.0.1:49198/_framework/dotnet.runtime.js:3:12809)
    at Yc (http://127.0.0.1:49198/_framework/dotnet.runtime.js:3:164114)
    at wasm_trace_logger (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[161]:0xaaa9)
    at eglib_log_adapter (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[630]:0x3dba7)
    at monoeg_g_logv_nofree (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[552]:0x3c0c3)
    at monoeg_g_log (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[554]:0x3c186)
    at monoeg_g_log_disabled (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[555]:0x3c1b9)
    at sgen_stop_world (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[843]:0x45999)
    at sgen_perform_collection_inner (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[842]:0x457be)
    at sgen_perform_collection (http://127.0.0.1:49198/_framework/dotnet.native.wasm:wasm-function[840]:0x4571b)
[20:21:42] info: Unable to evaluate script: target frame detached
[20:21:42] info: Unable to evaluate script: disconnected: unable to send message to renderer
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=540864
**Error message validated:** `Assertion: should not be reached at D:/a/_work/1/s/src/mono/mono/sgen/sgen-scan-object.h`
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 1/29/2024 1:34:24 PM UTC

**Comment by pavelsavara** [comment]
cc @lambdageek
