### ISSUE TITLE
BinderTracingTest.ResolutionFlow.cmd Timed Out

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#97735]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=545844
Build error leg or test failing: Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd
Pull request: https://github.com/dotnet/runtime.git/pull/97694

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd Timed Out",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=545844
**Error message validated:** `binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd Timed Out`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/30/2024 11:44:14 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[689262](https://dev.azure.com/dnceng-public/public/_build/results?buildId=689262)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=689262&view=ms.vss-test-web.build-test-results-tab&runId=17120718&resultId=113986)|dotnet/runtime#102260|
|[668696](https://dev.azure.com/dnceng-public/public/_build/results?buildId=668696)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=668696&view=ms.vss-test-web.build-test-results-tab&runId=16585098&resultId=114057)|dotnet/runtime#102000|
|[667190](https://dev.azure.com/dnceng-public/public/_build/results?buildId=667190)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=667190&view=ms.vss-test-web.build-test-results-tab&runId=16548942&resultId=114055)|dotnet/runtime#95565|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|3|

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci since it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr r2r-extra 20240414.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643145&view=ms.vss-test-web.build-test-results-tab&runId=15863410&resultId=121410&paneView=debug)

**Failed tests:**
```
R2R-CG2 windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
    - Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd
```

**Error message:**
```
cmdLine:C:hwB29F09D3wA8C608E4eLoaderLoader../binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 4/15/2024 4:39:14 AM, end: 4/15/2024 6:09:14 AM)

Return code:      -100
Raw output file:      C:hwB29F09D3wA8C608E4uploadsinding	racingBinderTracingTest.ResolutionFlowoutput.txt
Raw output:
BEGIN EXECUTION
AssemblyToLoad.dll
BinderTracingTest.ResolutionFlow.dll
TestLibrary.dll
        3 file(s) copied.
 4:39:15.03
Response file: C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowAssemblyToLoad.dll.rsp
C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowIL-CG2AssemblyToLoad.dll
-o:C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowAssemblyToLoad.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hwB29F09D3pSystem.*.dll
-r:C:hwB29F09D3pMicrosoft.*.dll
-r:C:hwB29F09D3p\xunit.*.dll
-r:C:hwB29F09D3pmscorlib.dll
-r:C:hwB29F09D3p
etstandard.dll
" "dotnet" "C:hwB29F09D3pcrossgen2crossgen2.dll" @"C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowAssemblyToLoad.dll.rsp"   -r:C:hwB29F09D3wA8C608E4eLoaderLoaderIL-CG2*.dll  -r:C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowIL-CG2*.dll"
Emitting R2R PE file: C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowAssemblyToLoad.dll
" "dotnet" "C:hwB29F09D3p
2rdump
2rdump.dll" --header --sc --in C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowAssemblyToLoad.dll --out C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowAssemblyToLoad.dll.r2rdump --val"
 4:39:16.82
 4:39:16.83
Response file: C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowBinderTracingTest.ResolutionFlow.dll.rsp
C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowIL-CG2BinderTracingTest.ResolutionFlow.dll
-o:C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowBinderTracingTest.ResolutionFlow.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hwB29F09D3pSystem.*.dll
-r:C:hwB29F09D3pMicrosoft.*.dll
-r:C:hwB29F09D3p\xunit.*.dll
-r:C:hwB29F09D3pmscorlib.dll
-r:C:hwB29F09D3p
etstandard.dll
" "dotnet" "C:hwB29F09D3pcrossgen2crossgen2.dll" @"C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowBinderTracingTest.ResolutionFlow.dll.rsp"   -r:C:hwB29F09D3wA8C608E4eLoaderLoaderIL-CG2*.dll  -r:C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowIL-CG2*.dll"
Emitting R2R PE file: C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowBinderTracingTest.ResolutionFlow.dll
" "dotnet" "C:hwB29F09D3p
2rdump
2rdump.dll" --header --sc --in C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowBinderTracingTest.ResolutionFlow.dll --out C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowBinderTracingTest.ResolutionFlow.dll.r2rdump --val"
 4:39:18.99
 4:39:18.99
Response file: C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowTestLibrary.dll.rsp
C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowIL-CG2TestLibrary.dll
-o:C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowTestLibrary.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hwB29F09D3pSystem.*.dll
-r:C:hwB29F09D3pMicrosoft.*.dll
-r:C:hwB29F09D3p\xunit.*.dll
-r:C:hwB29F09D3pmscorlib.dll
-r:C:hwB29F09D3p
etstandard.dll
" "dotnet" "C:hwB29F09D3pcrossgen2crossgen2.dll" @"C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowTestLibrary.dll.rsp"   -r:C:hwB29F09D3wA8C608E4eLoaderLoaderIL-CG2*.dll  -r:C:hwB29F09D3wA8C608E4eLoaderinding	racingBinderTracingTest.ResolutionFlowIL-CG2*.dll"
Emitting 
```

**Stack trace:**
```
    at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor64|0_65(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr jitstress 20240421.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=651442&view=ms.vss-test-web.build-test-results-tab&runId=16107102&resultId=121416&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked jitminopts @ Windows.10.Amd64.Open
    - Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd
```

**Error message:**
```
 

cmdLine:C:hwC34B09B6wB0DE0977eLoaderLoader../binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 4/22/2024 6:31:12 AM, end: 4/22/2024 7:01:13 AM)

Return code:      -100
Raw output file:      C:hwC34B09B6wB0DE0977uploadsinding	racingBinderTracingTest.ResolutionFlowoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwC34B09B6pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  BinderTracingTest.ResolutionFlow.dll 
[6:31:14 AM] Running AssemblyLoadContextResolving_ReturnNull...
[6:31:15 AM] Running AssemblyLoadContextResolving_LoadAssembly...
[6:31:15 AM] Running AssemblyLoadContextResolving_NameMismatch...
[6:31:15 AM] Running AssemblyLoadContextResolving_MultipleHandlers...
[6:31:16 AM] Running AppDomainAssemblyResolve_ReturnNull...
[6:31:16 AM] Running AppDomainAssemblyResolve_LoadAssembly...
[6:31:16 AM] Running AppDomainAssemblyResolve_NameMismatch...
[6:31:16 AM] Running AppDomainAssemblyResolve_MultipleHandlers...
[6:31:16 AM] Launching process for AssemblyLoadFromResolveHandler_LoadDependency...
[6:31:17 AM] Running AssemblyLoadFromResolveHandler_LoadDependency...

[6:31:18 AM] Launching process for AssemblyLoadFromResolveHandler_NotTracked...
[6:31:20 AM] Running AssemblyLoadFromResolveHandler_NotTracked...

cmdLine:C:hwC34B09B6wB0DE0977eLoaderLoader../binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 4/22/2024 6:31:12 AM, end: 4/22/2024 7:01:13 AM)
Invoking: C:Program Files (x86)Windows Kits10Debuggerscdb.exe -c "$<C:hwC34B09B6		mpclpplf.tmp" -z "C:corescrashdump_1376.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:corescrashdump_1376.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hwC34B09B6pPDB
Symbol search path is: C:hwC34B09B6pPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Mon Apr 22 07:01:13.000 2024 (UTC + 0:00)
System Uptime: 0 days 4:02:58.604
Process Uptime: 0 days 0:30:00.000
..............................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
eax=00000000 ebx=00000001 ecx=00000000 edx=00000000 esi=00000001 edi=00000001
eip=7749f18c esp=02ffe06c ebp=02ffe1fc iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000206
ntdll!ZwWaitForMultipleObjects+0xc:
7749f18c c21400          ret     14h
0:000> cdb: Reading initial command '$<C:hwC34B09B6		mpclpplf.tmp'
0:000> .load C:Users
unner.dotnetsossos.dll
0:000> ~*k

.  0  Id: 560.904 Suspend: 0 Teb: 02d31000 Unfrozen
ChildEBP RetAddr  
WARNING: Stack unwind information not available. Following frames may be wrong.
02ffe1fc 71c9e7c6 ntdll!ZwWaitForMultipleObjects+0xc
02ffe280 71c9ece0 coreclr!Thread::DoAppropriateAptStateWait+0xc6
02ffe3dc 71ca55cf coreclr!Thread::DoAppropriateWaitWorker+0x3d2
02ffe430 71c9e87d coreclr!`Thread::DoAppropriateWait'::`9'::__Body
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor64|0_65(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr jitstress 20240422.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652921&view=ms.vss-test-web.build-test-results-tab&runId=16147770&resultId=121416&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked jitstress1_tiered @ Windows.10.Amd64.Open
    - Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd
```

**Error message:**
```
 






cmdLine:C:hwA3240967wAAC1097DeLoaderLoader../binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 4/23/2024 5:52:57 AM, end: 4/23/2024 6:22:57 AM)

Return code:      -100
Raw output file:      C:hwA3240967wAAC1097Duploadsinding	racingBinderTracingTest.ResolutionFlowoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwA3240967pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  BinderTracingTest.ResolutionFlow.dll 
[5:52:59 AM] Running AssemblyLoadContextResolving_ReturnNull...
[5:53:00 AM] Running AssemblyLoadContextResolving_LoadAssembly...
[5:53:00 AM] Running AssemblyLoadContextResolving_NameMismatch...
[5:53:00 AM] Running AssemblyLoadContextResolving_MultipleHandlers...
[5:53:00 AM] Running AppDomainAssemblyResolve_ReturnNull...
[5:53:00 AM] Running AppDomainAssemblyResolve_LoadAssembly...
[5:53:01 AM] Running AppDomainAssemblyResolve_NameMismatch...
[5:53:01 AM] Running AppDomainAssemblyResolve_MultipleHandlers...
[5:53:01 AM] Launching process for AssemblyLoadFromResolveHandler_LoadDependency...
[5:53:02 AM] Running AssemblyLoadFromResolveHandler_LoadDependency...

[5:53:04 AM] Launching process for AssemblyLoadFromResolveHandler_NotTracked...
[5:53:05 AM] Running AssemblyLoadFromResolveHandler_NotTracked...

[5:53:07 AM] Launching process for FindInLoadContext_CustomALC...
[5:53:09 AM] Running FindInLoadContext_CustomALC...

[5:53:11 AM] Launching process for FindInLoadContext_DefaultALC...
[5:53:12 AM] Running FindInLoadContext_DefaultALC...

[5:53:14 AM] Launching process for FindInLoadContext_DefaultALC_IncompatibleVersion...
[5:53:15 AM] Running FindInLoadContext_DefaultALC_IncompatibleVersion...

[5:53:17 AM] Launching process for ApplicationAssemblies...
[5:53:18 AM] Running ApplicationAssemblies...

[5:53:20 AM] Launching process for ApplicationAssemblies_IncompatibleVersion...
[5:53:21 AM] Running ApplicationAssemblies_IncompatibleVersion...

cmdLine:C:hwA3240967wAAC1097DeLoaderLoader../binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 4/23/2024 5:52:57 AM, end: 4/23/2024 6:22:57 AM)
Invoking: C:Program Files (x86)Windows Kits10Debuggerscdb.exe -c "$<C:hwA3240967		mp1mmhvu.tmp" -z "C:corescrashdump_760.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:corescrashdump_760.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hwA3240967pPDB
Symbol search path is: C:hwA3240967pPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Tue Apr 23 06:22:57.000 2024 (UTC + 0:00)
System Uptime: 0 days 0:39:24.409
Process Uptime: 0 days 0:30:00.000
..............................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
eax=00000000 ebx=00000001 ecx=00000000 edx=00000000 esi=00000001 edi=00000001
eip=77abf18c esp=02f7e034 ebp=02f7e1c4 iopl=0         nv up ei pl nz na po nc
cs=0023  ss=002
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor64|0_65(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr jitstress 20240528.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=690625&view=ms.vss-test-web.build-test-results-tab&runId=17152182&resultId=120560&paneView=debug)

**Failed tests:**
```
coreclr windows x64 Checked jitstress1_tiered @ Windows.10.Amd64.Open
    - Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd
```

**Error message:**
```
 


cmdLine:C:hwB9E209C8wA42B0916eLoaderLoader../binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 5/29/2024 5:48:05 AM, end: 5/29/2024 6:18:05 AM)

Return code:      -100
Raw output file:      C:hwB9E209C8wA42B0916uploadsinding	racingBinderTracingTest.ResolutionFlowoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwB9E209C8pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  BinderTracingTest.ResolutionFlow.dll 
[5:48:07 AM] Running AssemblyLoadContextResolving_ReturnNull...
[5:48:08 AM] Running AssemblyLoadContextResolving_LoadAssembly...
[5:48:08 AM] Running AssemblyLoadContextResolving_NameMismatch...
[5:48:08 AM] Running AssemblyLoadContextResolving_MultipleHandlers...
[5:48:08 AM] Running AppDomainAssemblyResolve_ReturnNull...
[5:48:08 AM] Running AppDomainAssemblyResolve_LoadAssembly...
[5:48:08 AM] Running AppDomainAssemblyResolve_NameMismatch...
[5:48:08 AM] Running AppDomainAssemblyResolve_MultipleHandlers...
[5:48:09 AM] Launching process for AssemblyLoadFromResolveHandler_LoadDependency...
[5:48:10 AM] Running AssemblyLoadFromResolveHandler_LoadDependency...

[5:48:12 AM] Launching process for AssemblyLoadFromResolveHandler_NotTracked...
[5:48:13 AM] Running AssemblyLoadFromResolveHandler_NotTracked...

[5:48:15 AM] Launching process for FindInLoadContext_CustomALC...
[5:48:16 AM] Running FindInLoadContext_CustomALC...

cmdLine:C:hwB9E209C8wA42B0916eLoaderLoader../binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 5/29/2024 5:48:05 AM, end: 5/29/2024 6:18:05 AM)
Invoking: C:Program Files (x86)Windows Kits10Debuggersdcdb.exe -c "$<C:hwB9E209C8		mptpw0uy.tmp" -z "C:corescrashdump_3940.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:corescrashdump_3940.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hwB9E209C8pPDB
Symbol search path is: C:hwB9E209C8pPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x64
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Wed May 29 06:18:05.000 2024 (UTC + 0:00)
System Uptime: 0 days 0:41:17.119
Process Uptime: 0 days 0:29:59.000
............................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
For analysis of this file, run !analyze -v
ntdll!ZwWaitForMultipleObjects+0x14:
00007ffe`87156974 c3              ret
0:000> cdb: Reading initial command '$<C:hwB9E209C8		mptpw0uy.tmp'
0:000> .load C:Users
unner.dotnetsossos.dll
0:000> ~*k

.  0  Id: f64.f2c Suspend: 0 Teb: 00000090`23aa6000 Unfrozen
Child-SP          RetAddr           Call Site
00000090`23d7d6e8 00007ffe`84474d6f ntdll!ZwWaitForMultipleObjects+0x14
*** WARNING: Unable to verify checksum for coreclr.dll
00000090`23d7d6f0 00007ffe`7b1f3809 KERNELBASE!WaitForMultipleObjectsEx+0xef
00000090`23d7d9f0 00007ffe`7b1f3f28 coreclr!Thread::DoAppropriateAptStateWait+0x119
00000090`23d7dac0 00007ffe`7b1fd176 coreclr!Thread::DoAppropriateWaitWorker+0x508
00000090`23d7dd90 00007ffe`7b1f395e coreclr!`Thread::DoAppropriateWait'::`11'::__Body::Run+0xa6
0000
```

**Stack trace:**
```
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor64|0_65(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```
