### ISSUE TITLE
[NativeAOT] Assert in ILC when compiling System.Data.DataSetExtensions.Tests in Debug build

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#97758]
```
"/home/navara/runtime/artifacts/bin/coreclr/linux.arm.Debug/x64/ilc/ilc" @"/home/navara/runtime/artifacts/obj/System.Data.DataSetExtensions.Tests/Debug/net9.0/native/System.Data.DataSetExtensions.Tests.ilc.rsp"
Process terminated. Assertion failed.
   at ILCompiler.Dataflow.MethodBodyScanner.InterproceduralScan(MethodIL startingMethodBody) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/MethodBodyScanner.cs:line 332
   at ILCompiler.Dataflow.ReflectionMethodBodyScanner.InterproceduralScan(MethodIL methodBody) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReflectionMethodBodyScanner.cs:line 103
   at ILCompiler.Dataflow.ReflectionMethodBodyScanner.ScanAndProcessReturnValue(NodeFactory factory, FlowAnnotations annotations, Logger logger, MethodIL methodBody) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReflectionMethodBodyScanner.cs:line 128
   at ILCompiler.DependencyAnalysis.DataflowAnalyzedMethodNode.GetStaticDependencies(NodeFactory factory) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/DataflowAnalyzedMethodNode.cs:line 35
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 182
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1 node) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 222
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack() in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 257
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 308
   at ILCompiler.RyuJitCompilation.CompileInternal(String outputFile, ObjectDumper dumper) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.RyuJit/Compiler/RyuJitCompilation.cs:line 96
   at ILCompiler.Compilation.ILCompiler.ICompilation.Compile(String outputFile, ObjectDumper dumper) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Compilation.cs:line 528
   at ILCompiler.Program.Run() in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler/Program.cs:line 585
   at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass236_0.<.ctor>b__0(ParseResult result) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler/ILCompilerRootCommand.cs:line 292
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at System.CommandLine.ParseResult.Invoke()
   at ILCompiler.Program.Main(String[] args) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler/Program.cs:line 753
```

**Comment by MichalStrehovsky** [comment]
System.Data.DataSetExtensions.Tests/Debug/net9.0 - you're running a configuration we don't cover anywhere in the CI. We usually do `-rc Checked -lc Release` for libs tests. `-c Debug` will find new bugs that might not be arm specific.

**Comment by filipnavara** [comment]
I can confirm that this happens on linux-x64 too.

**Comment by filipnavara** [comment]
> We usually do `-rc Checked -lc Release` for libs tests. `-c Debug` will find new bugs that might not be arm specific.

Unfortunately the Release/Checked builds on linux-arm are still a mine field. Nearly nothing works there.
