### ISSUE TITLE
Test failure System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#97936]
Run: [runtime-coreclr libraries-jitstress2-jitstressregs 20240203.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552105&view=ms.vss-test-web.build-test-results-tab&runId=13132174&resultId=165717&paneView=debug)

Failed test:
```
net9.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs0x80-(Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7

- System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration

net9.0-linux-Release-arm64-CoreCLR_checked-jitstress2_jitstressregs0x10-(Ubuntu.1804.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8

- System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration
```
**Error message:**
```
Assert.Equal() Failure: Collections differ
↓ (pos 266)
Expected: [···, 50, 48, 51, 49, 48, ···]
Actual:   [···, 50, 48, 52, 49, 48, ···]
↑ (pos 266)



Stack trace
   at System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.<>c.<<RefreshOcspResponse_BeforeExpiration>b__5_0>d.MoveNext() in /_/src/libraries/System.Net.Security/tests/UnitTests/SslStreamCertificateContextOcspLinuxTests.cs:line 112
--- End of stack trace from previous location ---
   at System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.SimpleTest(PkiOptions pkiOptions, RunSimpleTest callback, String callerName, Boolean pkiOptionsInTestName) in /_/src/libraries/System.Net.Security/tests/UnitTests/SslStreamCertificateContextOcspLinuxTests.cs:line 241
   at System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration() in /_/src/libraries/System.Net.Security/tests/UnitTests/SslStreamCertificateContextOcspLinuxTests.cs:line 98
--- End of stack trace from previous location ---
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-02-03T22:23:24.079Z | runtime-extra-platforms | Release | osx.1200.amd64.open | x64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"configuration":"Release","DefinitionId":"154","Project":"public","System.JobAttempt":"1","AzurePipelinesTestRunId":"13142374","DefinitionName":"runtime-extra-platforms","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20240203.4","operatingSystem":"OSX.1200.Amd64.Open","System.StageName":"Build","System.JobId":"cd385208-11d3-5d70-fa38-1c21a65d17f1","System.PhaseName":"build_tvossimulator_x64_Release_AllSubsets_Mono","System.PhaseAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.StageAttempt":"1","runtimeFlavor":"mono","BuildId":"552485","architecture":"x64"} | Schedule
2024-02-03T21:26:17.289Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"DefinitionId":"154","System.JobName":"__default","System.JobAttempt":"1","Project":"public","DefinitionName":"runtime-extra-platforms","BuildNumber":"20240203.4","CollectionUri":"https://dev.azure.com/dnceng-public/","runtimeFlavor":"mono","architecture":"arm64","BuildId":"552485","System.StageAttempt":"1","System.PhaseAttempt":"1","System.StageName":"Build","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Reason":"Schedule","operatingSystem":"OSX.13.Amd64.AppleTV.Open","AzurePipelinesTestRunId":"13142042","configuration":"Release"} | Schedule
2024-02-03T21:22:09.63Z | runtime-extra-platforms | Release | ubuntu.2204.amd64.android.29.open.rt | x64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"configuration":"Release","System.JobAttempt":"1","DefinitionName":"runtime-extra-platforms","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildId":"552485","runtimeFlavor":"mono","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"13142030","System.StageName":"Build","DefinitionId":"154","architecture":"x64","System.JobId":"8ce12db4-5178-5d5b-6012-cb5f9bb20b0f","System.StageAttempt":"1","Reason":"Schedule","System.JobName":"__default","operatingSystem":"Ubuntu.2204.Amd64.Android.29.Open","System.PhaseName":"build_linux_bionic_x64_Release_AllSubsets_Mono","Project":"public","BuildNumber":"20240203.4"} | Schedule
2024-02-03T10:25:39.347Z | runtime-extra-platforms | Release | osx.1200.amd64.open | x64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"System.StageName":"Build","architecture":"x64","Reason":"Schedule","Project":"public","BuildId":"552107","operatingSystem":"OSX.1200.Amd64.Open","DefinitionId":"154","configuration":"Release","System.JobAttempt":"1","System.PhaseName":"build_tvossimulator_x64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"13132964","System.JobName":"__default","BuildNumber":"20240203.2","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","runtimeFlavor":"mono","System.JobId":"cd385208-11d3-5d70-fa38-1c21a65d17f1","DefinitionName":"runtime-extra-platforms"} | Schedule
2024-02-03T09:47:40.758Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","architecture":"arm64","configuration":"Release","DefinitionId":"154","BuildId":"552107","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Project":"public","runtimeFlavor":"mono","System.JobAttempt":"1","BuildNumber":"20240203.2","System.StageName":"Build","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Reason":"Schedule","AzurePipelinesTestRunId":"13132284","System.PhaseAttempt":"1","System.JobName":"__default","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1"} | Schedule
<details>
<summary>More failures</summary>

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-02-02T22:32:43.508Z | runtime-extra-platforms | Release | osx.1200.amd64.open | x64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"configuration":"Release","System.PhaseName":"build_tvossimulator_x64_Release_AllSubsets_Mono","DefinitionName":"runtime-extra-platforms","DefinitionId":"154","architecture":"x64","System.JobId":"cd385208-11d3-5d70-fa38-1c21a65d17f1","BuildNumber":"20240202.3","System.StageAttempt":"1","System.JobName":"__default","operatingSystem":"OSX.1200.Amd64.Open","AzurePipelinesTestRunId":"13118178","runtimeFlavor":"mono","BuildId":"551535","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public","System.StageName":"Build","System.PhaseAttempt":"1","Reason":"Schedule"} | Schedule
2024-02-02T21:49:43.36Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"Project":"public","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"13117142","DefinitionId":"154","System.StageName":"Build","configuration":"Release","BuildId":"551535","CollectionUri":"https://dev.azure.com/dnceng-public/","Reason":"Schedule","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.JobAttempt":"1","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","runtimeFlavor":"mono","System.StageAttempt":"1","DefinitionName":"runtime-extra-platforms","BuildNumber":"20240202.3","System.JobName":"__default"} | Schedule
2024-02-02T21:22:50.797Z | runtime-extra-platforms | Release | ubuntu.2204.amd64.android.29.open.rt | x64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"System.StageName":"Build","AzurePipelinesTestRunId":"13116148","architecture":"x64","Project":"public","runtimeFlavor":"mono","System.PhaseName":"build_linux_bionic_x64_Release_AllSubsets_Mono","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","BuildNumber":"20240202.3","configuration":"Release","System.PhaseAttempt":"1","BuildId":"551535","DefinitionName":"runtime-extra-platforms","Reason":"Schedule","operatingSystem":"Ubuntu.2204.Amd64.Android.29.Open","System.JobName":"__default","DefinitionId":"154","System.JobId":"8ce12db4-5178-5d5b-6012-cb5f9bb20b0f","System.StageAttempt":"1"} | Schedule
2024-02-02T14:49:45.119Z | runtime-extra-platforms | Release | osx.1200.amd64.open | x64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"BuildNumber":"20240202.1","System.JobId":"95ca57d8-d816-526d-1f60-a7e65dddec62","DefinitionName":"runtime-extra-platforms","Reason":"Schedule","System.JobName":"__default","operatingSystem":"OSX.1200.Amd64.Open","runtimeFlavor":"mono","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","BuildId":"550552","configuration":"Release","System.StageAttempt":"2","System.PhaseName":"build_tvossimulator_x64_Release_AllSubsets_Mono","DefinitionId":"154","AzurePipelinesTestRunId":"13098172","System.StageName":"Build","Project":"public","System.PhaseAttempt":"2","System.JobAttempt":"2"} | Schedule
2024-02-02T14:09:57.234Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"configuration":"Release","System.PhaseAttempt":"2","BuildId":"550552","operatingSystem":"OSX.13.Amd64.AppleTV.Open","BuildNumber":"20240202.1","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","System.JobAttempt":"2","DefinitionName":"runtime-extra-platforms","Reason":"Schedule","AzurePipelinesTestRunId":"13096294","architecture":"arm64","System.StageAttempt":"2","DefinitionId":"154","System.StageName":"Build","runtimeFlavor":"mono","System.JobName":"__default","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"ffd568e6-d16f-5e80-695c-a9ffc2e0cf22"} | Schedule
2024-02-02T13:38:41.243Z | runtime-extra-platforms | Release | ubuntu.2204.amd64.android.29.open.rt | x64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"Project":"public","configuration":"Release","DefinitionId":"154","System.StageName":"Build","System.StageAttempt":"2","System.JobAttempt":"2","BuildId":"550552","System.PhaseAttempt":"2","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20240202.1","DefinitionName":"runtime-extra-platforms","System.JobId":"ab306dbd-9f73-5131-57d7-1eb5f5188356","System.JobName":"__default","System.PhaseName":"build_linux_bionic_x64_Release_AllSubsets_Mono","Reason":"Schedule","operatingSystem":"Ubuntu.2204.Amd64.Android.29.Open","runtimeFlavor":"mono","AzurePipelinesTestRunId":"13094064","architecture":"x64"} | Schedule
2024-02-02T09:57:46.425Z | runtime-extra-platforms | Release | osx.1200.amd64.open | x64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"operatingSystem":"OSX.1200.Amd64.Open","runtimeFlavor":"mono","System.JobAttempt":"1","configuration":"Release","AzurePipelinesTestRunId":"13088192","architecture":"x64","System.StageName":"Build","BuildNumber":"20240202.1","System.StageAttempt":"1","System.JobId":"cd385208-11d3-5d70-fa38-1c21a65d17f1","BuildId":"550552","System.PhaseName":"build_tvossimulator_x64_Release_AllSubsets_Mono","DefinitionName":"runtime-extra-platforms","System.JobName":"__default","System.PhaseAttempt":"1","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public","DefinitionId":"154"} | Schedule
2024-02-02T09:53:47.963Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"13088186","Project":"public","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","runtimeFlavor":"mono","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","System.JobName":"__default","operatingSystem":"OSX.13.Amd64.AppleTV.Open","System.JobAttempt":"1","architecture":"arm64","System.StageAttempt":"1","DefinitionId":"154","System.StageName":"Build","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20240202.1","BuildId":"550552","configuration":"Release"} | Schedule
2024-02-01T21:58:02.827Z | runtime-extra-platforms | Release | osx.1200.amd64.open | x64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"System.JobName":"__default","runtimeFlavor":"mono","AzurePipelinesTestRunId":"13069930","Reason":"Schedule","System.JobId":"cd385208-11d3-5d70-fa38-1c21a65d17f1","System.JobAttempt":"1","System.StageAttempt":"1","DefinitionName":"runtime-extra-platforms","DefinitionId":"154","BuildId":"549970","System.PhaseName":"build_tvossimulator_x64_Release_AllSubsets_Mono","configuration":"Release","BuildNumber":"20240201.2","Project":"public","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"OSX.1200.Amd64.Open","System.StageName":"Build","architecture":"x64"} | Schedule
2024-02-01T21:51:30.566Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"runtimeFlavor":"mono","System.StageAttempt":"1","System.PhaseAttempt":"1","System.JobName":"__default","BuildId":"549970","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","AzurePipelinesTestRunId":"13069902","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","BuildNumber":"20240201.2","configuration":"Release","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageName":"Build","DefinitionId":"154","Reason":"Schedule"} | Schedule
2024-02-01T10:02:37.417Z | runtime-extra-platforms | Release | osx.1200.amd64.open | x64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"BuildId":"548958","BuildNumber":"20240201.1","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","runtimeFlavor":"mono","architecture":"x64","configuration":"Release","System.StageName":"Build","System.JobName":"__default","Reason":"Schedule","operatingSystem":"OSX.1200.Amd64.Open","System.StageAttempt":"1","System.JobId":"cd385208-11d3-5d70-fa38-1c21a65d17f1","DefinitionId":"154","System.JobAttempt":"1","System.PhaseName":"build_tvossimulator_x64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"13046430","DefinitionName":"runtime-extra-platforms"} | Schedule
2024-02-01T09:34:08.768Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","runtimeFlavor":"mono","Project":"public","BuildId":"548958","System.StageAttempt":"1","AzurePipelinesTestRunId":"13046160","configuration":"Release","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","System.JobName":"__default","DefinitionId":"154","System.JobAttempt":"1","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","System.PhaseAttempt":"1","architecture":"arm64","BuildNumber":"20240201.1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build"} | Schedule
2024-02-01T09:24:01.86Z | runtime-extra-platforms | Release | ubuntu.2204.amd64.android.29.open.rt | x64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | PassedOnRerun | {"System.StageAttempt":"1","System.JobAttempt":"1","BuildNumber":"20240201.1","runtimeFlavor":"mono","DefinitionName":"runtime-extra-platforms","DefinitionId":"154","System.StageName":"Build","System.PhaseName":"build_linux_bionic_x64_Release_AllSubsets_Mono","Project":"public","AzurePipelinesTestRunId":"13046026","configuration":"Release","operatingSystem":"Ubuntu.2204.Amd64.Android.29.Open","Reason":"Schedule","architecture":"x64","System.JobId":"8ce12db4-5178-5d5b-6012-cb5f9bb20b0f","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","BuildId":"548958","System.PhaseAttempt":"1"} | Schedule
2024-01-31T22:11:06.353Z | runtime-extra-platforms | Release | osx.1200.amd64.open | x64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"System.PhaseName":"build_tvossimulator_x64_Release_AllSubsets_Mono","System.StageName":"Build","DefinitionId":"154","System.PhaseAttempt":"1","System.JobName":"__default","architecture":"x64","Project":"public","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.1200.Amd64.Open","runtimeFlavor":"mono","System.JobId":"cd385208-11d3-5d70-fa38-1c21a65d17f1","BuildNumber":"20240131.6","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","configuration":"Release","AzurePipelinesTestRunId":"13030936","BuildId":"548331","Reason":"Schedule"} | Schedule
2024-01-31T21:53:01.665Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"DefinitionName":"runtime-extra-platforms","DefinitionId":"154","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"13030654","System.JobAttempt":"1","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","CollectionUri":"https://dev.azure.com/dnceng-public/","runtimeFlavor":"mono","configuration":"Release","System.JobName":"__default","operatingSystem":"OSX.13.Amd64.AppleTV.Open","BuildId":"548331","Project":"public","architecture":"arm64","System.StageName":"Build","System.StageAttempt":"1","BuildNumber":"20240131.6"} | Schedule
2024-01-31T21:21:55.181Z | runtime-extra-platforms | Release | ubuntu.2204.amd64.android.29.open.rt | x64 | System.Net.Security.Tests.SslStreamCertificateContextOcspLinuxTests.RefreshOcspResponse_BeforeExpiration | Failed | {"operatingSystem":"Ubuntu.2204.Amd64.Android.29.Open","System.StageName":"Build","Reason":"Schedule","System.JobId":"8ce12db4-5178-5d5b-6012-cb5f9bb20b0f","DefinitionId":"154","runtimeFlavor":"mono","Project":"public","System.JobAttempt":"1","AzurePipelinesTestRunId":"13029802","architecture":"x64","System.StageAttempt":"1","BuildId":"548331","BuildNumber":"20240131.6","configuration":"Release","System.JobName":"__default","System.PhaseAttempt":"1","System.PhaseName":"build_linux_bionic_x64_Release_AllSubsets_Mono","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionName":"runtime-extra-platforms"} | Schedule
</details>

**Comment by rzikm** [comment]
duplicate of https://github.com/dotnet/runtime/issues/97779
