### ISSUE TITLE
AssemblySaveModuleBuilderTests.GetArrayMethodTest fails on 'release mono_interpreter linux x64 Debug' CI leg

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#98013]
AssemblySaveModuleBuilderTests.GetArrayMethodTest fails on `release mono_interpreter linux x64 Debug` CI leg.

Not sure why it is only failing on this CI leg, the failure log doesn't have much info, though looks mono specific:

From [log](https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-97350-merge-598460e957bf4f2f86/System.Reflection.Emit.Tests/1/console.fea100ba.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-97350-merge-598460e957bf4f2f86/System.Reflection.Emit.Tests/1/console.fea100ba.log?helixlogtype=result)):
```log
System.Reflection.Emit.Tests.AssemblySaveModuleBuilderTests.GetArrayMethodTest [FAIL]
      System.ArrayTypeMismatchException : Attempted to access an element as a type incompatible with the array.
      Stack Trace:
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(178,0): at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
  Finished:    System.Reflection.Emit.Tests
=== TEST EXECUTION SUMMARY ===
   System.Reflection.Emit.Tests  Total: 1474, Errors: 0, Failed: 1, Skipped: 0, Time: 5.481s
```

**Comment by steveharter** [comment]
cc @BrzVlad
