### ISSUE TITLE
[QUIC] System.Net.Quic.Tests.QuicStreamTests.WriteCanceled_NextWriteThrows Expected exception not thrown 

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#98078]
### Error Blob

```json
{
  "ErrorMessage": "System.Net.Quic.Tests.QuicStreamTests.WriteCanceled_NextWriteThrows [FAIL]",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

Found in this 8.0 deps flow PR: https://github.com/dotnet/runtime/pull/97212

Related past issues:
- https://github.com/dotnet/runtime/issues/86852
- https://github.com/dotnet/runtime/issues/76831
- And a PR that fixed the issue in the past (is this a new regression?): https://github.com/dotnet/runtime/pull/90253

- Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=555122&view=logs&j=5d0c0cf7-4d03-5f34-03a4-db2320737fb6&t=7e45ffda-7df7-597d-59a4-d014036e46bf&l=56
- Queue: `Libraries Test Run checked coreclr linux_musl arm64 Release`
- Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-97212-merge-7c3cee8559984b61a4/System.Net.Quic.Functional.Tests/3/console.f89cf597.log?helixlogtype=result
- Callstack:
```
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
MsQuic supported and using 'libmsquic.so 2.3.0.0 (7ea0e2e640008ad5c86d8d31e0cd186399b6b404)'.
  Discovered:  System.Net.Quic.Functional.Tests (found 124 of 134 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.UnsupportedPlatforms_ThrowsPlatformNotSupportedException [SKIP]
      Condition(s) not met: "IsQuicUnsupported"
    System.Net.Quic.Tests.QuicStreamTests.WriteCanceled_NextWriteThrows [FAIL]
      System.AggregateException : One or more errors occurred. (Assert.Throws() Failure
      Expected: typeof(System.Net.Quic.QuicException)
      Actual:   (No exception was thrown)) (Assert.Throws() Failure
      Expected: typeof(System.Net.Quic.QuicException)
      Actual:   (No exception was thrown))
      ---- Assert.Throws() Failure
      Expected: typeof(System.Net.Quic.QuicException)
      Actual:   (No exception was thrown)
      ---- Assert.Throws() Failure
      Expected: typeof(System.Net.Quic.QuicException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(88,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(295,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(325,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(325,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(289,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(586,0): at System.Net.Quic.Tests.QuicStreamTests.WriteCanceled_NextWriteThrows()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace #1 (Xunit.Sdk.ThrowsException) -----
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(86,0): at System.Net.Quic.Tests.QuicTestBase.AssertThrowsQuicExceptionAsync(QuicError expectedError, Func`1 testCode)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(625,0): at System.Net.Quic.Tests.QuicStreamTests.<WriteCanceled_NextWriteThrows>b__24_1(QuicConnection connection)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(626,0): at System.Net.Quic.Tests.QuicStreamTests.<WriteCanceled_NextWriteThrows>b__24_1(QuicConnection connection)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(299,0): at System.Net.Quic.Tests.QuicTestBase.<>c__DisplayClass39_1.<<RunClientServer>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        ----- Inner Stack Trace #2 (Xunit.Sdk.ThrowsException) -----
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(86,0): at System.Net.Quic.Tests.QuicTestBase.AssertThrowsQuicExceptionAsync(QuicError expectedError, Func`1 testCode)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(606,0): at System.Net.Quic.Tests.QuicStreamTests.<WriteCanceled_NextWriteThrows>b__24_0(QuicConnection connection)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(606,0): at System.Net.Quic.Tests.QuicStreamTests.<WriteCanceled_NextWriteThrows>b__24_0(QuicConnection connection)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(305,0): at System.Net.Quic.Tests.QuicTestBase.<>c__DisplayClass39_1.<<RunClientServer>b__1>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
  Finished:    System.Net.Quic.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Quic.Functional.Tests  Total: 358, Errors: 0, Failed: 1, Skipped: 1, Time: 115.488s
/root/helix/work/workitem/e
----- end Tue Feb 6 15:02:43 UTC 2024 ----- exit code 1 ----------------------------------------------------------
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Provided build not found. Provide a valid build in the "**Build:** :mag_right:" line.
**Validation performed at:** 5/23/2024 2:52:58 PM UTC

**Comment by jeffschwMSFT** [comment]
was not seen recently... dropping blocking-clean-ci

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by ManickaP** [comment]
Triage: there's ~1 failure per month and it's highly likely test bug. We might decide to push this into future.

**Comment by liveans** [comment]
> Triage: there's ~1 failure per month and it's highly likely test bug. We might decide to push this into future.

I saw last occurrence on 3/27, and it failed because of a different reason than this (Idle timeout), I think this test is not failing anymore.

**Comment by ManickaP** [comment]
Let's close it then, we can always re-open if starts popping up again.
