### ISSUE TITLE
[mt][browser] `HttpClient_CancelInDifferentThread` failing with operation cancelled

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#98101]
### Error Blob

```json
{
  "ErrorMessage": "[FAIL] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=557097
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-98083-merge-4fc4545dd1b04ac5b9/WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests/1/console.7c54146d.log?helixlogtype=result) 
```
[12:49:20] fail: [FAIL] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(executor1: JSWebWorker, executor2: NewThread)
[12:49:20] info: System.OperationCanceledException : The operation was canceled.
[12:49:20] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTestBase.<ActionsInDifferentThreads>d__8`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
[12:49:20] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_ActionInDifferentThread(String url, Executor executor1, Executor executor2, Func`2 e2Job)
[12:49:20] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(Executor executor1, Executor executor2)
[12:49:20] info: --- End of stack trace from previous location ---
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[596734](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596734)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596734&view=ms.vss-test-web.build-test-results-tab&runId=14449470&resultId=187303)|dotnet/runtime#99492|
|[596663](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596663)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596663&view=ms.vss-test-web.build-test-results-tab&runId=14446476&resultId=187303)|dotnet/runtime#98559|
|[596477](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596477)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596477&view=ms.vss-test-web.build-test-results-tab&runId=14438142&resultId=187449)|dotnet/runtime#99000|
|[596244](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596244)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596244&view=ms.vss-test-web.build-test-results-tab&runId=14430938&resultId=187302)|dotnet/runtime#99479|
|[595592](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595592)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595592&view=ms.vss-test-web.build-test-results-tab&runId=14410400&resultId=187302)|dotnet/runtime#99081|
|[594929](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594929)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594929&view=ms.vss-test-web.build-test-results-tab&runId=14391718&resultId=187156)|dotnet/runtime#99360|
|[594175](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594175)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594175&view=ms.vss-test-web.build-test-results-tab&runId=14362392&resultId=187329)|dotnet/runtime#99350|
|[594166](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594166)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594166&view=ms.vss-test-web.build-test-results-tab&runId=14362122&resultId=187301)|dotnet/runtime#99081|
|[593365](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593365)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593365&view=ms.vss-test-web.build-test-results-tab&runId=14347914&resultId=187301)|dotnet/runtime#98559|
|[592874](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592874)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592874&view=ms.vss-test-web.build-test-results-tab&runId=14330026&resultId=186892)|dotnet/runtime#99400|
|[592686](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592686)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592686&view=ms.vss-test-web.build-test-results-tab&runId=14322226&resultId=187156)|dotnet/runtime#99185|
|[591452](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591452)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591452&view=ms.vss-test-web.build-test-results-tab&runId=14288276&resultId=187146)|dotnet/runtime#99355|
|[591354](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591354)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591354&view=ms.vss-test-web.build-test-results-tab&runId=14285664&resultId=187290)|dotnet/runtime#99287|
|[591221](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591221)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591221&view=ms.vss-test-web.build-test-results-tab&runId=14279650&resultId=186885)|dotnet/runtime#99240|
|[589810](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589810)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589810&view=ms.vss-test-web.build-test-results-tab&runId=14234274&resultId=187146)|dotnet/runtime#99042|
|[589719](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589719)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=589719&view=ms.vss-test-web.build-test-results-tab&runId=14232486&resultId=187146)|dotnet/runtime#98986|
|[588912](https://dev.azure.com/dnceng-public/public/_build/results?buildId=588912)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=588912&view=ms.vss-test-web.build-test-results-tab&runId=14210402&resultId=187146)|dotnet/runtime#99272|
|[588395](https://dev.azure.com/dnceng-public/public/_build/results?buildId=588395)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=588395&view=ms.vss-test-web.build-test-results-tab&runId=14193122&resultId=187137)||
|[587277](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587277)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587277&view=ms.vss-test-web.build-test-results-tab&runId=14178888&resultId=187164)|dotnet/runtime#98866|
|[586685](https://dev.azure.com/dnceng-public/public/_build/results?buildId=586685)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=586685&view=ms.vss-test-web.build-test-results-tab&runId=14151068&resultId=187136)|dotnet/runtime#98866|
|[585878](https://dev.azure.com/dnceng-public/public/_build/results?buildId=585878)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=585878&view=ms.vss-test-web.build-test-results-tab&runId=14111792&resultId=187064)||
|[584683](https://dev.azure.com/dnceng-public/public/_build/results?buildId=584683)|dotnet/runtime|[System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread](https://dev.azure.com/dnceng-public/public/_build/results?buildId=584683&view=ms.vss-test-web.build-test-results-tab&runId=14072724&resultId=129368)||
|[584322](https://dev.azure.com/dnceng-public/public/_build/results?buildId=584322)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=584322&view=ms.vss-test-web.build-test-results-tab&runId=14063026&resultId=187106)|dotnet/runtime#98559|
|[583505](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583505)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583505&view=ms.vss-test-web.build-test-results-tab&runId=14035962&resultId=187106)|dotnet/runtime#99072|
|[583350](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583350)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583350&view=ms.vss-test-web.build-test-results-tab&runId=14029796&resultId=187081)||
|[581317](https://dev.azure.com/dnceng-public/public/_build/results?buildId=581317)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=581317&view=ms.vss-test-web.build-test-results-tab&runId=14018748&resultId=187224)|dotnet/runtime#98997|
|[579763](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579763)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579763&view=ms.vss-test-web.build-test-results-tab&runId=13919510&resultId=187078)|dotnet/runtime#98947|
|[579145](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579145)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579145&view=ms.vss-test-web.build-test-results-tab&runId=13902496&resultId=100601)|dotnet/runtime#98920|
|[579025](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579025)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579025&view=ms.vss-test-web.build-test-results-tab&runId=13899144&resultId=100745)|dotnet/runtime#96440|
|[578848](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578848)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578848&view=ms.vss-test-web.build-test-results-tab&runId=13892736&resultId=187220)||
|[578632](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578632)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578632&view=ms.vss-test-web.build-test-results-tab&runId=13885862&resultId=100745)|dotnet/runtime#98754|
|[578526](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578526)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578526&view=ms.vss-test-web.build-test-results-tab&runId=13882766&resultId=187076)|dotnet/runtime#98866|
|[578246](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578246)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578246&view=ms.vss-test-web.build-test-results-tab&runId=13875264&resultId=186784)|dotnet/runtime#98852|
|[578279](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578279)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578279&view=ms.vss-test-web.build-test-results-tab&runId=13875716&resultId=100601)|dotnet/runtime#98891|
|[577806](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577806)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577806&view=ms.vss-test-web.build-test-results-tab&runId=13862098&resultId=100745)|dotnet/runtime#98877|
|[577740](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577740)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577740&view=ms.vss-test-web.build-test-results-tab&runId=13859990&resultId=100601)|dotnet/runtime#98472|
|[577721](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577721)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577721&view=ms.vss-test-web.build-test-results-tab&runId=13859320&resultId=100601)|dotnet/runtime#98874|
|[577475](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577475)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577475&view=ms.vss-test-web.build-test-results-tab&runId=13853260&resultId=100601)|dotnet/runtime#95001|
|[577272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577272)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577272&view=ms.vss-test-web.build-test-results-tab&runId=13847492&resultId=100601)|dotnet/runtime#95001|
|[577262](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577262)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577262&view=ms.vss-test-web.build-test-results-tab&runId=13847122&resultId=100745)|dotnet/runtime#98858|
|[577253](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577253)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577253&view=ms.vss-test-web.build-test-results-tab&runId=13846492&resultId=100745)|dotnet/runtime#98846|
|[575947](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575947)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575947&view=ms.vss-test-web.build-test-results-tab&runId=13842752&resultId=187207)|dotnet/runtime#98495|
|[577028](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577028)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577028&view=ms.vss-test-web.build-test-results-tab&runId=13840912&resultId=187065)|dotnet/runtime#96332|
|[576631](https://dev.azure.com/dnceng-public/public/_build/results?buildId=576631)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=576631&view=ms.vss-test-web.build-test-results-tab&runId=13830290&resultId=100601)|dotnet/runtime#98274|
|[576059](https://dev.azure.com/dnceng-public/public/_build/results?buildId=576059)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=576059&view=ms.vss-test-web.build-test-results-tab&runId=13815556&resultId=100601)|dotnet/runtime#98782|
|[575688](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575688)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575688&view=ms.vss-test-web.build-test-results-tab&runId=13806710&resultId=100745)|dotnet/runtime#98753|
|[574940](https://dev.azure.com/dnceng-public/public/_build/results?buildId=574940)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=574940&view=ms.vss-test-web.build-test-results-tab&runId=13786592&resultId=180273)|dotnet/runtime#98118|
|[574499](https://dev.azure.com/dnceng-public/public/_build/results?buildId=574499)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=574499&view=ms.vss-test-web.build-test-results-tab&runId=13773676&resultId=100744)|dotnet/runtime#98566|
|[574087](https://dev.azure.com/dnceng-public/public/_build/results?buildId=574087)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=574087&view=ms.vss-test-web.build-test-results-tab&runId=13762674&resultId=181169)|dotnet/runtime#98118|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|48|

**Comment by mkhamoyan** [comment]
After #98291

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=575688

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-98753-merge-cb5672c654ae499f91/WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests/1/console.13adfd3b.log?helixlogtype=result)
```
[14:04:32] info: [STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(executor1: JSWebWorker, executor2: NewThread)
[14:04:32] info: HttpClient_CancelInDifferentThread: ManagedThreadId: 1188 NativeThreadId: 118751296
[14:04:37] info: Unexpected test case HttpClient_ActionInDifferentThread timeout after 00:00:05.0510000 ManagedThreadId:3
[14:04:37] info: [FAIL] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(executor1: JSWebWorker, executor2: NewThread)
[14:04:37] info: System.OperationCanceledException : The operation was canceled.
[14:04:37] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTestBase.<ActionsInDifferentThreads>d__8`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
[14:04:37] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_ActionInDifferentThread(String url, Executor executor1, Executor executor2, Func`2 e2Job)
[14:04:37] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(Executor executor1, Executor executor2)
[14:04:37] info: --- End of stack trace from previous location ---
```

**Comment by pavelsavara** [comment]
Another [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-99000-merge-a8ac4836611646c588/WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests/1/console.f8e84040.log?helixlogtype=result)
```
[19:43:57] info: [STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(executor1: JSWebWorker, executor2: ThreadPool)
[19:43:57] info: HttpClient_CancelInDifferentThread: ManagedThreadId: 9 NativeThreadId: 56186504
[19:44:02] info: Unexpected test case HttpClient_ActionInDifferentThread timeout after 00:00:05.0530000 ManagedThreadId:10
[19:44:02] info: [FAIL] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(executor1: JSWebWorker, executor2: ThreadPool)
[19:44:02] info: System.OperationCanceledException : The operation was canceled.
[19:44:02] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTestBase.<ActionsInDifferentThreads>d__8`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
[19:44:02] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_ActionInDifferentThread(String url, Executor executor1, Executor executor2, Func`2 e2Job)
[19:44:02] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(Executor executor1, Executor executor2)
[19:44:02] info: --- End of stack trace from previous location ---
```

We can see that this is that the first/test cancelation was not delivered and that only timeout cancelation of the killing `JSWebWorker` 5 seconds later helped.

**Comment by lewing** [comment]
@pavelsavara do we think this one has been resolved?

**Comment by mkhamoyan** [comment]
This started occurring more frequently.
```
[05:45:09] info: [STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(executor1: Main, executor2: Main)
[05:45:09] info: HttpClient_CancelInDifferentThread: ManagedThreadId: 1 NativeThreadId: 13312336
[05:45:09] info: [PASS] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread
[05:45:09] info: [STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(executor1: Main, executor2: ThreadPool)
[05:45:09] info: HttpClient_CancelInDifferentThread: ManagedThreadId: 5 NativeThreadId: 51890608
[05:45:09] info: [PASS] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread
[05:45:09] info: [STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(executor1: Main, executor2: NewThread)
[05:45:09] info: HttpClient_CancelInDifferentThread: ManagedThreadId: 13 NativeThreadId: 101384192
[05:45:09] info: [PASS] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread
[05:45:09] info: [STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(executor1: Main, executor2: JSWebWorker)
[05:45:09] info: HttpClient_CancelInDifferentThread: ManagedThreadId: 14 NativeThreadId: 101384192
[05:45:09] info: [0x060b0000-jsww 05:45:09.303] MONO_WASM: forceDisposeProxies done: 1 imports, 0 exports, 0 GCHandles, 0 JSHandles.
[05:45:09] info: [PASS] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread
[05:45:09] info: [STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(executor1: ThreadPool, executor2: Main)
[05:45:09] info: HttpClient_CancelInDifferentThread: ManagedThreadId: 1 NativeThreadId: 13312336
[05:45:09] info: [PASS] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread
[05:45:09] info: [STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(executor1: ThreadPool, executor2: ThreadPool)
[05:45:09] info: HttpClient_CancelInDifferentThread: ManagedThreadId: 5 NativeThreadId: 51890608
[05:45:09] info: [PASS] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread
[05:45:09] info: [STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(executor1: ThreadPool, executor2: NewThread)
[05:45:14] info: Unexpected test case HttpClient_ActionInDifferentThread timeout after 00:00:05.0010000 ManagedThreadId:9
[05:45:19] info: [FAIL] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(executor1: ThreadPool, executor2: NewThread)
[05:45:19] info: System.OperationCanceledException : The operation was canceled.
[05:45:19] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTestBase.<ActionsInDifferentThreads>d__9`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
[05:45:19] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_ActionInDifferentThread(String url, Executor executor1, Executor executor2, Func`2 e2Job)
[05:45:19] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_CancelInDifferentThread(Executor executor1, Executor executor2)
[05:45:19] info: --- End of stack trace from previous location ---
```
Checking the logs, it works fine initially but fails on the second round with `executor2: NewThread`, consistently with `NewThread`.

**Comment by pavelsavara** [comment]
disabled in https://github.com/dotnet/runtime/pull/106114

**Comment by jeffschwMSFT** [comment]
removing 'blocking-clean-ci' as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0
