### ISSUE TITLE
[debugger][mt][browser] TestDebugUsingMultiThreadedRuntime times out

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#98110]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=554985
Build error leg or test failing: chrome-DebuggerTests.MiscTests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/97992

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Failed DebuggerTests.MiscTests.TestDebugUsingMultiThreadedRuntime",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-98087-merge-515a13ce68e04c0db7/chrome-DebuggerTests.MiscTests/1/console.61fee9a7.log?helixlogtype=result)

```
[xUnit.net 00:01:47.76]     DebuggerTests.MiscTests.TestDebugUsingMultiThreadedRuntime(_attempt: 0) [FAIL]
  Failed DebuggerTests.MiscTests.TestDebugUsingMultiThreadedRuntime(_attempt: 0) [57 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : Test timed out (elapsed time: 60.0023781)
  Stack Trace:
     at DebuggerTests.DebuggerTestBase.WaitFor(String what) in /_/src/mono/browser/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 288
   at DebuggerTests.DebuggerTestBase.SendCommandAndCheck(JObject args, String method, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn, String waitForEvent) in /_/src/mono/browser/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 692
   at DebuggerTests.DebuggerTestBase.StepAndCheck(StepKind kind, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn, Int32 times) in /_/src/mono/browser/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 644
   at DebuggerTests.MiscTests.TestDebugUsingMultiThreadedRuntime(Int32 _attempt) in /_/src/mono/browser/debugger/DebuggerTestSuite/MiscTests.cs:line 1197
--- End of stack trace from previous location ---
  Standard Output Messages:
 | [2024-02-07T13:24:30] DebuggerTests.TestHarnessProxy Information: [testId: 14] New test request for test id 14
 | [2024-02-07T13:24:30] DebuggerTests.TestHarnessProxy Debug: [14] Starting /root/helix/work/correlation/chrome-linux/chrome with --no-sandbox --headless --disable-gpu --lang=en-US --incognito --remote-debugging-port=0 about:blank
 | [2024-02-07T13:24:30] DebuggerTests.TestHarnessProxy Debug: [testId: 13] TestHarnessStartup done
 | [2024-02-07T13:24:30] DebuggerTests.TestHarnessProxy Debug: TestHarnessStartup: closing for 13
 | [2024-02-07T13:24:30] DebuggerTests.TestHarnessProxy Debug: [testId: 14] browser-stderr [0207/132430.559944:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
 | [2024-02-07T13:24:30] DebuggerTests.TestHarnessProxy Debug: [testId: 14] browser-stderr 
 | [2024-02-07T13:24:30] DebuggerTests.TestHarnessProxy Debug: [testId: 14] browser-stderr DevTools listening on ws://127.0.0.1:44955/devtools/browser/e2f58476-46b9-44ad-af5c-88e26d293a1f
 | [2024-02-07T13:24:30] DebuggerTests.TestHarnessProxy Debug: [testId: 14] browser-stderr [0207/132430.588214:WARNING:sandbox_linux.cc(400)] InitializeSandbox() called with multiple threads in process gpu-process.
 | [2024-02-07T13:24:30] DebuggerTests.TestHarnessProxy Information: [testId: 14] launching proxy for ws://127.0.0.1:44955/devtools/page/70D97F9E662EC13AF5A8E89EA24D1C56
 | [2024-02-07T13:24:30] Inspector-14 Information: waiting for the runtime to be ready
 | [2024-02-07T13:24:32] Inspector-14 Information: runtime ready, TEST TIME
 | [2024-02-07T13:24:32] Inspector-14 Information: console.log: Thread:4 - y
 | [2024-02-07T13:24:32] Inspector-14 Information: console.log: Thread:3 - y
 | [2024-02-07T13:24:32] Inspector-14 Information: console.log: Thread:5 - y


[xUnit.net 00:02:50.55]     DebuggerTests.MiscTests.TestDebugUsingMultiThreadedRuntime(_attempt: 2) [FAIL]
```

**Comment by pavelsavara** [comment]
This test is now disabled on CI, that's why it doesn't show up here
