### ISSUE TITLE
[browser][MT] HttpClientCancelTest.SendAsync_Cancel_Success

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#98201]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=558384
Build error leg or test failing: System.Net.WebSockets.Client.Tests.HttpClientCancelTest.SendAsync_Cancel_Success
Pull request: https://github.com/dotnet/runtime/pull/98151

```
[08:36:55] info: [STRT] System.Net.WebSockets.Client.Tests.HttpClientCancelTest.SendAsync_Cancel_Success(server: ws://127.0.0.1:41705/WebSocket/EchoWebSocket.ashx)
[08:36:55] fail: [FAIL] System.Net.WebSockets.Client.Tests.HttpClientCancelTest.SendAsync_Cancel_Success(server: ws://127.0.0.1:41705/WebSocket/EchoWebSocket.ashx)
[08:36:55] info: Actual Open when System.OperationCanceledException: The operation was canceled.
[08:36:55] info:    at System.Threading.CancellationToken.ThrowOperationCanceledException()
[08:36:55] info:    at System.Threading.CancellationToken.ThrowIfCancellationRequested()
[08:36:55] info:    at System.Net.WebSockets.BrowserWebSocket.SendAsyncCore(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
[08:36:55] info:    at System.Net.WebSockets.Client.Tests.ClientWebSocketTestBase.TestCancellation(Func`2 action, Uri server)
[08:36:55] info:    at System.Net.WebSockets.Client.Tests.ClientWebSocketTestBase.TestCancellation(Func`2 action, Uri server)
[08:36:55] info:    at System.Net.WebSockets.Client.Tests.CancelTest.SendAsync_Cancel_Success(Uri server)
[08:36:55] info: --- End of stack trace from previous location ---
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "[FAIL] System.Net.WebSockets.Client.Tests.HttpClientCancelTest.SendAsync_Cancel_Success",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=558384
**Error message validated:** `[[FAIL] System.Net.WebSockets.Client.Tests.HttpClientCancelTest.SendAsync_Cancel_Success`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/9/2024 12:29:11 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[590192](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590192)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590192&view=ms.vss-test-web.build-test-results-tab&runId=14242798&resultId=100600)|dotnet/runtime#99331|
|[583839](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583839)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=583839&view=ms.vss-test-web.build-test-results-tab&runId=14045536&resultId=100600)|dotnet/runtime#99095|
|[579689](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579689)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579689&view=ms.vss-test-web.build-test-results-tab&runId=13917838&resultId=100600)|dotnet/runtime#98838|
|[578065](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578065)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578065&view=ms.vss-test-web.build-test-results-tab&runId=13870388&resultId=100600)|dotnet/runtime#98876|
|[571214](https://dev.azure.com/dnceng-public/public/_build/results?buildId=571214)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=571214&view=ms.vss-test-web.build-test-results-tab&runId=13679392&resultId=187059)|dotnet/runtime#98631|
|[569393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=569393)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=569393&view=ms.vss-test-web.build-test-results-tab&runId=13628044&resultId=100600)|dotnet/runtime#98557|
|[567944](https://dev.azure.com/dnceng-public/public/_build/results?buildId=567944)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=567944&view=ms.vss-test-web.build-test-results-tab&runId=13583596&resultId=100600)|dotnet/runtime#98299|
|[567229](https://dev.azure.com/dnceng-public/public/_build/results?buildId=567229)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=567229&view=ms.vss-test-web.build-test-results-tab&runId=13559724&resultId=100600)|dotnet/runtime#98446|
|[562250](https://dev.azure.com/dnceng-public/public/_build/results?buildId=562250)|dotnet/runtime|[WasmTestOnBrowser-System.Net.WebSockets.Client.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=562250&view=ms.vss-test-web.build-test-results-tab&runId=13425552&resultId=100741)|dotnet/runtime#98152|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|8|

**Comment by lewing** [comment]
cc @pavelsavara
