### ISSUE TITLE
Writing to `StreamWriter.Null` can cause exceptions

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#98457]
This surprised me as I thought a null stream was stateless and did nothing...

```C#
string longLine = new string('#', 100000);
Parallel.For(0, 25, i => StreamWriter.Null.WriteLine(longLine));
```
produces

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.) (Specified argument was out of the range of valid values.) (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.) (Specified argument was out of the range of valid values.) (Specified argument was out of the range of valid values.) (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.) (Specified argument was out of the range of valid values.)
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IO.StreamWriter.WriteLine(String value)
   at Program.<>c__DisplayClass0_0.<<Main>$>b__0(Int32 i) in D:\bugs\streaming-spmi\null\Program.cs:line 4
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Program.<Main>$(String[] args) in D:\bugs\streaming-spmi\null\Program.cs:line 4
 ---> (Inner Exception #1) System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IO.StreamWriter.WriteLine(String value)
   at Program.<>c__DisplayClass0_0.<<Main>$>b__0(Int32 i) in D:\bugs\streaming-spmi\null\Program.cs:line 4
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
```

**Comment by stephentoub** [comment]
Fascinating. It's been like this forever, and I'm amazed we've never noticed before. A singleton exposed from a static should definitely not be implemented like this.

**Comment by EgorBo** [comment]
Today I learned: `StreamWriter.Null` exists 🙂

**Comment by stephentoub** [comment]
Yeah, it's not widely used nor useful. Especially with the existence of TextWriter.Null, which does the RightThing(tm) here.

**Comment by AndyAyersMS** [comment]
I was lazily implementing some optional logging. When logging was disabled, I was concurrently sending lots of text to the null stream figuring doing this was somewhat wasteful but not actually harmful.
