### ISSUE TITLE
Exception rethrows in .net 8.0.2 rethrow wrong exception in nested catch blocks when followed by awaits

### ISSUE THREAD

**Issue by EklipZgit** [dotnet/runtime#98585]
### Description

When rethrowing an exception that was caught inside an outer catch block followed by an await, the outer exception is rethrown instead of the one one from the catch block the throw; is inside of. This began with .net 8.0.2, and does not reproduce in 8.0.1

### Reproduction Steps

XUnit + Fluent Validators reproduction tests:
```CSharp

    [Fact]
    public async Task Validate_BehaviorOfInnerNreRethrows()
    {
        bool threw = false;

        try
        {
            // Must be an async method in order to repro
            await MethodWithInnerNreRethrowAsync();
        }
        catch (Exception ex)
        {
            threw = true;
            var nre = ex.Should().BeOfType<NullReferenceException>();
        }

        threw.Should().Be(true);
    }

    [Fact]
    public async Task Validate_BehaviorOfOtherInnerExceptionsRethrows()
    {
        bool threw = false;

        try
        {
            // Must be an async method in order to repro
            await MethodWithInnerAltExcRethrowAsync();
        }
        catch (Exception ex)
        {
            threw = true;
            var myExc = ex.Should().BeOfType<MyExc>();
        }

        threw.Should().Be(true);
    }

    private async Task MethodWithInnerNreRethrowAsync()
    {
        try
        {
            // This is not necessary for the repro, however it is necessary to compile
            // errorless when you comment out the final await Task.Delay(1)
            // in order to demonstrate that it no longer reprodues without
            // an await inside the outer catch.
            await Task.Delay(1);

            throw new InvalidOperationException("");
        }
        catch (InvalidOperationException ex)
        {
            var something = ex.Message;

            try
            {
                // Throws NRE
                something = ex.InnerException!.Message;
            }
            catch
            {
                // Should rethrow NRE, rethrows the InvalidOperationException instead, when there is an await in the outer catch.
                throw;
            }

            // This await AnythingAsync() must be here, or the problem no longer reproduces.
            await Task.Delay(1);
        }

        // Moving the await outside of the outer catch to the end of the method like below will also no longer reproduce the bug.
        //await Task.Delay(1);
    }

    /// <summary>
    /// Alt variation of the above that proves that this is not just applicable to NRE exceptions, but other exception types as well.
    /// </summary>
    /// <returns></returns>
    private async Task MethodWithInnerAltExcRethrowAsync()
    {
        var a = 1;

        try
        {
            await Task.Delay(1);

            throw new InvalidOperationException("");
        }
        catch (InvalidOperationException)
        {
            try
            {
                // Trick the compiler into not complaining about unreachable Task.Delay below.
                if (a == 1)
                    throw new MyExc("whatever"); // Throws MyExc
            }
            catch
            {
                // Should rethrow MyExc, rethrows the InvalidOperationException instead.
                throw;
            }

            // This await AnythingAsync() must be here, or the problem no longer reproduces.
            await Task.Delay(1);
        }
    }

    public class MyExc : Exception
    {
        public MyExc(string message)
            : base(message)
        {
        }
    }
```

### Expected behavior

The inner exception should be rethrown in both tests

### Actual behavior

The exception from the outer catch block that contains a following await inside of it is rethrown, instead. This can even be seen with the visual studio debugger which was how I first found the issue before writing this set of repro tests. The inner throw statement rethrows the outer exception.

### Regression?

Yes. We've had a test that relies on this since .net 6, made it all the way through net 7 and the net8 upgrade, and began failing as soon as run in a .net 8.0.2 patched container, and now reproducing locally after updating local to 8.0.2).

Both tests pass on 8.0.100 and both fail on 8.0.200

### Known Workarounds

None, besides removing the await that follows the inner try-catch and moving it outside the outer catch block.

**Comment by tboby** [comment]
We're facing this same issue. Here is a very simple reproduction

```
namespace HelloWorld
{
    class Program
    {
        public static async Task ThrowInvalidOperationException(){
            throw new InvalidOperationException();
        }
        static async Task Main()
        {
            try
            {
                throw new ArgumentException();
            }
            catch (ArgumentException)
            {
                try{
                    await ThrowInvalidOperationException();
                }
                catch(Exception){
                    throw;
                }
            }
        }
    }
}
```

And dockerfile

```
FROM mcr.microsoft.com/dotnet/sdk:8.0.101 AS old-build
WORKDIR /app
RUN dotnet new console --force
COPY Program.cs /app/Program.cs
RUN dotnet build -c Release

FROM mcr.microsoft.com/dotnet/sdk:8.0.201 AS new-build
WORKDIR /app
RUN dotnet new console --force
COPY Program.cs /app/Program.cs
RUN dotnet build -c Release

FROM mcr.microsoft.com/dotnet/runtime:8.0.2 AS new-runtime
COPY --from=new-build /app/bin/Release/net8.0 /app/
ENTRYPOINT ["dotnet", "/app/app.dll"]

FROM mcr.microsoft.com/dotnet/runtime:8.0.1 AS old-runtime
COPY --from=old-build /app/bin/Release/net8.0 /app/
ENTRYPOINT ["dotnet", "/app/app.dll"]
```

Run the following:
```
docker build --target old-runtime -t 98585-old .
docker build --target new-runtime -t 98585-new .
docker run 98585-old
docker run 98585-new
```

Gives

```
> docker run 98585-old
Unhandled exception. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at HelloWorld.Program.ThrowInvalidOperationException() in /app/Program.cs:line 6
   at HelloWorld.Program.Main() in /app/Program.cs:line 17
   at HelloWorld.Program.<Main>()
> docker run 98585-new
Unhandled exception. System.ArgumentException: Value does not fall within the expected range.
   at HelloWorld.Program.Main() in /app/Program.cs:line 12
   at HelloWorld.Program.Main() in /app/Program.cs:line 20
   at HelloWorld.Program.<Main>()
```

**Comment by stephentoub** [comment]
This is a C# compiler issue. Presumably it's a duplicate of https://github.com/dotnet/roslyn/issues/71569.
