### ISSUE TITLE
Test failure: System.Runtime.CompilerServices.UnsafeTests.BitCast

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#98594]
**Failed in:** [runtime-coreclr libraries-jitstressregs 20240211.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=561822&view=ms.vss-test-web.build-test-results-tab&runId=13411844&resultId=110912&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-arm-CoreCLR_checked-jitstressregs0x10-(Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Runtime.CompilerServices.UnsafeTests.BitCast
net9.0-linux-Release-arm-CoreCLR_checked-jitstressregs3-(Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Runtime.CompilerServices.UnsafeTests.BitCast
net9.0-linux-Release-arm-CoreCLR_checked-jitstressregs0x80-(Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Runtime.CompilerServices.UnsafeTests.BitCast
net9.0-linux-Release-arm-CoreCLR_checked-jitstressregs0x1000-(Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Runtime.CompilerServices.UnsafeTests.BitCast
net9.0-linux-Release-arm-CoreCLR_checked-jitstressregs1-(Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Runtime.CompilerServices.UnsafeTests.BitCast
net9.0-linux-Release-arm-CoreCLR_checked-jitstressregs0x2000-(Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Runtime.CompilerServices.UnsafeTests.BitCast
net9.0-linux-Release-arm-CoreCLR_checked-jitstressregs2-(Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Runtime.CompilerServices.UnsafeTests.BitCast
net9.0-linux-Release-arm-CoreCLR_checked-jitstressregs4-(Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Runtime.CompilerServices.UnsafeTests.BitCast
net9.0-linux-Release-arm-CoreCLR_checked-jitstressregs8-(Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Runtime.CompilerServices.UnsafeTests.BitCast
```

**Error message:**
```
 System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
```

**Stack trace:**
```
    at System.Runtime.CompilerServices.UnsafeTests.BitCast() in /_/src/libraries/System.Runtime/tests/System.Runtime.CompilerServices.Unsafe.Tests/UnsafeTests.cs:line 1278
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by EgorBo** [comment]
The test was reverted in https://github.com/dotnet/runtime/pull/98272 and the fix is being worked in https://github.com/dotnet/runtime/pull/98271

**Comment by EgorBo** [comment]
Moving to Future since the problem looks like a corner-case: reproduces only on this new/rarely used API + some intentional misalignment + only on platforms with faulty misaligned loads
