### ISSUE TITLE
ApplicationSettingsBase.Upgrade() throws ArgumentNullException when run under fresh new user in macOS

### ISSUE THREAD

**Issue by snechaev** [dotnet/runtime#98715]
### Description

In my console application I use the old-style `Properties.Settings` concept. For now this implemented with help of the `System.Configuration.ConfigurationManager` nuget package.

When I call `Properties.Settings.Default.Upgrade();` on the newly  created macOS user, I get the `ArgumentNullException` with the following stacktrace
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Directory.GetParent(String path)
   at System.Configuration.LocalFileSettingsProvider.GetPreviousConfigFileName(Boolean isRoaming)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties, Boolean isRoaming)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.ApplicationSettingsBase.Upgrade()
   at Program.<Main>$(String[] args) in /Users/user/testUpgrade/Program.cs:line 15
zsh: abort       
```

### Reproduction Steps

* Download the test project [test.zip](https://github.com/dotnet/runtime/files/14349938/test.zip)
* Publish with `dotnet publish`
* (!) Important: make sure that the following folders do **NOT** exist (they are really do not exist for the fresh newly created user)
  *  `~/.config/`
  * `~/.local/`
* Run the published application directly ((!) do not use `dotnet run`, as it internally create settings folder before actually running the app)
* Observe exception as described above (or, if the mentioned folder still exists, then you will see corresponding note and no crash) 

### Expected behavior

Application finished without exceptions.

### Actual behavior

Unhandled `ArgumentNullException` inside `LocalFileSettingsProvider`

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Directory.GetParent(String path)
   at System.Configuration.LocalFileSettingsProvider.GetPreviousConfigFileName(Boolean isRoaming)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties, Boolean isRoaming)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.ApplicationSettingsBase.Upgrade()
   at Program.<Main>$(String[] args) in /Users/user/testUpgrade/Program.cs:line 15
```

### Regression?

The problem can be reproduced in net6/7.

### Configuration

* net versions I have tried: 6.0.408, 7.0.310, 8.0.101`
* `System.Configuration.ConfigurationManager` package versions: 6.0.1 and 8.0.0
* macOS: 13.6.4 Ventura (x86) and 14.3.1 Sonoma (ARM64/Apple M2)
* Important: tested on newly created macos used, so no one has created settings folders yet. 

### Other information

When the `~/.local/` and `~/.config` folder are missing, the system can't build a path to the settings file, so 
`ConfigurationManager.OpenExeConfiguration(level).FilePath` gives null (or empty string) for the `level = ConfigurationUserLevel.PerUserRoamingAndLocal` and `level = ConfigurationUserLevel. PerUserRoaming`. 

When executing `Upgrade()` the `ConfigurationManagerInternalFactory.Instance.ExeRoamingConfigDirectory` and `ConfigurationManagerInternalFactory.Instance.ExeLocalConfigDirectory` are null here
https://github.com/dotnet/runtime/blob/46870a030cffab0276165af9fddbc0c30f357161/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/LocalFileSettingsProvider.cs#L288-L290

And  then we got exception in `Directory.GetParent(null)` here
https://github.com/dotnet/runtime/blob/46870a030cffab0276165af9fddbc0c30f357161/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/LocalFileSettingsProvider.cs#L302

**Comment by buyaa-n** [comment]
> ### Expected behavior
> 
> Application finished without exceptions.
> 
> ### Other information
> 
> When the `~/.local/` and `~/.config` folder are missing, the system can't build a path to the settings file, so 
> `ConfigurationManager.OpenExeConfiguration(level).FilePath` gives null (or empty string) for the `level = ConfigurationUserLevel.PerUserRoamingAndLocal` and `level = ConfigurationUserLevel. PerUserRoaming`. 

I am not sure if this is expected to work, at least I don't think this is configuration issue. If the settings file were expected to be generated on Mac that is most likely issue in VS Mac issue, then it should be reported there. 

@ericstj @steveharter what you think?

**Comment by snechaev** [comment]
@buyaa-n, just a note: VS Mac is completely unrelated here, it's not even used anywhere in the scenario. The initial code was written on Windows, compiled with `dotnet` cli (on macOS) and launched from the Finder. The problem is not with the dev-environment, it's with application work after deployment to the client machine, where neither dotnet nor VS was installed.

**Comment by ericstj** [comment]
Probably something unrelated during the build process creates `.local` and `.config` directories when you do `dotnet run`.

It sounds like this issue has a workaround - your application can explicitly create those directories.

I do think this is a bug though - we shouldn't be throwing an `ArgumentNullException` from framework code.  This code path tries to deal with a non-existent folder, but it doesn't deal with null.
https://github.com/dotnet/runtime/blob/9d906a2f922c57605ce4c886b8dc675e97d41a40/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/LocalFileSettingsProvider.cs#L302-L304

Seems to me like something went wrong when constructing the paths to leave them with a null value.  I think this location is the place they should be set, and looking at 
https://github.com/dotnet/runtime/blob/7608b3aa906439134e50c32c57b6448d8ffe7893/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs#L162-L165

It uses `GetFolderPath` to obtain the root, which gets called with `SpecialFolderOption.None` https://github.com/dotnet/runtime/blob/e2acec9dfc2df4a067f2d029c65b830a4022ebd7/src/libraries/System.Private.CoreLib/src/System/Environment.cs#L124

Which means, that at this point, it's going to try to try to access and check for read.
https://github.com/dotnet/runtime/blob/e2acec9dfc2df4a067f2d029c65b830a4022ebd7/src/libraries/System.Private.CoreLib/src/System/Environment.GetFolderPathCore.Unix.cs#L28-L46

This will fail because the folder doesn't exist.  That is intentional [per the docs](https://learn.microsoft.com/en-us/dotnet/api/system.environment.specialfolderoption?view=net-8.0):
None | 0 | The path to the folder is verified. If the folder exists, the path is returned. If the folder does not exist, an empty string is returned. This is the default behavior.
-- | -- | --

So I think we either need to change our call to GetFolderPath to not validate -- could be risky as it might change legit error paths, or cause side effects -- or just examine the places that might access these paths and make sure they can handle a null value.

**Comment by snechaev** [comment]
> It sounds like this issue has a workaround - your application can explicitly create those directories.
Yes, my current workaround is as follows.

```
private static void FixMacSettigns()
{
    var homePath = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
    var foldersToCheck = new[] { ".config/", ".local/share/" }.Select(x => Path.Combine(homePath, x));
    foreach (var path in foldersToCheck)
    {
        Directory.CreateDirectory(path);
    }
}
```

The drawbacks are
* you can only hardcode paths. If you will try to get the path from the `ConfigurationManger`, then (in case if paths do not not exist on disk)
   * you will get null
   * the static members of the `ConfigurationManger` will be initialised and even though the workaround will create the missing folders, the `ConfigurationManger` will still fail because the static members are already in the state that reflects the fact that folders are missing.
* I haven't checked the internal logic of how the path of the settings file is built, so if such paths can be different depending on the environment (OS version, permissions, and so on), then such a fix with hardcoded paths will fail.
