### ISSUE TITLE
Test failure Assert.All() Failure: 12 out of 256 items in the collection did not pass

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#98732]
**Failed in:** [runtime-coreclr libraries-jitstress 20240219.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=572369&view=ms.vss-test-web.build-test-results-tab&runId=13716158&resultId=208265&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-CoreCLR_checked-jitstress2_tiered-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
net9.0-windows-Release-x64-CoreCLR_checked-jitstress2_tiered-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
```

**Error message:**
```
Assert.All() Failure: 12 out of 256 items in the collection did not pass.
[3]:  Item:  4
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.151808769
             Actual:   0.153238416
[4]:  Item:  5
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.253379166
             Actual:   0.370503962
[5]:  Item:  6
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.344092488
             Actual:   -0.385987788
[6]:  Item:  7
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.410494238
             Actual:   -0.477760583
[7]:  Item:  8
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.114995345
             Actual:   0.115108378
[8]:  Item:  9
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.307092249
             Actual:   0.334470063
[9]:  Item:  10
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.0431030653
             Actual:   0.0478207767
[10]: Item:  11
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.565155208
             Actual:   -0.611512542
[11]: Item:  12
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.120973401
             Actual:   0.142828137
[12]: Item:  13
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.177610368
             Actual:   -0.228073046
[13]: Item:  14
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.0260503069
             Actual:   -0.0323534235
[14]: Item:  15
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.301667929
             Actual:   0.351612419
```

**Stack trace:**
```
   at System.Numerics.Tensors.Tests.TensorPrimitivesTests`1.CosineSimilarity_AllLengths() in /_/src/libraries/System.Numerics.Tensors/tests/TensorPrimitivesTests.cs:line 738
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by BruceForstall** [comment]
Related or dup: https://github.com/dotnet/runtime/issues/98718

@tannergooding @kunalspathak

**Comment by JulieLeeMSFT** [comment]
It failed again. [Pipelines - Runs for runtime-coreclr libraries-jitstress (azure.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng-public%2Fpublic%2F_build%3FdefinitionId%3D138%26_a%3Dsummary&data=05%7C02%7CJulie.Lee%40microsoft.com%7Cb0407c0a1dc44c1b73fe08dc37b79c63%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638446508956174342%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=WqdQcmoELl28yRTT9x2zMEVL1ztP0%2B5uuQi46leYjNY%3D&reserved=0)

**Comment by JulieLeeMSFT** [comment]
@tannergooding PTAL.

**Comment by v-wenyuxu** [comment]
**Failed in:** runtime-coreclr libraries-jitstress 20240312.1

**Failed tests:**
```
net9.0-windows-Release-x64-CoreCLR_checked-jitstress2_tiered-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
```

**Error message:**
```
 Assert.All() Failure: 12 out of 256 items in the collection did not pass.
[3]:  Item:  4
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.151808769
             Actual:   0.153238416
[4]:  Item:  5
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.253379166
             Actual:   0.370503962
[5]:  Item:  6
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.344092488
             Actual:   -0.385987788
[6]:  Item:  7
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.410494238
             Actual:   -0.477760583
[7]:  Item:  8
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.114995345
             Actual:   0.115108378
[8]:  Item:  9
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.307092249
             Actual:   0.334470063
[9]:  Item:  10
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.0431030653
             Actual:   0.0478207767
[10]: Item:  11
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.565155208
             Actual:   -0.611512542
[11]: Item:  12
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.120973401
             Actual:   0.142828137
[12]: Item:  13
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.177610368
             Actual:   -0.228073046
[13]: Item:  14
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.0260503069
             Actual:   -0.0323534235
[14]: Item:  15
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.301667929
             Actual:   0.351612419
```

**Stack trace:**
```
   at System.Numerics.Tensors.Tests.TensorPrimitivesTests`1.CosineSimilarity_AllLengths() in /_/src/libraries/System.Numerics.Tensors/tests/TensorPrimitivesTests.cs:line 741
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by BruceForstall** [comment]
Still failing:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=607042&view=ms.vss-test-web.build-test-results-tab

@tannergooding

**Comment by kunalspathak** [comment]
Just like https://github.com/dotnet/runtime/issues/98718, this looks more to be a codegen issue.

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20240323.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615632&view=ms.vss-test-web.build-test-results-tab&runId=15040550&resultId=177841&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-jitstress_random_2-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
```

**Error message:**
```
 Assert.All() Failure: 4 out of 256 items in the collection did not pass.
[3]: Item:  4
     Error: Assert.Equal() Failure: Values differ
            Expected: 0.151808769
            Actual:   0.25312683
[4]: Item:  5
     Error: Assert.Equal() Failure: Values differ
            Expected: 0.253379166
            Actual:   0.138663024
[5]: Item:  6
     Error: Assert.Equal() Failure: Values differ
            Expected: -0.344092488
            Actual:   -0.0114496415
[6]: Item:  7
     Error: Assert.Equal() Failure: Values differ
            Expected: -0.410494238
            Actual:   -0.248638168
```

**Stack trace:**
```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240329.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=623575&view=ms.vss-test-web.build-test-results-tab&runId=15274404&resultId=208567&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-jitstress2_tiered-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
```

**Error message:**
```
 Assert.All() Failure: 12 out of 256 items in the collection did not pass.
[3]:  Item:  4
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.151808769
             Actual:   0.153238416
[4]:  Item:  5
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.253379166
             Actual:   0.370503962
[5]:  Item:  6
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.344092488
             Actual:   -0.385987788
[6]:  Item:  7
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.410494238
             Actual:   -0.477760583
[7]:  Item:  8
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.114995345
             Actual:   0.115108378
[8]:  Item:  9
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.307092249
             Actual:   0.334470063
[9]:  Item:  10
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.0431030653
             Actual:   0.0478207767
[10]: Item:  11
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.565155208
             Actual:   -0.611512542
[11]: Item:  12
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.120973401
             Actual:   0.142828137
[12]: Item:  13
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.177610368
             Actual:   -0.228073046
[13]: Item:  14
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.0260503069
             Actual:   -0.0323534235
[14]: Item:  15
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.301667929
             Actual:   0.351612419
```

**Stack trace:**
```
   at System.Numerics.Tensors.Tests.TensorPrimitivesTests`1.CosineSimilarity_AllLengths() in /_/src/libraries/System.Numerics.Tensors/tests/TensorPrimitivesTests.cs:line 740
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240418.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=647704&view=ms.vss-test-web.build-test-results-tab&runId=16001306&resultId=208340&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-jitstress2_tiered-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
```

**Error message:**
```
 Assert.All() Failure: 12 out of 256 items in the collection did not pass.
[3]:  Item:  4
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.151808769
             Actual:   0.153238416
[4]:  Item:  5
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.253379166
             Actual:   0.370503962
[5]:  Item:  6
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.344092488
             Actual:   -0.385987788
[6]:  Item:  7
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.410494238
             Actual:   -0.477760583
[7]:  Item:  8
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.114995345
             Actual:   0.115108378
[8]:  Item:  9
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.307092249
             Actual:   0.334470063
[9]:  Item:  10
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.0431030653
             Actual:   0.0478207767
[10]: Item:  11
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.565155208
             Actual:   -0.611512542
[11]: Item:  12
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.120973401
             Actual:   0.142828137
[12]: Item:  13
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.177610368
             Actual:   -0.228073046
[13]: Item:  14
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.0260503069
             Actual:   -0.0323534235
[14]: Item:  15
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.301667929
             Actual:   0.351612419
```

**Stack trace:**
```
   at System.Numerics.Tensors.Tests.TensorPrimitivesTests`1.CosineSimilarity_AllLengths() in /_/src/libraries/System.Numerics.Tensors/tests/TensorPrimitivesTests.cs:line 740
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by amanasifkhalid** [comment]
@dotnet/jit-contrib any takers?

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240425.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655550&view=ms.vss-test-web.build-test-results-tab&runId=16227726&resultId=207724&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-jitstress2_tiered-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
```

**Error message:**
```
 Assert.All() Failure: 12 out of 256 items in the collection did not pass.
[3]:  Item:  4
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.151808769
             Actual:   0.153238416
[4]:  Item:  5
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.253379166
             Actual:   0.370503962
[5]:  Item:  6
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.344092488
             Actual:   -0.385987788
[6]:  Item:  7
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.410494238
             Actual:   -0.477760583
[7]:  Item:  8
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.114995345
             Actual:   0.115108378
[8]:  Item:  9
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.307092249
             Actual:   0.334470063
[9]:  Item:  10
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.0431030653
             Actual:   0.0478207767
[10]: Item:  11
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.565155208
             Actual:   -0.611512542
[11]: Item:  12
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.120973401
             Actual:   0.142828137
[12]: Item:  13
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.177610368
             Actual:   -0.228073046
[13]: Item:  14
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.0260503069
             Actual:   -0.0323534235
[14]: Item:  15
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.301667929
             Actual:   0.351612419
```

**Stack trace:**
```
   at System.Numerics.Tensors.Tests.TensorPrimitivesTests`1.CosineSimilarity_AllLengths() in /_/src/libraries/System.Numerics.Tensors/tests/TensorPrimitivesTests.cs:line 740
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```
