### ISSUE TITLE
win-x64 SPMI asmdiffs failing

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#98759]
Fails after my PR with this message:
```scala

Traceback (most recent call last):

  File "C:\h\w\AAFC096C\p\superpmi.py", line 5227, in <module>

    sys.exit(main(args))

  File "C:\h\w\AAFC096C\p\superpmi.py", line 5118, in main

    success = asm_diffs.replay_with_asm_diffs()

  File "C:\h\w\AAFC096C\p\superpmi.py", line 2155, in replay_with_asm_diffs

    details = read_csv(detailed_info_file)

  File "C:\h\w\AAFC096C\p\superpmi.py", line 511, in read_csv

    return list(reader)

  File "C:\python3\lib\csv.py", line 111, in __next__

    row = next(self.reader)

  File "C:\python3\lib\encodings\cp1252.py", line 23, in decode

    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5250: character maps to <undefined>


Failed during asmdiffs. Log file: C:\h\w\AAFC096C\w\A1AB090D\uploads\superpmi_asmdiffs_windows_x64.log
```

I'm investigating...

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib
