### ISSUE TITLE
Instrument type parameter could be restricted

### ISSUE THREAD

**Issue by jfheins** [dotnet/runtime#98763]
### Description

I tried to create a Histogram of TimeSpan and got this exception:

```
System.InvalidOperationException: System.TimeSpan is unsupported type for this operation. The only supported types are byte, short, int, long, float, double, and decimal.  
   at System.Diagnostics.Metrics.Instrument.ValidateTypeParameter[T]()
```

### Reproduction Steps

Run code like this:
```
        var meter = meterFactory.Create("dotnet");
        _myMetric = meter.CreateHistogram<TimeSpan>(...)
```

### Expected behavior

The type parameter could be restricted so that TimeSpan creates a _compile_ error.
e.g. `where T : struct, IBinaryNumber<T>`
this does not prevent every misuse, but a few easy ones.

### Actual behavior

Runtime exception

### Regression?

unknown / unlikely

Relevant source file: https://source.dot.net/#System.Diagnostics.DiagnosticSource/System/Diagnostics/Metrics/Instrument.common.cs,15

**Comment by tarekgh** [comment]
We don't produce compile time error but you should be getting a runtime exception when running such code. I think that is good enough as I don't think anyone will write a code without trying or testing it.

```
Unhandled exception. System.InvalidOperationException: System.TimeSpan is unsupported type for this operation. The only supported types are byte, short, int, long, float, double, and decimal.  
   at System.Diagnostics.Metrics.Instrument.ValidateTypeParameter[T]()
   at System.Diagnostics.Metrics.Instrument`1..ctor(Meter meter, String name, String unit, String description, IEnumerable`1 tags)
   at System.Diagnostics.Metrics.Histogram`1..ctor(Meter meter, String name, String unit, String description, IEnumerable`1 tags)
   at System.Diagnostics.Metrics.Meter.<>c__DisplayClass35_0`1.<CreateHistogram>b__0()
   at System.Diagnostics.Metrics.Meter.GetOrCreateInstrument[T](Type instrumentType, String name, String unit, String description, IEnumerable`1 tags, Func`1 instrumentCreator)
   at System.Diagnostics.Metrics.Meter.CreateHistogram[T](String name, String unit, String description, IEnumerable`1 tags)
   at System.Diagnostics.Metrics.Meter.CreateHistogram[T](String name, String unit, String description)
```
