### ISSUE TITLE
[browser][MT] PlatformNotSupportedException Blocking wait is not supported on the JS interop threads

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#98804]
### Error Blob

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "System\.PlatformNotSupportedException ?: Blocking wait is not supported on the JS interop threads",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-98118-merge-d3bb697342374ee0a2/WasmTestOnBrowser-System.Net.Http.Functional.Tests/1/console.7d02ff39.log?helixlogtype=result)
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=574940
```
[22:24:46] info: [FAIL] System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.ReadAsStreamAsync_EmptyResponseBody_HandlerProducesWellBehavedResponseStream
[22:24:46] info: System.PlatformNotSupportedException : Blocking wait is not supported on the JS interop threads.
[22:24:46] info:    at System.Threading.Thread.AssureBlockingPossible()
[22:24:46] info:    at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[22:24:46] info:    at System.Threading.SemaphoreSlim.Wait()
[22:24:46] info:    at System.IO.Stream.BeginReadInternal(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state, Boolean serializeAsynchronously, Boolean apm)
[22:24:46] info:    at System.IO.Stream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
[22:24:46] info:    at System.Threading.Tasks.TaskFactory`1[[System.Int32, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].FromAsyncImpl[Byte[],Int32,Int32](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, Byte[] arg1, Int32 arg2, Int32 arg3, Object state, TaskCreationOptions creationOptions)
[22:24:46] info:    at System.Threading.Tasks.TaskFactory.FromAsync[Byte[],Int32,Int32,Int32](Func`6 beginMethod, Func`2 endMethod, Byte[] arg1, Int32 arg2, Int32 arg3, Object state)
[22:24:46] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<ReadAsStreamAsync_EmptyResponseBody_HandlerProducesWellBehavedResponseStream>b__29_0(Uri uri)
[22:24:46] info:    at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
[22:24:46] info: --- End of stack trace from previous location ---
[22:24:46] info:    at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
[22:24:46] info:    at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass6_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
[22:24:46] info: --- End of stack trace from previous location ---
[22:24:46] info:    at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
[22:24:46] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest.ReadAsStreamAsync_EmptyResponseBody_HandlerProducesWellBehavedResponseStream()
[22:24:46] info: --- End of stack trace from previous location ---
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Provided build not found. Provide a valid build in the "**Build:** :mag_right:" line.
**Validation performed at:** 4/15/2024 7:27:53 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[643881](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643881)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643881&view=ms.vss-test-web.build-test-results-tab&runId=15890716&resultId=186742)|dotnet/runtime#101056|
|[644056](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644056)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644056&view=ms.vss-test-web.build-test-results-tab&runId=15888292&resultId=100604)|dotnet/runtime#101038|
|[643951](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643951)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643951&view=ms.vss-test-web.build-test-results-tab&runId=15886098&resultId=186742)|dotnet/runtime#100765|
|[643885](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643885)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643885&view=ms.vss-test-web.build-test-results-tab&runId=15883368&resultId=100167)|dotnet/runtime#100898|
|[643867](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643867)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643867&view=ms.vss-test-web.build-test-results-tab&runId=15883472&resultId=186785)|dotnet/runtime#100266|
|[643892](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643892)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643892&view=ms.vss-test-web.build-test-results-tab&runId=15883710&resultId=100604)|dotnet/runtime#100949|
|[643833](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643833)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643833&view=ms.vss-test-web.build-test-results-tab&runId=15881900&resultId=100604)|dotnet/runtime#100947|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|7|7|

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by pavelsavara** [comment]
@radekdoulik I opened this to catch all surprising cases where blocking happens.

In this particular case it's
https://github.com/dotnet/runtime/blob/8dcb639fac6a5a19edfad508f61ff27a9bb82da3/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L228

And I wonder why `serializeAsynchronously` is false ?

**Comment by AlitzelMendez** [comment]
Known issues update: This issue has been affected by the issue described in: https://github.com/dotnet/dnceng/issues/2065. Since all the issues opened after 02/20 can cause the build analysis to fail, I will exclude this issue from the build analysis and add a tracking label to restore it as a known issue once this problem is resolved.

**Comment by Jozkee** [comment]
It happened again in https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100898-merge-475198b81218424ca4/WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests/1/console.70c98dfd.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100898-merge-475198b81218424ca4/WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests/1/console.70c98dfd.log?helixlogtype=result)

```
[15:30:18] info: [STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerHttpTest.HttpClient_ContentInDifferentThread(executor1: JSWebWorker, executor2: JSWebWorker)
[15:30:18] warn: [0x07e90040-jsww 15:30:18.437] [MONO] Process terminated.
[15:30:18] warn: [0x07e90040-jsww 15:30:18.440] [MONO] CompleteTask: Unexpected synchronous failure (ManagedThreadId 157): System.PlatformNotSupportedException: Blocking wait is not supported on the JS interop threads.
                    at System.Threading.Thread.AssureBlockingPossible()
                    at System.Threading.ManualResetEventSlim.Wait(Int32 , CancellationToken )
                    at System.Runtime.InteropServices.JavaScript.JavaScriptExports.CompleteTask(JSMarshalerArgument* arguments_buffer)
```

ErrorMessage is different by a whitespace:
```diff
- System.PlatformNotSupportedException : Blocking wait is not supported on the JS interop threads
+ System.PlatformNotSupportedException: Blocking wait is not supported on the JS interop threads
```

**Comment by pavelsavara** [comment]
I'm hoping that https://github.com/dotnet/runtime/pull/101078 fixed it, please re-open if not
