### ISSUE TITLE
[mono] expression Cannot box IsByRefLike type 'System.ReadOnlySpan`1'

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#98805]
### Description

we are using `Spanjson` on ios use interp mode, it will throw exception when use `expression` generate deserialize/serialize code

### Reproduction Steps

our source code:
```c#
internal class SpanJson
	{
		/// <summary>
		/// 一个简单的SpanJson测试用例
		/// </summary>
		[Test("SpanJson.SimpleSample")]
		public static void Run()
		{
			Person person = new Person { Name = "John Doe", Age = 30 };

			//Utf16
			{
				//Generic
				{
					var json = JsonSerializer.Generic.Utf16.Serialize(person);
					var deserializeData = JsonSerializer.Generic.Utf16.Deserialize<Person>(json);
					TestUtility.Check(deserializeData.Name == person.Name && deserializeData.Age == person.Age);
				}

				//NonGeneric
				{
					var json = JsonSerializer.NonGeneric.Utf16.Serialize(person);
					var deserializeData = JsonSerializer.NonGeneric.Utf16.Deserialize(json, typeof(Person)) as Person;
					TestUtility.Check(deserializeData.Name == person.Name && deserializeData.Age == person.Age);
				}
			}

			//Utf8
			{
				//Generic
				{
					var bytes = JsonSerializer.Generic.Utf8.Serialize(person);
					var deserializeData = JsonSerializer.Generic.Utf8.Deserialize<Person>(bytes);
					TestUtility.Check(deserializeData.Name == person.Name && deserializeData.Age == person.Age);
				}

				//NonGeneric
				{
					var bytes = JsonSerializer.NonGeneric.Utf8.Serialize(person);
					var deserializeData = JsonSerializer.NonGeneric.Utf8.Deserialize(bytes, typeof(Person)) as Person;
					TestUtility.Check(deserializeData.Name == person.Name && deserializeData.Age == person.Age);
				}
			}
		}
	}

	[JsonFormatterGenerator]
	public class Person
	{
		public string Name { get; set; }
		public int Age { get; set; }
	}

```

### Expected behavior

walk correctly

### Actual behavior

throw exception, the stacktrace show below:
```
···
Exception Test Name: SpanJson.SimpleSample
Cannot box IsByRefLike type 'System.ReadOnlySpan`1'
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed) in System.Private.CoreLib.dll:token 0x6000258+0x86
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure) in System.Private.CoreLib.dll:token 0x6000256+0x0
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method) in System.Private.CoreLib.dll:token 0x600026d+0x0
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target) in System.Private.CoreLib.dll:token 0x6005d6b+0x11
   at System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(Type delegateType, Func`2 handler) in System.Linq.Expressions.dll:token 0x6001038+0x355
   at System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegate(Type delegateType, Func`2 handler) in System.Linq.Expressions.dll:token 0x600102d+0x2
   at System.Linq.Expressions.Interpreter.LightLambda.MakeDelegate(Type delegateType) in System.Linq.Expressions.dll:token 0x6000c1c+0x31
   at System.Linq.Expressions.Interpreter.LightDelegateCreator.CreateDelegate(IStrongBox[] closure) in System.Linq.Expressions.dll:token 0x6000c19+0x0
   at System.Linq.Expressions.Interpreter.LightDelegateCreator.CreateDelegate() in System.Linq.Expressions.dll:token 0x6000c18+0x0
   at System.Linq.Expressions.Expression`1[[SpanJson.JsonSerializer.NonGeneric.Inner`2.DeserializeDelegate[[System.Char, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SpanJson.Resolvers.ExcludeNullsOriginalCaseResolver`1[[System.Char, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], SpanJson, Version=4.0.1.0, Culture=neutral, PublicKeyToken=12740fa6726bc6d3]], SpanJson, Version=4.0.1.0, Culture=neutral, PublicKeyToken=12740fa6726bc6d3]].Compile() in System.Linq.Expressions.dll:token 0x6000641+0x3
   at SpanJson.JsonSerializer.NonGeneric.Inner`2[[System.Char, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SpanJson.Resolvers.ExcludeNullsOriginalCaseResolver`1[[System.Char, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], SpanJson, Version=4.0.1.0, Culture=neutral, PublicKeyToken=12740fa6726bc6d3]].BuildDeserializer(Type type) in G:\MonoGroup\spanjson\SpanJson\JsonSerializer.NonGeneric.cs:line 233
   at SpanJson.JsonSerializer.NonGeneric.Inner`2[[System.Char, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SpanJson.Resolvers.ExcludeNullsOriginalCaseResolver`1[[System.Char, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], SpanJson, Version=4.0.1.0, Culture=neutral, PublicKeyToken=12740fa6726bc6d3]].BuildInvoker(Type type) in G:\MonoGroup\spanjson\SpanJson\JsonSerializer.NonGeneric.cs:line 160
   at SpanJson.JsonSerializer.NonGeneric.Inner`2.<>c[[System.Char, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SpanJson.Resolvers.ExcludeNullsOriginalCaseResolver`1[[System.Char, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], SpanJson, Version=4.0.1.0, Culture=neutral, PublicKeyToken=12740fa6726bc6d3]].<InnerSerializeToString>b__2_0(Type x) in G:\MonoGroup\spanjson\SpanJson\JsonSerializer.NonGeneric.cs:line 44
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SpanJson.JsonSerializer.NonGeneric.Inner`2.Invoker[[System.Char, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SpanJson.Resolvers.ExcludeNullsOriginalCaseResolver`1[[System.Char, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], SpanJson, Version=4.0.1.0, Culture=neutral, PublicKeyToken=12740fa6726bc6d3]], SpanJson, Version=4.0.1.0, Culture=neutral, PublicKeyToken=12740fa6726bc6d3]].GetOrAdd(Type key, Func`2 valueFactory) in System.Collections.Concurrent.dll:token 0x60000d1+0x47
   at SpanJson.JsonSerializer.NonGeneric.Inner`2[[System.Char, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SpanJson.Resolvers.ExcludeNullsOriginalCaseResolver`1[[System.Char, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], SpanJson, Version=4.0.1.0, Culture=neutral, PublicKeyToken=12740fa6726bc6d3]].InnerSerializeToString(Object input) in G:\MonoGroup\spanjson\SpanJson\JsonSerializer.NonGeneric.cs:line 44
   at SpanJson.JsonSerializer.NonGeneric.Utf16.Serialize[ExcludeNullsOriginalCaseResolver`1](Object input) in G:\MonoGroup\spanjson\SpanJson\JsonSerializer.NonGeneric.cs:line 416
   at SpanJson.JsonSerializer.NonGeneric.Utf16.Serialize(Object input) in G:\MonoGroup\spanjson\SpanJson\JsonSerializer.NonGeneric.cs:line 346
   at UnrealEngine.Game.Tests.SpanJson.SpanJson.Run() in /Users/game-netease/unrealmono/UEDemo-427/UEDemo/Content/Script/Game/Tests/SpanJson/SpanJson.cs:line 27
···
```

### Regression?

we have only try use on .net7, but I think .net8 also have this problem.

### Known Workarounds

no

### Configuration

ios

**Comment by steveisok** [comment]
@srxqds I'd expect the type of exception you're getting to occur under full aot mode. Can you double check that you are indeed using the interpreter?

**Comment by srxqds** [comment]
> @srxqds I'd expect the type of exception you're getting to occur under full aot mode. Can you double check that you are indeed using the interpreter?

yes

**Comment by BrzVlad** [comment]
What is `Spanjson` ? Boxing a byref type doesn't make sense to me.

**Comment by srxqds** [comment]
> What is `Spanjson` ? Boxing a byref type doesn't make sense to me.

the source code you can find here： https://github.com/Tornhoof/SpanJson/blob/3849bc28847e2e3ec6d2474283f512a3315b42ae/SpanJson/JsonSerializer.NonGeneric.cs#L213-L226

it can work on mono execute with jit and coreclr

**Comment by srxqds** [comment]
anyone can help to solve this problem?

**Comment by BrzVlad** [comment]
can you provide a full desktop console project that should fail with interpreter ?

**Comment by srxqds** [comment]
> can you provide a full desktop console project that should fail with interpreter ?
[SpanJsonTest.zip](https://github.com/dotnet/runtime/files/14428829/SpanJsonTest.zip)

**Comment by BrzVlad** [comment]
I'm actually not able to reproduce it on this sample with desktop interpreter. I haven't yet tried to port the code to an ios project.

**Comment by srxqds** [comment]
we are using embed mono in ue, the project is too big to share with you. anyone can help me port the c ode to ios project?

**Comment by AlexeiNaabal** [comment]
> I'm actually not able to reproduce it on this sample with desktop interpreter. I haven't yet tried to port the code to an ios project.

We tested this repro on ios device and reproduced this error, based on the iOS sample on the repo and the SpanJsonTest
The config we use are:

- branch release/7.0
- iOS sample project on the repo, plus the code on the SpanJsonTest
- enable Interp when building the iOS sample project and the later AOT compiling
- disable PublishTrimmed

might need further investigation?

**Comment by AlexeiNaabal** [comment]
We also tested this repro with release/8.0 on iOS device, the runtime did throw exception, though the message is different, but with further check, we believe this exception behavior is consistent with the release/7.0

We added the `/p:MonoForceInterpreter=true \` to the Makefile's `run: clean appbuilder` block, and disable the `<PublishTrimmed>` property, and add the PackageReference of SpanJson by using command line `dotnet add pakcage SpanJson` on the csproj file of the HelloiOS project. The c# code is same as we provided above that with release/7.0.

**Comment by srxqds** [comment]
@BrzVlad  can you take time to look up this problem?

**Comment by srxqds** [comment]
we have 

> We also tested this repro with release/8.0 on iOS device, the runtime did throw exception, though the message is different, but with further check, we believe this exception behavior is consistent with the release/7.0
> 
> We added the `/p:MonoForceInterpreter=true \` to the Makefile's `run: clean appbuilder` block, and disable the `<PublishTrimmed>` property, and add the PackageReference of SpanJson by using command line `dotnet add pakcage SpanJson` on the csproj file of the HelloiOS project. The c# code is same as we provided above that with release/7.0.
> 
> The runtime exception is like:
> 
> ```
> 2024-03-25 09:25:43.736931+0800 HelloiOS[52931:2050639] Unhandled managed exceptions:
> The type initializer for 'Inner`3' threw an exception. (System.TypeInitializationException)
>    at System.Object.lambda_method1(Closure , Object )
>    at SpanJson.JsonSerializer.NonGeneric.Inner`2[[System.Char, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SpanJson.Resolvers.ExcludeNullsOriginalCaseResolver`1[[System.Char, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], SpanJson, Version=4.0.1.0, Culture=neutral, PublicKeyToken=12740fa6726bc6d3]].InnerSerializeToString(Object )
>    at SpanJson.JsonSerializer.NonGeneric.Utf16.Serialize[ExcludeNullsOriginalCaseResolver`1](Object )
>    at SpanJson.JsonSerializer.NonGeneric.Utf16.Serialize(Object )
>    at Program.Main(String[] ) in /Users/{wut}/runtime/src/mono/sample/iOS/Program.cs:line 58
>    at Program.<Main>(String[] )
> ```

hi, @steveisok @BrzVlad  you can reproduce by this step

**Comment by Liangjia0411** [comment]
"In the `v8.0.3` tag, setting the <`PublishTrimmed`> property to `true` in the csproj file results in the `same error`. However, changing this property to `false` `resolves` the issue and the error no longer occurs."

I hope this helps! If you have any more requests or questions, feel free to ask.
> We also tested this repro with release/8.0 on iOS device, the runtime did throw exception, though the message is different, but with further check, we believe this exception behavior is consistent with the release/7.0
> 
> We added the `/p:MonoForceInterpreter=true \` to the Makefile's `run: clean appbuilder` block, and disable the `<PublishTrimmed>` property, and add the PackageReference of SpanJson by using command line `dotnet add pakcage SpanJson` on the csproj file of the HelloiOS project. The c# code is same as we provided above that with release/7.0.
> 
> The runtime exception is like:
> 
> ```
> 2024-03-25 09:25:43.736931+0800 HelloiOS[52931:2050639] Unhandled managed exceptions:
> The type initializer for 'Inner`3' threw an exception. (System.TypeInitializationException)
>    at System.Object.lambda_method1(Closure , Object )
>    at SpanJson.JsonSerializer.NonGeneric.Inner`2[[System.Char, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SpanJson.Resolvers.ExcludeNullsOriginalCaseResolver`1[[System.Char, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], SpanJson, Version=4.0.1.0, Culture=neutral, PublicKeyToken=12740fa6726bc6d3]].InnerSerializeToString(Object )
>    at SpanJson.JsonSerializer.NonGeneric.Utf16.Serialize[ExcludeNullsOriginalCaseResolver`1](Object )
>    at SpanJson.JsonSerializer.NonGeneric.Utf16.Serialize(Object )
>    at Program.Main(String[] ) in /Users/{wut}/runtime/src/mono/sample/iOS/Program.cs:line 58
>    at Program.<Main>(String[] )
> ```

**Comment by BrzVlad** [comment]
Tried again to reproduce, this time on device, but failed. Tried both with the sample steps from recent main branch and with a net9 maui application. `PublishTrimmed` didn't seem to have any effect. Maybe this bug has been fixed since ?

Attaching the maui project I used in an attempt to reproduce. Please update it accordingly if you can get it to crash.

[SpanJsonTest.zip](https://github.com/user-attachments/files/21284378/SpanJsonTest.zip)
