### ISSUE TITLE
[browser][wbt] RunWithDifferentAppBundleLocations

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#98828]
### Error Blob

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "RunWithDifferentAppBundleLocations.*FAIL",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-98802-merge-a7835c7a63484410b6/Workloads-NoWebcil-Wasm.Build.Tests.WasmTemplateTests/1/console.cba58467.log?helixlogtype=result)
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=575939
```
   Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: True, extraProperties: "") [FAIL]
      System.Exception : Timed out waiting for the web server url
      Stack Trace:
        /_/src/mono/wasm/Wasm.Build.Tests/BrowserRunner.cs(82,0): at Wasm.Build.Tests.BrowserRunner.StartServerAndGetUrlAsync(ToolCommand cmd, String args)
        /_/src/mono/wasm/Wasm.Build.Tests/BrowserRunner.cs(112,0): at Wasm.Build.Tests.BrowserRunner.RunAsync(ToolCommand cmd, String args, Boolean headless, Action`1 onConsoleMessage, Action`1 onError, Func`2 modifyBrowserUrl)
        /_/src/mono/wasm/Wasm.Build.Tests/Templates/WasmTemplateTests.cs(292,0): at Wasm.Build.Tests.WasmTemplateTests.BrowserRunTwiceWithAndThenWithoutBuildAsync(String config, String extraProperties, Boolean runOutsideProjectDirectory)
        /_/src/mono/wasm/Wasm.Build.Tests/Templates/WasmTemplateTests.cs(294,0): at Wasm.Build.Tests.WasmTemplateTests.BrowserRunTwiceWithAndThenWithoutBuildAsync(String config, String extraProperties, Boolean runOutsideProjectDirectory)
        /_/src/mono/wasm/Wasm.Build.Tests/Templates/WasmTemplateTests.cs(271,0): at Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(Boolean forConsole, Boolean runOutsideProjectDirectory, String extraProperties)
        --- End of stack trace from previous location ---
```

**Comment by AlitzelMendez** [comment]
Known issues update: This issue has been affected by the issue described in: https://github.com/dotnet/dnceng/issues/2065. Since all the issues opened after 02/20 can cause the build analysis to fail, I will exclude this issue from the build analysis and add a tracking label to restore it as a known issue once this problem is resolved.
