### ISSUE TITLE
Missing TimeProvider implementation for Azure Function .NET Isolated

### ISSUE THREAD

**Issue by kenken023** [dotnet/runtime#98860]
### Description

Good day! We recently upgraded our Azure Functions to .NET 8 Isolated and used the **TimeProvider** in the Dependency Injection but there is an issue. It can't resolve the **System.TimeProvider**.

**.NET Version**
8.0.101

```
[2024-02-23T15:36:18.305Z] Function 'TestFunction', Invocation id '6969ae13-d190-4451-a5b4-858b19300bbb': An exception was thrown by the invocation.
[2024-02-23T15:36:18.307Z] Result: Function 'TestFunction', Invocation id '6969ae13-d190-4451-a5b4-858b19300bbb': An exception was thrown by the invocation.
Exception: System.InvalidOperationException: Unable to resolve service for type 'System.TimeProvider' while attempting to activate 'ChannelServices.Functions.TestFunction'.
[2024-02-23T15:36:18.308Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[2024-02-23T15:36:18.308Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
[2024-02-23T15:36:18.308Z]    at Microsoft.Azure.Functions.Worker.DefaultFunctionActivator.CreateInstance(Type instanceType, FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionActivator.cs:line 23
[2024-02-23T15:36:18.309Z]    at ChannelServices.Functions.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\Fritz.Salar\source\repos\ChannelServices\ChannelServices.Functions\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 95
[2024-02-23T15:36:18.309Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-02-23T15:36:18.310Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 48
[2024-02-23T15:36:18.311Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
Stack:    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[2024-02-23T15:36:18.312Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
[2024-02-23T15:36:18.313Z]    at Microsoft.Azure.Functions.Worker.DefaultFunctionActivator.CreateInstance(Type instanceType, FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionActivator.cs:line 23
[2024-02-23T15:36:18.314Z]    at ChannelServices.Functions.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\Fritz.Salar\source\repos\ChannelServices\ChannelServices.Functions\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 95
[2024-02-23T15:36:18.315Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-02-23T15:36:18.317Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 48
``` 

### Reproduction Steps

1. Create a new Azure Function project
2. Add TimeProvider in the constructor

### Expected behavior

Should be able to resolve `System.TimeProvider`

### Actual behavior

Exception thrown

**Comment by Clockwork-Muse** [comment]
If you only added it as a parameter, `System.TimeProvider` isn't injected as a [default service currently](https://github.com/dotnet/runtime/issues/96717), so you'll need to register it as a dependency as you would normally.

If you did add it as a dependency, please attach a repro project that demonstrates this.
