### ISSUE TITLE
Test failure: baseservices/varargs/varargsupport/varargsupport.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#98911]
**Failed in:** [runtime-coreclr gcstress-extra 20240224.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578457&view=ms.vss-test-web.build-test-results-tab&runId=13881108&resultId=111033&paneView=debug)

**Failed tests:**
```
coreclr linux x64 Checked gcstress0xc_disabler2r_jitstress2 @ Ubuntu.2204.Amd64.Open
    - baseservices/varargs/varargsupport/varargsupport.cmd
```

**Error message:**
```
 
Assert failure(PID 63101 [0x0000f67d], Thread: 63101 [0xf67d]): SanityCheck()
    File: /__w/1/s/src/coreclr/vm/methodtable.cpp:9171
    Image: /datadisks/disk1/work/AB660977/p/corerun

waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/datadisks/disk1/work/AB660977/w/AD2709C8/e/baseservices/baseservices/../varargs/varargsupport/varargsupport.sh: line 441: 63101 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /datadisks/disk1/work/AB660977/w/AD2709C8/uploads/varargs/varargsupport/output.txt
Raw output:
BEGIN EXECUTION
/datadisks/disk1/work/AB660977/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true varargsupport.dll ''
[createdump] Gathering state for process 63101 corerun
[createdump] Crashing thread f67d signal 6 (0006)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.63101.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.63101.dmp
[createdump] Written 69099520 bytes (16870 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 231ms
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 2/24/2024 10:41:04 PM
Processing /home/helixbot/dotnetbuild/dumps/coredump.63101.dmp.crashreport.json
Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/coredump.63101.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Errors while running llvm-symbolizer --pretty-print
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'llvm-symbolizer' with working directory '/datadisks/disk1/work/AB660977/w/AD2709C8/e/baseservices/baseservices'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 499
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 456
   at CoreclrTestLib.CoreclrTestWrapperLib.TryPrintStackTraceFromCrashReport(String crashReportJsonFile, TextWriter outputWriter)
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /datadisks/disk1/work/AB660977/w/AD2709C8/e/baseservices/baseservices/../varargs/varargsupport/varargsupport.sh
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor39|0_40(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```
Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-02-25T07:39:12.18Z | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_disabler2r_jitstress2 | osx.1200.arm64.open | arm64 | baseservices/varargs/varargsupport/varargsupport.cmd | Failed | {"BuildId":"578585","DefinitionId":"141","DefinitionName":"runtime-coreclr crossgen2-composite gcstress","configuration":"Checked-gcstress0xc_disabler2r_jitstress2","AzurePipelinesTestRunId":"13885124","System.PhaseAttempt":"1","System.JobName":"__default","operatingSystem":"OSX.1200.ARM64.Open","System.StageAttempt":"1","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","System.StageName":"Build","Reason":"Schedule","System.JobAttempt":"1","architecture":"arm64","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","Project":"public","BuildNumber":"20240224.1","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2024-02-24T22:40:19.243Z | runtime-coreclr gcstress-extra | Checked-gcstress0xc_disabler2r_jitstress2 | osx.1200.arm64.open | arm64 | baseservices/varargs/varargsupport/varargsupport.cmd | Failed | {"BuildId":"578457","Project":"public","System.StageName":"Build","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","architecture":"arm64","AzurePipelinesTestRunId":"13881256","System.PhaseAttempt":"1","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildNumber":"20240224.1","operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"113","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","configuration":"Checked-gcstress0xc_disabler2r_jitstress2","System.JobAttempt":"1","Reason":"Schedule","System.StageAttempt":"1","DefinitionName":"runtime-coreclr gcstress-extra"} | Schedule

**Comment by BruceForstall** [comment]
@EgorBo This is _probably_ the same issue as https://github.com/dotnet/runtime/issues/98913, so since you assigned yourself that one, I'm assigning this to you.

I wonder if https://github.com/dotnet/runtime/pull/98570 has had an effect on GCStress.

**Comment by mangod9** [comment]
@janvorli as well in case this is related to new exceptions change.

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr gcstress-extra 20240526.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688099&view=ms.vss-test-web.build-test-results-tab&runId=17087792&resultId=100671&paneView=debug)

**Failed tests:**
```
coreclr linux arm Checked gcstress0xc_disabler2r_heapverify1 @ (Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - reflection/SetValue/TrySetReadonlyStaticField/TrySetReadonlyStaticField.cmd
```

**Error message:**
```
 
Assert failure(PID 165 [0x000000a5], Thread: 165 [0x00a5]): SanityCheck()
    File: /__w/1/s/src/coreclr/vm/methodtable.cpp:8544
    Image: /root/helix/work/correlation/corerun

waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/root/helix/work/workitem/e/reflection/reflection/../SetValue/TrySetReadonlyStaticField/TrySetReadonlyStaticField.sh: line 441:   165 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/SetValue/TrySetReadonlyStaticField/output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true TrySetReadonlyStaticField.dll ''
Begin initializing class X
Attempting to update S via SetValue, current value is '0', desired new value is '1'
Updated S to '1'
Attempting to update S via SetValueDirect, current value is '1', desired new value is '2'
Updated S to '2'
Done initializing class X
Attempting to update S via SetValue, current value is '2', desired new value is '3'
Caught expected exception
[createdump] Gathering state for process 165 corerun
[createdump] Crashing thread 00a5 signal 6 (0006)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.165.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.165.dmp
[createdump] Written 71507968 bytes (17458 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 108ms
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 5/26/2024 10:43:56 PM
Processing /home/helixbot/dotnetbuild/dumps/coredump.165.dmp.crashreport.json
Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/coredump.165.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Stack trace:
----------------------------------
Thread Id: 0xa5
      Child SP               IP Call Site
 0xffbeddc0 0xf79b7614 libc.so.6!
 0xffbeddc8 0xf7a219c0 libc.so.6!__wait4_time64
 0xffbede30 0xf78bc984 libcoreclr.so!PROCCreateCrashDump(std::vector<char const*, std::allocator<char const*> >&, char*, int, bool) at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:2308:22
 0xffbede78 0xf78bd784 libcoreclr.so!PROCCreateCrashDumpIfEnabled at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:2526:9
 0xffbedec8 0xf78bae78 libcoreclr.so!PROCAbort at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:2559:5
 (inlined by) RaiseFailFastException at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:1276:14
 0xffbedee0 0xf77a43ac libcoreclr.so!_DbgBreakCheckNoThrow(char const*, int, char const*, int) at /__w/1/s/src/coreclr/utilcode/debug.cpp:300:0
 0xffbedee8 0xf77a4232 libcoreclr.so!SBuffer::~SBuffer() at /__w/1/s/src/coreclr/inc/sbuffer.inl:206:9
 (inlined by) _DbgBreakCheck at /__w/1/s/src/coreclr/utilcode/debug.cpp:293:1
 0xffbeef68 0xf77a4406 libcoreclr.so!_DbgBreakCheckNoThrow(char const*, int, char const*, int) at /__w/1/s/src/coreclr/utilcode/debug.cpp:0:0
 0xffbeefb0 0xf77a4618 libcoreclr.so!DbgAssertDialog at /__w/1/s/src/coreclr/utilcode/debug.cpp:425:22
 0xffbeefd8 0xf753a646 libcoreclr.so!MethodTable::Validate() at /__w/1/s/src/coreclr/vm/methodtable.cpp:0:0
 0xffbef000 0xf753d384 libcoreclr.so!Object::ValidateInner(int, int, int) at /__w/1/s/src/coreclr/vm/object.cpp:553:9
 0xffbef078 0xf7726a38 libcoreclr.so!WKS::GCHeap::Promote(Object**, ScanContext*, unsigned int) at /__w/1/s/src/coreclr/gc/gc.cpp:49013:9
 0xffbef0a8 0xf76c1320 libcoreclr.so!GcInfoDecoder::ReportSlotToGC(GcSlotDecoder&, unsigned int, REGDISPLAY*, bool, unsigned int, void (*)(void*, OBJECTREF*, unsigned int), void*) at /__w/1/s/src/coreclr/inc/gcinfodecoder.h:0:17
 0xffbef0e8 0xf76bff02 libcoreclr.so!
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor13|0_14(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by EgorBo** [comment]
No hits since may, closing
