### ISSUE TITLE
Test failure: GC\\Features\\KeepAlive\\keepaliveother\\keepalivetry\\keepalivetry.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#98916]
**Failed in:** [runtime-coreclr crossgen2 20240224.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578586&view=ms.vss-test-web.build-test-results-tab&runId=13884682&resultId=111995&paneView=debug)

**Failed tests:**
```
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
    - GC\\Features\\KeepAlive\\keepaliveother\\keepalivetry\\keepalivetry.cmd
R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open
    - GC\\Features\\KeepAlive\\keepaliveother\\keepalivetry\\keepalivetry.cmd
R2R-CG2 linux x64 Checked @ Ubuntu.2204.Amd64.Open
    - GC/Features/KeepAlive/keepaliveother/keepalivetry/keepalivetry.sh
R2R-CG2 linux x64 Checked no_tiered_compilation @ Ubuntu.2204.Amd64.Open
    - GC/Features/KeepAlive/keepaliveother/keepalivetry/keepalivetry.sh
R2R-CG2 osx x64 Checked no_tiered_compilation @ OSX.1200.Amd64.Open
    - GC/Features/KeepAlive/keepaliveother/keepalivetry/keepalivetry.sh
R2R-CG2 osx x64 Checked @ OSX.1200.Amd64.Open
    - GC/Features/KeepAlive/keepaliveother/keepalivetry/keepalivetry.sh
```

**Error message:**
```
 Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Test_keepalivetry.Main()

Return code:      1
Raw output file:      C:\h\w\B0B90953\w\ACEA0926\uploads\Reports\GC.Features\KeepAlive\keepaliveother\keepalivetry\keepalivetry.output.txt
Raw output:
BEGIN EXECUTION
keepalivetry.dll
        1 file(s) copied.
 7:24:21.13
Response file: C:\h\w\B0B90953\w\ACEA0926\e\GC\Features\KeepAlive\keepaliveother\keepalivetry\keepalivetry.dll.rsp
C:\h\w\B0B90953\w\ACEA0926\e\GC\Features\KeepAlive\keepaliveother\keepalivetry\IL-CG2\keepalivetry.dll
-o:C:\h\w\B0B90953\w\ACEA0926\e\GC\Features\KeepAlive\keepaliveother\keepalivetry\keepalivetry.dll
--targetarch:x64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
--hot-cold-splitting
-r:C:\h\w\B0B90953\p\System.*.dll
-r:C:\h\w\B0B90953\p\Microsoft.*.dll
-r:C:\h\w\B0B90953\p\xunit.*.dll
-r:C:\h\w\B0B90953\p\mscorlib.dll
-r:C:\h\w\B0B90953\p\netstandard.dll
" "dotnet" "C:\h\w\B0B90953\p\crossgen2\crossgen2.dll" @"C:\h\w\B0B90953\w\ACEA0926\e\GC\Features\KeepAlive\keepaliveother\keepalivetry\keepalivetry.dll.rsp"   -r:C:\h\w\B0B90953\w\ACEA0926\e\GC\Features\KeepAlive\keepaliveother\keepalivetry\IL-CG2\*.dll"
Emitting R2R PE file: C:\h\w\B0B90953\w\ACEA0926\e\GC\Features\KeepAlive\keepaliveother\keepalivetry\keepalivetry.dll
" "dotnet" "C:\h\w\B0B90953\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\B0B90953\w\ACEA0926\e\GC\Features\KeepAlive\keepaliveother\keepalivetry\keepalivetry.dll --out C:\h\w\B0B90953\w\ACEA0926\e\GC\Features\KeepAlive\keepaliveother\keepalivetry\keepalivetry.dll.r2rdump --val"
 7:24:23.97
 "C:\h\w\B0B90953\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  keepalivetry.dll 
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 2/25/2024 7:24:20 AM
Processing C:\cores\corerun.exe.5188.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe -c "$<C:\h\w\B0B90953\t\tmpxc31ca.tmp" -z "C:\cores\corerun.exe.5188.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\cores\corerun.exe.5188.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\B0B90953\p\PDB
Symbol search path is: C:\h\w\B0B90953\p\PDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x64
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Sun Feb 25 07:24:26.000 2024 (UTC + 0:00)
System Uptime: 0 days 0:39:41.953
Process Uptime: 0 days 0:00:03.000
................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(1444.1268): CLR exception - code e0434352 (first/second chance not available)
For analysis of this file, run !analyze -v
ntdll!ZwWaitForMultipleObjects+0x14:
00007ffd`c1a46974 c3              ret
0:000> cdb: Reading initial command '$<C:\h\w\B0B90953\t\tmpxc31ca.tmp'
0:000> .load C:\Users\runner\.dotnet\sos\sos.dll
0:000> ~*k

.  0  Id: 1444.1268 Suspend: 0 Teb: 000000ee`ba54a000 Unfrozen
Child-SP 
```

**Stack trace:**
```
   at GC_Features._KeepAlive_keepaliveother_keepalivetry_keepalivetry_._KeepAlive_keepaliveother_keepalivetry_keepalivetry_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by BruceForstall** [comment]
@mangod9 @janvorli @dotnet/crossgen-contrib Another R2R EH test failure?

**Comment by lambdageek** [comment]
Fixed by https://github.com/dotnet/runtime/pull/99012
