### ISSUE TITLE
Test failure: reflection/DefaultInterfaceMethods/Emit/Emit.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#98973]
**Failed in:** [runtime-coreclr gcstress-extra 20240225.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578854&view=ms.vss-test-web.build-test-results-tab&runId=13893324&resultId=108895&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked gcstress0xc_disabler2r_jitstress2 @ Windows.11.Arm64.Open
    - reflection/DefaultInterfaceMethods/Emit/Emit.cmd
```

**Error message:**
```
 
Assert failure(PID 4248 [0x00001098], Thread: 4664 [0x1238]): m_alignpad == 0

CORECLR! ObjHeader::IllegalAlignPad + 0x7C (0x00007ff9`6bcc1c2c)
CORECLR! WKS::gc_heap::plan_phase + 0x2C84 (0x00007ff9`6bf2922c)
CORECLR! WKS::gc_heap::gc1 + 0x250 (0x00007ff9`6bf189a0)
CORECLR! WKS::gc_heap::garbage_collect + 0x680 (0x00007ff9`6bf18710)
CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x520 (0x00007ff9`6beff388)
CORECLR! WKS::GCHeap::GarbageCollect + 0x1C8 (0x00007ff9`6befedf8)
CORECLR! WKS::GCHeap::StressHeap + 0x794 (0x00007ff9`6bf02614)
CORECLR! MethodDesc::DoPrestub + 0x308 (0x00007ff9`6bc96660)
CORECLR! PreStubWorker + 0x428 (0x00007ff9`6bc9e300)
CORECLR! ThePreStub + 0x50 (0x00007ff9`6bb911f8)
    File: D:_work1ssrccoreclrmsyncblk.cpp:2963
    Image: C:hw9A580924pcorerun.exe


Return code:      1
Raw output file:      C:hw9A580924wB3FA09A5uploadsDefaultInterfaceMethodsEmitoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hw9A580924pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  Emit.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 2/25/2024 10:51:54 PM
Processing C:corescorerun.exe.4248.dmp
Unable to find cdb.exe at C:Program Files (x86)Windows Kits10Debuggersrm64cdb.exe
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> C:hw9A580924wB3FA09A5e
eflection
eflection../DefaultInterfaceMethods/Emit/Emit.cmd
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor1|0_2(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```
Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-02-26T07:48:52.302Z | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_disabler2r_jitstress2 | osx.1200.arm64.open | arm64 | reflection/DefaultInterfaceMethods/Emit/Emit.cmd | Failed | {"System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","AzurePipelinesTestRunId":"13900548","configuration":"Checked-gcstress0xc_disabler2r_jitstress2","DefinitionName":"runtime-coreclr crossgen2-composite gcstress","System.JobName":"__default","Project":"public","Reason":"Schedule","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","System.PhaseAttempt":"1","BuildNumber":"20240225.1","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","System.StageName":"Build","operatingSystem":"OSX.1200.ARM64.Open","architecture":"arm64","BuildId":"579020","DefinitionId":"141"} | Schedule
2024-02-25T22:42:01.132Z | runtime-coreclr gcstress-extra | Checked-gcstress0xc_disabler2r_jitstress2 | osx.1200.arm64.open | arm64 | reflection/DefaultInterfaceMethods/Emit/Emit.cmd | Failed | {"configuration":"Checked-gcstress0xc_disabler2r_jitstress2","System.StageAttempt":"1","System.JobName":"__default","operatingSystem":"OSX.1200.ARM64.Open","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildId":"578854","DefinitionId":"113","DefinitionName":"runtime-coreclr gcstress-extra","System.JobAttempt":"1","Project":"public","Reason":"Schedule","BuildNumber":"20240225.1","System.PhaseName":"run_test_p1__osx_arm64_checked","architecture":"arm64","System.StageName":"Build","AzurePipelinesTestRunId":"13893396"} | Schedule
2024-02-25T07:39:12.18Z | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_disabler2r_jitstress2 | osx.1200.arm64.open | arm64 | reflection/DefaultInterfaceMethods/Emit/Emit.cmd | Failed | {"BuildId":"578585","DefinitionId":"141","DefinitionName":"runtime-coreclr crossgen2-composite gcstress","configuration":"Checked-gcstress0xc_disabler2r_jitstress2","AzurePipelinesTestRunId":"13885124","System.PhaseAttempt":"1","System.JobName":"__default","operatingSystem":"OSX.1200.ARM64.Open","System.StageAttempt":"1","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","System.StageName":"Build","Reason":"Schedule","System.JobAttempt":"1","architecture":"arm64","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","Project":"public","BuildNumber":"20240224.1","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2024-02-24T22:40:19.243Z | runtime-coreclr gcstress-extra | Checked-gcstress0xc_disabler2r_jitstress2 | osx.1200.arm64.open | arm64 | reflection/DefaultInterfaceMethods/Emit/Emit.cmd | Failed | {"BuildId":"578457","Project":"public","System.StageName":"Build","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","architecture":"arm64","AzurePipelinesTestRunId":"13881256","System.PhaseAttempt":"1","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildNumber":"20240224.1","operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"113","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","configuration":"Checked-gcstress0xc_disabler2r_jitstress2","System.JobAttempt":"1","Reason":"Schedule","System.StageAttempt":"1","DefinitionName":"runtime-coreclr gcstress-extra"} | Schedule
2024-02-03T07:21:19.509Z | runtime-coreclr pgostress | Checked-syntheticpgo_blend | ubuntu.2004.armarch.open | arm64 | reflection/DefaultInterfaceMethods/Emit/Emit.cmd | Failed | {"architecture":"arm64","System.JobAttempt":"1","operatingSystem":"(Ubuntu.1804.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8","System.JobName":"__default","configuration":"Checked-syntheticpgo_blend","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.StageName":"Build","Project":"public","System.PhaseName":"run_test_p1__linux_arm64_checked","AzurePipelinesTestRunId":"13130950","DefinitionName":"runtime-coreclr pgostress","BuildId":"552059","System.JobId":"34b2f53b-add1-5e74-7a39-5a11483297fc","System.StageAttempt":"1","DefinitionId":"230","BuildNumber":"20240202.1","Reason":"Schedule"} | Schedule

**Comment by JulieLeeMSFT** [comment]
@kunalspathak, PTAL.

**Comment by BruceForstall** [comment]
Likely the same as https://github.com/dotnet/runtime/issues/98972

**Comment by kunalspathak** [comment]
This seems to be passing lately:

![image](https://github.com/dotnet/runtime/assets/12488060/ff6cd3fb-87d9-41bb-a0b6-17788cab1fb9)
