### ISSUE TITLE
Test failure: IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestHelperMethodsUnrelatedPropertyDoesntHelp

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#98970]
**Failed in:** [runtime-coreclr libraries-jitstress 20240225.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579054&view=ms.vss-test-web.build-test-results-tab&runId=13900488&resultId=107727&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x86-CoreCLR_checked-jitstress2-Windows.10.Amd64.Open
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestHelperMethodsUnrelatedPropertyDoesntHelp
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatementWithOrOperationCase
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestHelperMethodsCanOnlyBeCalledWithAppropriateIsSupportedChecksSuccess
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatementAroundLocalFunctionDefinition
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestHelperMethodsWithHelperProperty
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUnprotectedUseWithIntrinsicsHelperAttribute
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUnprotectedUse
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithTernaryOperator
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatementAroundLambdaFunctionDefinition
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUnprotectedNestedTypeUse
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatementWithNestedAndBaseTypeLookupRequired
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatementButWithInadequateHelperMethodAttribute
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestHelperMethodsCanOnlyBeCalledWithAppropriateIsSupportedChecksError
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatementWithOrOperationCaseWithImplicationProcessingRequired
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUnprotectedUseInLocalFunctionWithIntrinsicsHelperAttributeNotOnLocalFunction
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUseOfIntrinsicsFromWithinOtherMethodOnIntrinsicType
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUnprotectedUseInLambdaWithIntrinsicsHelperAttributeOnOuterFunction
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUnprotectedUseWithIntrinsicsHelperAttributeComplex
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUnprotectedUseInLocalFunctionWithIntrinsicsHelperAttributeOnLocalFunction
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatement
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatementButWithAdequateHelperMethodAttribute
net9.0-windows-Release-x86-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestHelperMethodsUnrelatedPropertyDoesntHelp
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatementWithOrOperationCase
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestHelperMethodsCanOnlyBeCalledWithAppropriateIsSupportedChecksSuccess
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatementAroundLocalFunctionDefinition
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestHelperMethodsWithHelperProperty
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUnprotectedUseWithIntrinsicsHelperAttribute
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUnprotectedUse
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithTernaryOperator
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatementAroundLambdaFunctionDefinition
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUnprotectedNestedTypeUse
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatementWithNestedAndBaseTypeLookupRequired
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatementButWithInadequateHelperMethodAttribute
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestHelperMethodsCanOnlyBeCalledWithAppropriateIsSupportedChecksError
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatementWithOrOperationCaseWithImplicationProcessingRequired
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUnprotectedUseInLocalFunctionWithIntrinsicsHelperAttributeNotOnLocalFunction
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUseOfIntrinsicsFromWithinOtherMethodOnIntrinsicType
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUnprotectedUseInLambdaWithIntrinsicsHelperAttributeOnOuterFunction
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUnprotectedUseWithIntrinsicsHelperAttributeComplex
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodUnprotectedUseInLocalFunctionWithIntrinsicsHelperAttributeOnLocalFunction
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatement
    - IntrinsicsInSystemPrivateCoreLib.Test.IntrinsicsInSystemPrivateCoreLibUnitTest.TestMethodWithIfStatementButWithAdequateHelperMethodAttribute
```

**Error message:**
```
 NuGet.Configuration.NuGetConfigurationException : NuGet.Config is not valid XML. Path: 'C:\Users\runner\AppData\Roaming\NuGet\NuGet.Config'.
---- System.Xml.XmlException : Root element is missing.
```

**Stack trace:**
```
   at NuGet.Configuration.SettingsFile.<>c__DisplayClass32_0.<ExecuteSynchronized>b__0()
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLocked(String filePath, Action action)
   at NuGet.Configuration.SettingsFile.ExecuteSynchronized(Action ioOperation)
   at NuGet.Configuration.SettingsFile..ctor(String directoryPath, String fileName, Boolean isMachineWide, Boolean isReadOnly)
   at NuGet.Configuration.Settings.ReadSettings(String settingsRoot, String settingsPath, Boolean isMachineWideSettings, Boolean isAdditionalUserWideConfig, SettingsLoadingContext settingsLoadingContext)
   at NuGet.Configuration.Settings.LoadUserSpecificSettings(String root, String configFileName, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)+MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection) in /_/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs:line 269
   at NuGet.Configuration.Settings.LoadSettingsForSpecificConfigs(String root, String configFileName, List`1 validSettingFiles, IMachineWideSettings machineWideSettings, Boolean loadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
   at NuGet.Configuration.Settings.LoadSettings(String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean loadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
   at NuGet.Configuration.Settings.LoadDefaultSettings(String root)
   at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveCoreAsync(String language, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs:line 210
   at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveAsync(String language, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs:line 197
   at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveAsync(String language, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs:line 174
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.CreateSolutionAsync(ProjectId projectId, EvaluatedProjectState projectState, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 1601
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.CreateProjectImplAsync(EvaluatedProjectState primaryProject, ImmutableArray`1 additionalProjects, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 1416
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.CreateProjectAsync(EvaluatedProjectState primaryProject, ImmutableArray`1 additionalProjects, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 1395
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.GetSolutionAsync(EvaluatedProjectState primaryProject, ImmutableArray`1 additionalProjects, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 1373
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.GetSortedDiagnosticsAsync(EvaluatedProjectState primaryProject, ImmutableArray`1 additionalProjects, ImmutableArray`1 analyzers, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 1097
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.VerifyDiagnosticsAsync(EvaluatedProjectState primaryProject, ImmutableArray`1 additionalProjects, DiagnosticResult[] expected, IVerifier verifier, CancellationToken cancellationToken) in /_/sr
```

**Comment by BruceForstall** [comment]
This looks like a test infra issue that didn't happen in the run that followed (https://dev.azure.com/dnceng-public/public/_build/results?buildId=580562&view=ms.vss-test-web.build-test-results-tab).
