### ISSUE TITLE
Test failure: Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#99090]
**Failed in:** [runtime-coreclr r2r-extra 20240227.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=581938&view=ms.vss-test-web.build-test-results-tab&runId=13990156&resultId=109835&paneView=debug)

**Failed tests:**
```
R2R-CG2 osx arm64 Checked jitstressregs8 @ OSX.1200.ARM64.Open
    - Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd
```

**Error message:**
```
 /private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Interop/../Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.sh: line 315: -r:/private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/IL-CG2/*.dll: No such file or directory

Assert failure(PID 74204 [0x000121dc], Thread: 3110877 [0x2f77dd]): Assertion failed 'this->OperIsBinary()' in '(dynamicClass):IL_STUB_PInvoke(int,byref):long' during 'LSRA allocate' (IL size 42; hash 0xcfebd874; FullOpts)

    File: /Users/runner/work/1/s/src/coreclr/jit/gentree.cpp:6878
    Image: /private/tmp/helix/working/BA6D09D5/p/corerun

waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Interop/../Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.sh: line 432: 74204 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/BA6D09D5/w/AEB5097D/uploads/Swift/SwiftErrorHandling/SwiftErrorHandling/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/IL-CG2/SwiftErrorHandling.dll
17:01:06
Response file: /private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.dll.rsp
/private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/IL-CG2/SwiftErrorHandling.dll
-o:/private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.dll
-r:/tmp/helix/working/BA6D09D5/p/System.*.dll
-r:/tmp/helix/working/BA6D09D5/p/Microsoft.*.dll
-r:/tmp/helix/working/BA6D09D5/p/xunit.*.dll
-r:/tmp/helix/working/BA6D09D5/p/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm64
--targetos:osx
Running CrossGen2:  dotnet /tmp/helix/working/BA6D09D5/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.dll.rsp  
Emitting R2R PE file: /private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.dll
Running R2RDump:  dotnet /tmp/helix/working/BA6D09D5/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.dll --out /private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.dll.r2rdump --val
17:01:06
/private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/IL-CG2/TestLibrary.dll
17:01:06
Response file: /private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/TestLibrary.dll.rsp
/private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/IL-CG2/TestLibrary.dll
-o:/private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/TestLibrary.dll
-r:/tmp/helix/working/BA6D09D5/p/System.*.dll
-r:/tmp/helix/working/BA6D09D5/p/Microsoft.*.dll
-r:/tmp/helix/working/BA6D09D5/p/xunit.*.dll
-r:/tmp/helix/working/BA6D09D5/p/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm64
--targetos:osx
Running CrossGen2:  dotnet /tmp/helix/working/BA6D09D5/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/TestLibrary.dll.rsp  
Emitting R2R PE file: /private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/TestLibrary.dll
Running R2RDump:  dotnet /tmp/helix/working/BA6D09D5/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/BA6D09D5/w/AEB5097D/e/Interop/Swift/SwiftErrorHandling/SwiftErr
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor274|25_275(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```

**Comment by jakobbotsch** [comment]
cc @amanasifkhalid
