### ISSUE TITLE
[9.0-preview.1] Test process crash on Windows in Release mode with task throwing an exception

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#99187]
### Description

Testing our Polly build with .NET 9 preview 1, we have a single test case in our test suite that is failing on Windows in Release mode. Linux and macOS appear to be unaffected, as is Debug mode on Windows.

dotnet test fails with the following error:

```
[xUnit.net 00:00:00.25]   Starting:    Polly.Core.Tests
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Polly.Core.Tests.Utils.StrategyHelperTests.<>c__DisplayClass1_0.<<ExecuteCallbackSafeAsync_CallbackThrows_EnsureExceptionWrapped>b__1>d.MoveNext() in C:\Coding\App-vNext\Polly\test\Polly.Core.Tests\Utils\StrategyHelperTests.cs:line 35
--- End of stack trace from previous location ---
   at Polly.Utils.StrategyHelper.<ExecuteCallbackSafeAsync>g__AwaitTask|0_0[TResult,TState,T](ValueTask`1 task, Boolean continueOnCapturedContext) in C:\Coding\App-vNext\Polly\src\Polly.Core\Utils\StrategyHelper.cs:line 36
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

The exception is _technically_ expected, because [our test](https://github.com/App-vNext/Polly/blob/8c2041d183dc510c194a21f9aea90ca6af1b7a05/test/Polly.Core.Tests/Utils/StrategyHelperTests.cs#L21-L41) is verifying that [we catch an exception and wrap it in an object](https://github.com/App-vNext/Polly/blob/8c2041d183dc510c194a21f9aea90ca6af1b7a05/src/Polly.Core/Utils/StrategyHelper.cs#L17-L42). This is failing to occur though, and the exception is not being caught and terminating the process.

The test has two variants which pass either `true` or `false` to control whether the lambda method we throw the exception from performs an await.

The variant which fails is the one where the method [calls `await Task.Delay(15)`](https://github.com/App-vNext/Polly/blob/8c2041d183dc510c194a21f9aea90ca6af1b7a05/test/Polly.Core.Tests/Utils/StrategyHelperTests.cs#L30-L33) before throwing the exception.

### Reproduction Steps

- Clone https://github.com/App-vNext/Polly/pull/2003/commits/c27d8dbc4a5e32a182da13c9281679334891ffd7 on Windows
- Either:
  - Change to the `Polly\test\Polly.Core.Tests` directory
  - Run `dotnet test --configuration Release`
- Or:
  - Open the solution in Visual Studio
  - Ensure Release mode is selected
  - Run the `ExecuteCallbackSafeAsync_CallbackThrows_EnsureExceptionWrapped` test with the input of `true`

### Expected behavior

The tests pass.

### Actual behavior

The `net9.0` tests fail with the following error from `dotnet test`:

```text
Polly.Core.Tests net9.0 failed with errors (13.2s)
  C:\Program Files\dotnet\sdk\9.0.100-preview.1.24101.2\Microsoft.TestPlatform.targets(41,5): error MSB6006: "dotnet.exe" exited with code 1. [C:\Coding\App-vNext\Polly\test\Polly.Core.Tests\Polly.Core.Tests.csproj]
```

The same tests pass:

- in Release mode for `net9.0` on Linux and macOS
- in Debug mode for `net9.0` on Windows
- in Release mode for `net8.0` for Linux, macOS and Windows
- in Debug mode for `net8.0` for Windows

I've not tested non-Release for non-Windows builds of either as I'm just relying on our GitHub Actions CI for Linux and macOS, and I only have access to a Windows machine locally.

### Regression?

Compared to `net8.0`, yes.

### Known Workarounds

None.

### Configuration

- Windows 11 Version 22H2 (OS Build 22621.3155) and `windows-latest` GitHub Actions hosted runner
- .NET SDK `9.0.100-preview.1.24101.2`

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/71569 ?

**Comment by martincostello** [comment]
Seems similar, though we haven't seen the issue with the latest .NET 8 SDK (8.0.201) which also has that bug if I understand correctly?

**Comment by martincostello** [comment]
Still observing this with preview 2.

**Comment by martincostello** [comment]
I can't replicate this with preview 3.
