### ISSUE TITLE
Test failure: Assertion failed 'Cloning of node not supported' in '(dynamicClass):IL_STUB_PInvoke(int,byref):long' during 'Morph - Global'

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#99214]
**Failed in:** [runtime-coreclr jitstress-random 20240303.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=587102&view=ms.vss-test-web.build-test-results-tab&runId=14151326&resultId=117708&paneView=debug)

**Failed tests:**
```
coreclr osx x64 Checked jitstress_random_2 @ OSX.1200.Amd64.Open
    - Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd
coreclr osx arm64 Checked jitstress_random_1 @ OSX.1200.ARM64.Open
    - Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd
coreclr osx arm64 Checked jitstress_random_2 @ OSX.1200.ARM64.Open
    - Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd
```

**Error message:**
```
 
Assert failure(PID 84637 [0x00014a9d], Thread: 3101368 [0x2f52b8]): Assertion failed 'Cloning of node not supported' in '(dynamicClass):IL_STUB_PInvoke(int,byref):long' during 'Morph - Global' (IL size 43; hash 0xcfebd874; FullOpts)

    File: /Users/runner/work/1/s/src/coreclr/jit/gentree.cpp:9442
    Image: /private/tmp/helix/working/AC160975/p/corerun

waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/private/tmp/helix/working/AC160975/w/AFB909DD/e/Interop/Interop/../Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.sh: line 441: 84637 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/AC160975/w/AFB909DD/uploads/Swift/SwiftErrorHandling/SwiftErrorHandling/output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/AC160975/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true SwiftErrorHandling.dll ''
[createdump] Gathering state for process 84637 
[createdump] Crashing thread 2f52b8 signal 6 (0006)
[createdump] Writing crash report to file /cores/coredump.84637.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /cores/coredump.84637.dmp
[createdump] Written 356933768 bytes (87142 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 2563ms
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /cores since 3/3/2024 2:43:34 PM
Processing /cores/coredump.84637.dmp.crashreport.json
Printing stacktrace from '/cores/coredump.84637.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Errors while running llvm-symbolizer --pretty-print
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'llvm-symbolizer' with working directory '/private/tmp/helix/working/AC160975/w/AFB909DD/e/Interop/Interop'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 499
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 456
   at System.Diagnostics.Process.Start() in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1282
   at CoreclrTestLib.CoreclrTestWrapperLib.TryPrintStackTraceFromCrashReport(String crashReportJsonFile, TextWriter outputWriter)
Finish looking for *.crashreport.json. No new files created.
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /private/tmp/helix/working/AC160975/w/AFB909DD/e/Interop/Interop/../Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.sh
```

**Stack trace:**
```
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor274|25_275(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```
Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-03-03T19:43:11.767Z | runtime-coreclr jitstress-random | Checked-jitstress_random_2 | osx.1200.arm64.open | arm64 | Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd | Failed | {"DefinitionId":"159","CollectionUri":"https://dev.azure.com/dnceng-public/","configuration":"Checked-jitstress_random_2","System.PhaseAttempt":"1","operatingSystem":"OSX.1200.ARM64.Open","BuildId":"587102","BuildNumber":"20240303.1","Reason":"Schedule","architecture":"arm64","DefinitionName":"runtime-coreclr jitstress-random","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.StageAttempt":"1","System.PhaseName":"run_test_p1__osx_arm64_checked","System.StageName":"Build","Project":"public","System.JobName":"__default","AzurePipelinesTestRunId":"14151334","System.JobAttempt":"1"} | Schedule
2024-03-03T19:43:10.398Z | runtime-coreclr jitstress-random | Checked-jitstress_random_1 | osx.1200.arm64.open | arm64 | Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd | Failed | {"Reason":"Schedule","BuildId":"587102","AzurePipelinesTestRunId":"14151332","System.PhaseAttempt":"1","DefinitionId":"159","BuildNumber":"20240303.1","DefinitionName":"runtime-coreclr jitstress-random","System.JobName":"__default","System.JobAttempt":"1","configuration":"Checked-jitstress_random_1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__osx_arm64_checked","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","operatingSystem":"OSX.1200.ARM64.Open","System.StageName":"Build","Project":"public","architecture":"arm64","System.StageAttempt":"1"} | Schedule
2024-03-03T19:42:10.342Z | runtime-coreclr jitstress-random | Checked-jitstress_random_2 | osx.1200.amd64.open | x64 | Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd | Failed | {"operatingSystem":"OSX.1200.Amd64.Open","Project":"public","AzurePipelinesTestRunId":"14151326","Reason":"Schedule","architecture":"x64","System.PhaseAttempt":"1","System.StageAttempt":"1","System.JobAttempt":"1","DefinitionId":"159","DefinitionName":"runtime-coreclr jitstress-random","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.StageName":"Build","System.JobName":"__default","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20240303.1","System.PhaseName":"run_test_p1__osx_x64_checked","configuration":"Checked-jitstress_random_2","BuildId":"587102"} | Schedule
2024-03-03T18:39:52.965Z | runtime-coreclr jitstress2-jitstressregs | Checked-jitstress2_jitstressregs8 | osx.1200.amd64.open | x64 | Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd | Failed | {"System.StageAttempt":"1","operatingSystem":"OSX.1200.Amd64.Open","System.JobName":"__default","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","Project":"public","DefinitionName":"runtime-coreclr jitstress2-jitstressregs","System.StageName":"Build","BuildId":"587093","architecture":"x64","System.JobAttempt":"1","DefinitionId":"111","AzurePipelinesTestRunId":"14150824","Reason":"Schedule","System.PhaseAttempt":"1","System.PhaseName":"run_test_p1__osx_x64_checked","BuildNumber":"20240303.1","CollectionUri":"https://dev.azure.com/dnceng-public/","configuration":"Checked-jitstress2_jitstressregs8"} | Schedule
2024-03-03T18:39:45.215Z | runtime-coreclr jitstress2-jitstressregs | Checked-jitstress2_jitstressregs1 | osx.1200.amd64.open | x64 | Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd | Failed | {"Project":"public","BuildId":"587093","BuildNumber":"20240303.1","architecture":"x64","System.JobAttempt":"1","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","operatingSystem":"OSX.1200.Amd64.Open","AzurePipelinesTestRunId":"14150808","System.JobName":"__default","System.StageAttempt":"1","Reason":"Schedule","System.PhaseName":"run_test_p1__osx_x64_checked","System.PhaseAttempt":"1","System.StageName":"Build","configuration":"Checked-jitstress2_jitstressregs1","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionName":"runtime-coreclr jitstress2-jitstressregs","DefinitionId":"111"} | Schedule
2024-03-03T11:44:00.724Z | runtime-coreclr jitstressregs | Checked-jitstressregs8 | osx.1200.amd64.open | x64 | Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd | Failed | {"DefinitionName":"runtime-coreclr jitstressregs","System.StageAttempt":"1","System.PhaseAttempt":"1","System.JobName":"__default","System.StageName":"Build","AzurePipelinesTestRunId":"14144184","DefinitionId":"110","architecture":"x64","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","configuration":"Checked-jitstressregs8","Project":"public","System.JobAttempt":"1","operatingSystem":"OSX.1200.Amd64.Open","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__osx_x64_checked","BuildNumber":"20240303.1","BuildId":"586909","Reason":"Schedule"} | Schedule
2024-03-03T11:43:56.505Z | runtime-coreclr jitstressregs | Checked-jitstressregs1 | osx.1200.amd64.open | x64 | Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd | Failed | {"BuildId":"586909","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","DefinitionName":"runtime-coreclr jitstressregs","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Checked-jitstressregs1","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.JobAttempt":"1","System.StageAttempt":"1","BuildNumber":"20240303.1","DefinitionId":"110","System.StageName":"Build","Project":"public","Reason":"Schedule","AzurePipelinesTestRunId":"14144158","System.PhaseName":"run_test_p1__osx_x64_checked","operatingSystem":"OSX.1200.Amd64.Open"} | Schedule

**Comment by jakobbotsch** [comment]
cc @amanasifkhalid
