### ISSUE TITLE
Assert in CounterGroup.OnEventSourceCommand after trying to run BDN x86

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#99497]
I've tried to run BenchmarkDotNet in x86 (which failed unless I used `InProcessEmitToolchain`) and after that I've noticed that checked CoreLib is now hitting an assert here:
https://github.com/dotnet/runtime/blob/8bd4f6fe252395455969c7b3e76f40b36764c4a9/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs#L50

Seems like BDN somehow corrupt my current PC boot, still, this probably shouldn't assert in .NET when BDN isn't even running anymore.

Stacktrace:
```cs
Process terminated. Assertion failed.
   at System.Diagnostics.Tracing.CounterGroup.OnEventSourceCommand(Object sender, EventCommandEventArgs e)
   at System.Diagnostics.Tracing.EventSource.add_EventCommandExecuted(EventHandler`1 value)
   at System.Diagnostics.Tracing.CounterGroup.GetCounterGroup(EventSource eventSource)
   at System.Diagnostics.Tracing.DiagnosticCounter.Publish()
   at System.Diagnostics.Tracing.RuntimeEventSource.OnEventCommand(EventCommandEventArgs command)
   at System.Diagnostics.Tracing.EventSource.DoCommand(EventCommandEventArgs commandArgs)
   at System.Diagnostics.Tracing.EventSource.Initialize(Guid eventSourceGuid, String eventSourceName, String[] traits)
   at System.Diagnostics.Tracing.RuntimeEventSource..ctor()
   at System.Diagnostics.Tracing.RuntimeEventSource.Initialize()
   at System.StartupHookProvider.ManagedStartup(Char* pDiagnosticStartupHooks)
```

**Comment by mdh1418** [comment]
Hi Michal, this seems related to https://github.com/dotnet/runtime/issues/94964 and https://github.com/dotnet/runtime/issues/96324, both of which seemed to have resolved after the issue authors had restarted their machines. Are you able to reproduce the assert failure reliably in a sample project that you'd be comfortable sharing?

Could you also share the dotnet version you're using along with your machine's specifications?
