### ISSUE TITLE
Using TypeBuilder as a generic typa parameter throws NotSupportedException in AssemblyBuilder created by DefinePersistedAssembly

### ISSUE THREAD

**Issue by mateuszradny** [dotnet/runtime#99505]
### Description

Creating types which use dynamically create types as generic types parameters throws exceptions as below:

`
System.NotSupportedException: Specified method is not supported.
   at System.Reflection.Emit.TypeBuilderInstantiation.GetConstructorImpl(BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers)
   at System.Reflection.Emit.TypeBuilderImpl.DefineDefaultConstructorInternal(MethodAttributes attributes)
   at System.Reflection.Emit.TypeBuilderImpl.CreateTypeInfoCore()
   at Handyflows.Core.Customization.Snapshots.DummyCustomizationSnapshotProvider..ctor()
`

### Reproduction Steps

```csharp

public class BasTypee<T> { }



```

### Expected behavior

```csharp
public class BaseType<T> { }

// code
var assemblyBuilder = AssemblyBuilder.DefinePersistedAssembly(new AssemblyName("test"), typeof(object).Assembly);
var module = assemblyBuilder.DefineDynamicModule("test");
var typeBuilder = module
    .DefineType("test.Test", TypeAttributes.Public | TypeAttributes.Class);

var type = typeBuilder.CreateType();
var baseType = typeof(BaseType<>).GetGenericTypeDefinition().MakeGenericType(type);

var typeBuilder2 = module
    .DefineType("TestService",
    TypeAttributes.Public | TypeAttributes.Class,
    baseType 
    );

typeBuilder2.CreateType(); // exception
```

### Actual behavior

The same code for `DefineDynamicAssembly` works fine, but problem exists only for `DefinePersistedAssembly`.

**Comment by buyaa-n** [comment]
> I see that PR was merged. Can I somehow test it

You might be able to use daily build mentioned in https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md, though looks all info in the doc are outdated (for .NET 8.0), but the instructions/links most likely work if you just change the 8.0 into 9.0, for example the link for daily build for Windows (x64) is `https://aka.ms/dotnet/8.0/daily/dotnet-runtime-win-x64.exe` updating the link with 9.0 works for me `https://aka.ms/dotnet/9.0/daily/dotnet-runtime-win-x64.exe`

**Comment by mateuszradny** [comment]
After installing a daily version of SDK the problem still exists, should I do something else?

**Comment by buyaa-n** [comment]
SDK [has](https://aka.ms/dotnet/9.0.1xx/daily/productCommit-win-x64.txt) old bits, should try out runtime bits https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md#daily-builds-table

**Comment by mateuszradny** [comment]
This link contains 8.0.4 version 
![image](https://github.com/dotnet/runtime/assets/11389995/4e3068ee-5f55-443a-a8bf-010fa94ad08d)
not 9.0.0-preview.*

**Comment by buyaa-n** [comment]
Yes, as mentioned earlier the page is not up to date, change the `8.0` part in the link with `9.0`, for example the link for daily build for Windows (x64) is https://aka.ms/dotnet/8.0/daily/dotnet-runtime-win-x64.exe updating the link with 9.0 works for me https://aka.ms/dotnet/9.0/daily/dotnet-runtime-win-x64.exe

**Comment by mateuszradny** [comment]
I installed SDK from this link: https://aka.ms/dotnet/9.0/daily/dotnet-runtime-win-x64.exe but still the code from my first post doesn't work.

**Comment by buyaa-n** [comment]
I guess your build still uses the old runtime, did you see error on `AssemblyBuilder.DefinePersistedAssembly(.. )`? If you are using new bits this method is removed and should see error and would need to use `PersistedAssemblyBuilder` constructor instead:
`var assemblyBuilder = new PersistedAssemblyBuilder(new AssemblyName("test"), typeof(object).Assembly);`

I don't know how to force the build use newly installed runtime, maybe need to wait until the bits shipped with SDK

**Comment by mateuszradny** [comment]
It's required to set 
`<RuntimeFrameworkVersion>9.0.0-preview.4.24171.3</RuntimeFrameworkVersion>`
If you want to to force specified preview version.

Is somewhere daily builds to download for `Microsoft.NET.Sdk.Web`?

**Comment by buyaa-n** [comment]
Now SDK daily build updated, you can use the installer directly https://github.com/dotnet/installer?tab=readme-ov-file#installers-and-binaries

**Comment by mateuszradny** [comment]
Now it works correctly, thanks for your contributions :)

**Comment by buyaa-n** [comment]
Thank you for reporting :)
