### ISSUE TITLE
Assertion failed in SafeFileHandle.OverlappedValueTaskSource.IOCallback

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#99517]
In System.IO.FileSystem tests

```
Process terminated. Assertion failed.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.IOCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOverlapped) in /_/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.OverlappedValueTaskSource.Windows.cs:line 193
   at System.Threading.ThreadPoolTypedWorkItemQueue`2.System.Threading.IThreadPoolWorkItem.Execute() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 1128
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 913
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.NonBrowser.cs:line 102
----- end Mon 03/11/2024  7:15:25.24 ----- exit code -2146232797 ----------------------------------------------------------
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=597206
Build error leg or test failing: System.IO.FileSystem.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/99513

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "at Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.IOCallback",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by stephentoub** [comment]
> at Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.IOCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOverlapped) in /_/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.OverlappedValueTaskSource.Windows.cs:line 193

`Debug.Assert(numBytes < int.MaxValue);` in the IO callback is an interesting assert to be failing.

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0
