### ISSUE TITLE
Test Crash: Microsoft.CodeAnalysis.VisualBasic.UnitTests.AsyncTests.Imported_AsyncWithEH

### ISSUE THREAD

**Issue by 333fred** [dotnet/runtime#99623]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=599758&view=ms.vss-test-web.build-test-results-tab&runId=14541768&resultId=188622&paneView=debug
https://github.com/dotnet/roslyn/pull/72499/checks?check_run_id=22567221018

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.NotifySynchronizationContextOfCompletion()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Results File: C:\h\w\B1C0098E\w\AAFB0938\e\WorkItem_20_x64_test_results.xml

The active Test Run was aborted because the host process exited unexpectedly. Please inspect the call stack above, if available, to get more information about where the exception originated from.
The test running when the crash occurred: 
Microsoft.CodeAnalysis.VisualBasic.UnitTests.AsyncTests.Imported_AsyncWithEH
```

Dump (MSFT Internal only): https://microsoft-my.sharepoint.com/:u:/p/frsilb/ESIbrjR9gkpHp47XxFPO_7IBSBDDfNLSlDmLQ_YWX5Y1eg?e=hskNn4

**Comment by jaredpar** [comment]
Transfering to runtime as this appears to be a crash in `AsyncVoidMethodBuilder` using `net8.0` runtime. The crash dump is throwing an NRE here: 

```csharp
        private void NotifySynchronizationContextOfCompletion()
        {
            Debug.Assert(_synchronizationContext != null, "Must only be used with a non-null context.");
            try
            {
                _synchronizationContext.OperationCompleted(); // NRE HERE
            }
            catch (Exception exc)
```

Locals aren't available (optimized code) but seems likely that `_synchronizationContext` is `null` here.

**Comment by reflectronic** [comment]
Is this the same as https://github.com/dotnet/runtime/pull/99461?

**Comment by jaredpar** [comment]
It does indeed look like a dupe of that issue

**Comment by ericstj** [comment]
Resolving as I agree with @reflectronic and @jaredpar that this appears to be a dup of https://github.com/dotnet/runtime/issues/99452 https://github.com/dotnet/runtime/issues/93969 https://github.com/dotnet/runtime/issues/40463, fixed in #99461 cc @stephentoub
