### ISSUE TITLE
Test failure: System.DirectoryServices.Protocols.Tests.BerConverterTests.Decode_Bytes_ReturnsExpected

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#99738]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=602282
Build error leg or test failing: System.DirectoryServices.Protocols.Tests.BerConverterTests.Decode_Bytes_ReturnsExpected

## Error Message

```json
{
  "ErrorMessage" : "BerConverterTests.cs(200,0): at System.DirectoryServices.Protocols.Tests.BerConverterTests.Decode_Bytes_ReturnsExpected",
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/99713
- Queues:
  - `windows-x86 Release Libraries_NET48`
  - `Test Run release coreclr windows x86 Release`
  - `Test Run checked coreclr windows x86 Debug`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=602282&view=logs&j=885df564-30f3-5dad-0bdc-caf444244bdf&t=71aa97be-149e-50ab-5d1c-74d5540a091f&l=51
- Log file: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-99713-merge-6373e45618364ea687/System.DirectoryServices.Protocols.Tests/1/console.a47db42e.log?helixlogtype=result
- Output:
```
    System.DirectoryServices.Protocols.Tests.BerConverterTests.Decode_Bytes_ReturnsExpected(format: "vv", values: [48, 132, 0, 0, 0, ···], expected: [["abc", ""], null]) [FAIL]
      Assert.Equal() Failure: Collections differ
                 ↓ (pos 0)
      Expected: [["abc", ""], null]
      Actual:   [["abc", "", ""], null]
                 ↑ (pos 0)
      Stack Trace:
        /_/src/libraries/System.DirectoryServices.Protocols/tests/BerConverterTests.cs(200,0): at System.DirectoryServices.Protocols.Tests.BerConverterTests.Decode_Bytes_ReturnsExpected(String format, Byte[] values, Object[] expected)
    System.DirectoryServices.Protocols.Tests.BerConverterTests.Decode_Bytes_ReturnsExpected(format: "VV", values: [48, 132, 0, 0, 0, ···], expected: [[[···], [···]], null]) [FAIL]
      Assert.Equal() Failure: Collections differ
                 ↓ (pos 0)
      Expected: [[[97, 98, 99], []], null]
      Actual:   [[[97, 98, 99], [], []], null]
                 ↑ (pos 0)
      Stack Trace:
        /_/src/libraries/System.DirectoryServices.Protocols/tests/BerConverterTests.cs(200,0): at System.DirectoryServices.Protocols.Tests.BerConverterTests.Decode_Bytes_ReturnsExpected(String format, Byte[] values, Object[] expected)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=602282
**Error message validated:** `[BerConverterTests.cs(200,0): at System.DirectoryServices.Protocols.Tests.BerConverterTests.Decode_Bytes_ReturnsExpected`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/14/2024 1:39:27 AM UTC

**Comment by carlossanlop** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/99725
