### ISSUE TITLE
[mono][minijit] GC regression: v2_0_beta2_452950_452950_452950_

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#99739]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=602282
Build error leg or test failing: GC_Regressions._v2_0_beta2_452950_452950_452950_

## Error Message

```json
{
  "ErrorMessage" : "at GC_Regressions._v2_0_beta2_452950_452950_452950_._v2_0_beta2_452950_452950_452950_cmd()",
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/99713
- Queue: `mono minijit Pri0 Runtime Tests Run windows x64 release`
- Job result: https://dev.azure.com/dnceng-public/public/public%20Team/_build/results?buildId=602282&view=logs&j=0f62f1a3-554a-55c3-ebc5-36cfcbfb3f99&t=7dc63514-3350-5975-c010-1b2368d75740&l=32
- Log file: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-99713-merge-edb3e609f64a42f69a/PayloadGroup0/1/console.04510c8e.log?helixlogtype=result
- Output:
```
 Starting:    GC.Regressions.XUnitWrapper (parallel test collections = on [4 threads], stop on fail = off)
    GC\Regressions\v2.0-beta2\452950\452950\452950.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\h\w\B61509AF\w\B0DF0A0C\uploads\Reports\GC.Regressions\v2.0-beta2\452950\452950\452950.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\B61509AF\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  452950.dll 
      72
      Failed
      Expected: 100
      Actual: 1
      END EXECUTION - FAILED
      FAILED
      Test failed. Trying to see if dump file was created in C:\cores since 3/13/2024 10:13:51 PM
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=C:\h\w\B61509AF\p
      > C:\h\w\B61509AF\w\B0DF0A0C\e\GC\Regressions\v2.0-beta2\452950\452950\452950.cmd
      Stack Trace:
           at GC_Regressions._v2_0_beta2_452950_452950_452950_._v2_0_beta2_452950_452950_452950_cmd()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
      Output:
        
        Return code:      1
        Raw output file:      C:\h\w\B61509AF\w\B0DF0A0C\uploads\Reports\GC.Regressions\v2.0-beta2\452950\452950\452950.output.txt
        Raw output:
        BEGIN EXECUTION
         "C:\h\w\B61509AF\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  452950.dll 
        72
        Failed
        Expected: 100
        Actual: 1
        END EXECUTION - FAILED
        FAILED
        Test failed. Trying to see if dump file was created in C:\cores since 3/13/2024 10:13:51 PM
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=C:\h\w\B61509AF\p
        > C:\h\w\B61509AF\w\B0DF0A0C\e\GC\Regressions\v2.0-beta2\452950\452950\452950.cmd
  Finished:    GC.Regressions.XUnitWrapper
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=602282
**Error message validated:** `[at GC_Regressions._v2_0_beta2_452950_452950_452950_._v2_0_beta2_452950_452950_452950_cmd()`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/14/2024 1:48:08 AM UTC

**Comment by carlossanlop** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/99729
