### ISSUE TITLE
Failing test System.DirectoryServices.Protocols.Tests.BerConverterTests.Decode_Bytes_ReturnsExpected

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#99764]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=603272&view=logs&jobId=cb131f87-d5af-5ecc-6e5f-6dc86994859c
Build error leg or test failing: System.DirectoryServices.Protocols.Tests.BerConverterTests.Decode_Bytes_ReturnsExpected

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorPattern": "Decode_Bytes_ReturnsExpected.*FAIL",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-99422-merge-c5d5162539e94828b3/System.DirectoryServices.Protocols.Tests/1/console.29a618c4.log?helixlogtype=result)
```
    System.DirectoryServices.Protocols.Tests.BerConverterTests.Decode_Bytes_ReturnsExpected(format: "vv", values: [48, 132, 0, 0, 0, ���], expected: [["abc", ""], null]) [FAIL]
      Assert.Equal() Failure: Collections differ
                  (pos 0)
      Expected: [["abc", ""], null]
      Actual:   [["abc", "", ""], null]
                  (pos 0)
      Stack Trace:
        /_/src/libraries/System.DirectoryServices.Protocols/tests/BerConverterTests.cs(199,0): at System.DirectoryServices.Protocols.Tests.BerConverterTests.Decode_Bytes_ReturnsExpected(String format, Byte[] values, Object[] expected)
           at InvokeStub_BerConverterTests.Decode_Bytes_ReturnsExpected(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.DirectoryServices.Protocols.Tests.BerConverterTests.Decode_Bytes_ReturnsExpected(format: "VV", values: [48, 132, 0, 0, 0, ���], expected: [[[���], [���]], null]) [FAIL]
      Assert.Equal() Failure: Collections differ
                  (pos 0)
      Expected: [[[97, 98, 99], []], null]
      Actual:   [[[97, 98, 99], [], []], null]
                  (pos 0)
      Stack Trace:
        /_/src/libraries/System.DirectoryServices.Protocols/tests/BerConverterTests.cs(199,0): at System.DirectoryServices.Protocols.Tests.BerConverterTests.Decode_Bytes_ReturnsExpected(String format, Byte[] values, Object[] expected)
           at InvokeStub_BerConverterTests.Decode_Bytes_ReturnsExpected(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=603272
**Error message validated:** `[Decode_Bytes_ReturnsExpected.*FAIL`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/14/2024 2:52:59 PM UTC

**Comment by pavelsavara** [comment]
Duplicate https://github.com/dotnet/runtime/issues/99725
