### ISSUE TITLE
Test failure: Interop/Swift/SwiftAbiStress/SwiftAbiStress/SwiftAbiStress.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#99882]
**Failed in:** [runtime-coreclr jitstress-random 20240317.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=606164&view=ms.vss-test-web.build-test-results-tab&runId=14764766&resultId=118348&paneView=debug)

**Failed tests:**
```
coreclr osx x64 Checked jitstress_random_1 @ OSX.1200.Amd64.Open
    - Interop/Swift/SwiftAbiStress/SwiftAbiStress/SwiftAbiStress.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      /tmp/helix/working/AC1D09A3/w/B6F809A6/uploads/Swift/SwiftAbiStress/SwiftAbiStress/output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/AC1D09A3/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true SwiftAbiStress.dll ''
Running SwiftFunc0: OK
Running SwiftFunc1: OK
Running SwiftFunc2: OK
Running SwiftFunc3: OK
Running SwiftFunc4: OK
Running SwiftFunc5: OK
Running SwiftFunc6: OK
Running SwiftFunc7: OK
Running SwiftFunc8: OK
Running SwiftFunc9: OK
Running SwiftFunc10: OK
Running SwiftFunc11: OK
Running SwiftFunc12: OK
Running SwiftFunc13: OK
Running SwiftFunc14: OK
Running SwiftFunc15: OK
Running SwiftFunc16: OK
Running SwiftFunc17: OK
Running SwiftFunc18: OK
Running SwiftFunc19: OK
Running SwiftFunc20: OK
Running SwiftFunc21: OK
Running SwiftFunc22: OK
Running SwiftFunc23: OK
Running SwiftFunc24: OK
Running SwiftFunc25: OK
Running SwiftFunc26: OK
Running SwiftFunc27: OK
Running SwiftFunc28: OK
Running SwiftFunc29: OK
Running SwiftFunc30: OK
Running SwiftFunc31: OK
Running SwiftFunc32: OK
Running SwiftFunc33: OK
Running SwiftFunc34: OK
Running SwiftFunc35: Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 8413899507614185381
Actual:   5611232815251267807
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at SwiftAbiStress.TestSwiftFunc35()
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /cores since 3/17/2024 3:45:18 PM
Finish looking for *.crashreport.json. No new files created.
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /private/tmp/helix/working/AC1D09A3/w/B6F809A6/e/Interop/Interop/../Swift/SwiftAbiStress/SwiftAbiStress/SwiftAbiStress.sh
```

**Stack trace:**
```
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor274|25_275(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```
Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-03-17T19:42:20.44Z | runtime-coreclr jitstress-random | Checked-jitstress_random_1 | osx.1200.amd64.open | x64 | Interop/Swift/SwiftAbiStress/SwiftAbiStress/SwiftAbiStress.cmd | Failed | {"AzurePipelinesTestRunId":"14764766","DefinitionId":"159","BuildId":"606164","DefinitionName":"runtime-coreclr jitstress-random","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","configuration":"Checked-jitstress_random_1","BuildNumber":"20240317.1","architecture":"x64","System.JobAttempt":"1","operatingSystem":"OSX.1200.Amd64.Open","System.StageAttempt":"1","System.PhaseName":"run_test_p1__osx_x64_checked","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1"} | Schedule

**Comment by BruceForstall** [comment]
Also fails in runtime-jit-experimental:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=606209&view=ms.vss-test-web.build-test-results-tab
